const LEVEL2_BANK=[{"word":"describe","level":2,"definition":"to tell what something is like","example":"Please describe the puppy, so I can picture it.","imageKeyword":"child talking about picture"},
{"word":"explain","level":2,"definition":"to tell how or why","example":"Dad can explain why the sky looks orange at sunset.","imageKeyword":"dad explaining sunset to child"},
{"word":"solve","level":2,"definition":"to find the answer","example":"I worked hard to solve the math problem.","imageKeyword":"puzzle"},
{"word":"complete","level":2,"definition":"to finish all the parts","example":"I will complete my worksheet before lunch.","imageKeyword":"finished work"},
{"word":"arrange","level":2,"definition":"to put things in order","example":"We arrange the books by size on the shelf.","imageKeyword":"arrange books"},
{"word":"decide","level":2,"definition":"to choose after thinking","example":"I decided to bring an apple instead of chips.","imageKeyword":"choice"},
{"word":"suppose","level":2,"definition":"to guess that something might be true","example":"I suppose the bus is late because of rain.","imageKeyword":"bus rain"},
{"word":"mention","level":2,"definition":"to talk about something in just a few words","example":"She mentioned her trip but did not tell us the details.","imageKeyword":"person speaking briefly"},
{"word":"realize","level":2,"definition":"to understand suddenly","example":"I realized my mittens were still on the chair.","imageKeyword":"mittens"},
{"word":"repeat","level":2,"definition":"to say or do again","example":"Can you repeat the directions one more time?","imageKeyword":"loop arrows"},
{"word":"separate","level":2,"definition":"to put into different groups","example":"We separate the toys into cars and blocks.","imageKeyword":"sorting colored blocks into groups"},
{"word":"struggle","level":2,"definition":"to try hard when something is difficult","example":"I struggle with this knot, so I ask for help.","imageKeyword":"tangled knot"},
{"word":"succeed","level":2,"definition":"to do something you tried to do","example":"After weeks of practice, I succeeded in riding without training wheels.","imageKeyword":"bike success"},
{"word":"surround","level":2,"definition":"to be all around","example":"Tall trees surround the quiet cabin.","imageKeyword":"cabin trees"},
{"word":"wander","level":2,"definition":"to walk without a plan","example":"We wander through the park and look at flowers.","imageKeyword":"walk park"},
{"word":"ancient","level":2,"definition":"from a very long time ago","example":"We saw an ancient pot in the museum.","imageKeyword":"ancient pottery museum"},
{"word":"modern","level":2,"definition":"of the present time; not old","example":"Our modern classroom has a big screen.","imageKeyword":"classroom screen"},
{"word":"brilliant","level":2,"definition":"very smart or impressive; also very bright","example":"She had a brilliant idea for the science project.","imageKeyword":"flashlight"},
{"word":"fragile","level":2,"definition":"easy to break","example":"The fragile glass fell and cracked.","imageKeyword":"broken glass"},
{"word":"sturdy","level":2,"definition":"strong and not easy to break","example":"This sturdy chair holds me even when I wiggle.","imageKeyword":"wood chair"},
{"word":"swift","level":2,"definition":"very fast","example":"The swift rabbit ran across the field before we could blink.","imageKeyword":"running rabbit"},
{"word":"anxious","level":2,"definition":"feeling worried that something bad might happen","example":"I was anxious before the spelling bee, so I practiced.","imageKeyword":"spelling bee"},
{"word":"setting","level":2,"definition":"where and when a story happens","example":"The setting is a snowy mountain at night.","imageKeyword":"storybook showing castle at night"},
{"word":"plot","level":2,"definition":"what happens in the story","example":"The plot changes when the map goes missing.","imageKeyword":"missing map"},
{"word":"paragraph","level":2,"definition":"a group of sentences about one topic","example":"This paragraph tells how the turtle finds water.","imageKeyword":"paragraph of text on paper"},
{"word":"sentence","level":2,"definition":"a group of words that makes a complete thought","example":"My sentence ends with a period.","imageKeyword":"sentence"},
{"word":"fiction","level":2,"definition":"a story that is made up","example":"This book about dragons is fiction because none of it is real.","imageKeyword":"dragon book"},
{"word":"nonfiction","level":2,"definition":"writing with true facts","example":"A book about whales is nonfiction because it teaches facts.","imageKeyword":"whale facts"},
{"word":"main idea","level":2,"definition":"the most important point","example":"The main idea is that teamwork helps everyone win.","imageKeyword":"teamwork"},
{"word":"detail","level":2,"definition":"a small piece of information","example":"One detail is that the dog has a red collar.","imageKeyword":"red collar"},
{"word":"cause","level":2,"definition":"why something happens","example":"The cause of the puddle is the melted snow.","imageKeyword":"puddle snow"},
{"word":"effect","level":2,"definition":"what happens because of something","example":"The effect of the rain was a muddy playground.","imageKeyword":"muddy ground"},
{"word":"habitat","level":2,"definition":"the place where an animal lives","example":"A frog's habitat can be a pond with reeds.","imageKeyword":"frog pond"},
{"word":"insect","level":2,"definition":"a small animal with six legs","example":"An ant is an insect that can carry crumbs.","imageKeyword":"ant"},
{"word":"mammal","level":2,"definition":"an animal that has hair and drinks milk as a baby","example":"A dolphin is a mammal even though it lives in water.","imageKeyword":"dolphin"},
{"word":"reptile","level":2,"definition":"an animal with dry skin and scales like a snake","example":"A snake is a reptile that can slide quietly.","imageKeyword":"snake"},
{"word":"liquid","level":2,"definition":"something that flows like water","example":"Juice is a liquid that fills the cup.","imageKeyword":"juice cup"},
{"word":"gas","level":2,"definition":"a substance like air that is not a solid or a liquid","example":"Air is a gas that fills a balloon when you blow it up.","imageKeyword":"air filling balloon"},
{"word":"energy","level":2,"definition":"what your body needs to move, play, and do things","example":"Breakfast gives me energy to run and play all day.","imageKeyword":"running kid"},
{"word":"force","level":2,"definition":"a push or pull that moves things","example":"A force makes the swing move forward.","imageKeyword":"swing"},
{"word":"magnet","level":2,"definition":"something that pulls some metals","example":"The magnet grabbed the paper clip from the table.","imageKeyword":"magnet clip"},
{"word":"soil","level":2,"definition":"dirt that plants grow in","example":"Dark soil crumbled in my hand when I dug.","imageKeyword":"garden soil"},
{"word":"climate","level":2,"definition":"the usual weather in a place","example":"The desert climate is hot and dry most days.","imageKeyword":"desert"},
{"word":"season","level":2,"definition":"one part of the year like spring or winter","example":"Winter is the season when we wear coats and hats.","imageKeyword":"winter coat"},
{"word":"citizen","level":2,"definition":"a person who belongs to a country and has rights there","example":"Every citizen must follow the laws of their country.","imageKeyword":"passport"},
{"word":"government","level":2,"definition":"the group that makes rules for a place","example":"Our government makes laws to keep people safe.","imageKeyword":"city hall"},
{"word":"law","level":2,"definition":"a rule made by the government","example":"A law says we must stop at a red light.","imageKeyword":"red light"},
{"word":"rule","level":2,"definition":"something you must follow","example":"One classroom rule is to raise your hand.","imageKeyword":"classroom rules list"},
{"word":"map","level":2,"definition":"a drawing that shows where places are","example":"We used a map to find the zoo.","imageKeyword":"map"},
{"word":"globe","level":2,"definition":"a ball-shaped map of Earth","example":"I spun the globe to find Africa.","imageKeyword":"globe"},
{"word":"continent","level":2,"definition":"one of Earth's big land areas","example":"Asia is a continent with many countries.","imageKeyword":"continent"},
{"word":"country","level":2,"definition":"a nation with its own government","example":"Japan is a country made of islands.","imageKeyword":"flag"},
{"word":"state","level":2,"definition":"a part of a country","example":"Texas is a state in the United States.","imageKeyword":"state map"},
{"word":"city","level":2,"definition":"a large town","example":"The city has tall buildings and busy streets.","imageKeyword":"city skyline"},
{"word":"border","level":2,"definition":"a line between places","example":"A fence can mark the border of a yard.","imageKeyword":"border fence"},
{"word":"freedom","level":2,"definition":"being able to choose and act","example":"I have freedom to pick a book during reading time.","imageKeyword":"choose book"},
{"word":"election","level":2,"definition":"a time when people vote to choose a leader","example":"During an election, adults vote for the mayor.","imageKeyword":"ballot box"},
{"word":"subtract","level":2,"definition":"to take away","example":"I subtract one cookie after I eat it.","imageKeyword":"take away"},
{"word":"multiply","level":2,"definition":"to add the same number many times","example":"We multiply 3 by 2 to make 6.","imageKeyword":"times sign"},
{"word":"divide","level":2,"definition":"to split into equal parts","example":"We divide the pizza, so each friend gets a slice.","imageKeyword":"pizza slices"},
{"word":"sum","level":2,"definition":"the answer to an addition problem","example":"The sum of 5 and 4 is 9.","imageKeyword":"addition"},
{"word":"graph","level":2,"definition":"a picture that shows numbers","example":"Our graph shows more kids like apples than pears.","imageKeyword":"bar graph"},
{"word":"chart","level":2,"definition":"a table or picture that shows facts","example":"The chart tells what jobs we want to do.","imageKeyword":"class chart"},
{"word":"data","level":2,"definition":"facts we collect","example":"We wrote data about the weather each day.","imageKeyword":"weather notes"},
{"word":"length","level":2,"definition":"how long something is","example":"The length of the rope is three meters.","imageKeyword":"rope"},
{"word":"width","level":2,"definition":"the distance from one side to the other","example":"We measured the width of the door with a ruler.","imageKeyword":"door"},
{"word":"height","level":2,"definition":"how tall something is","example":"We checked my height by marking the wall.","imageKeyword":"height chart"},
{"word":"area","level":2,"definition":"the space inside a shape","example":"The area of the rug covers most of the floor.","imageKeyword":"rug"},
{"word":"shape","level":2,"definition":"the outline of something","example":"A stop sign has the shape of an octagon.","imageKeyword":"octagon"},
{"word":"angle","level":2,"definition":"the space between two lines that meet, measured in degrees","example":"A square has four angles that are all the same size.","imageKeyword":"right angle"},
{"word":"triple","level":2,"definition":"to make three times as much","example":"We need to triple the recipe to feed everyone.","imageKeyword":"measuring cups"},
{"word":"gradually","level":2,"definition":"little by little","example":"The paint color changed gradually from light to dark.","imageKeyword":"color fade"},
{"word":"immediately","level":2,"definition":"right away","example":"When the bell rang, we immediately lined up.","imageKeyword":"school line"},
{"word":"afterward","level":2,"definition":"later, after something else happened","example":"We cleaned up and afterward played a game.","imageKeyword":"clean up"},
{"word":"recently","level":2,"definition":"not long ago","example":"I recently learned to tie my shoes.","imageKeyword":"shoelaces"},
{"word":"frequently","level":2,"definition":"many times","example":"The baby frequently giggled during the silly song.","imageKeyword":"giggling baby"},
{"word":"rarely","level":2,"definition":"not often","example":"We rarely see snow in our town, so it feels special.","imageKeyword":"snowflakes"},
{"word":"occasionally","level":2,"definition":"sometimes","example":"I occasionally ride my bike to the library.","imageKeyword":"bike library"},
{"word":"however","level":2,"definition":"a word that means 'but' or 'on the other hand'","example":"I wanted to play outside; however, the rain was heavy.","imageKeyword":"rain window"},
{"word":"therefore","level":2,"definition":"for that reason; because of that","example":"The road was closed; therefore, we took a different path.","imageKeyword":"detour sign"},
{"word":"otherwise","level":2,"definition":"or else; if not","example":"Wear your boots, otherwise your feet will get wet.","imageKeyword":"rain boots"},
{"word":"turn into","level":2,"definition":"to change into something else","example":"The caterpillar will turn into a butterfly.","imageKeyword":"butterfly"},
{"word":"look forward to","level":2,"definition":"to feel excited about something coming","example":"I look forward to field day all year.","imageKeyword":"field day"},
{"word":"make up","level":2,"definition":"to invent","example":"We make up a funny story about a talking shoe.","imageKeyword":"funny story"},
{"word":"point out","level":2,"definition":"to show or tell someone about something they may not have noticed","example":"The teacher pointed out the comma in my sentence.","imageKeyword":"comma"},
{"word":"come across","level":2,"definition":"to find by chance","example":"I came across a shiny shell while walking on the beach.","imageKeyword":"shell"},
{"word":"break down","level":2,"definition":"to stop working","example":"Our old wagon broke down, so we carried the pumpkins.","imageKeyword":"broken wagon"},
{"word":"carry out","level":2,"definition":"to do a plan","example":"We carried out our science test step by step.","imageKeyword":"science test"},
{"word":"set up","level":2,"definition":"to get ready","example":"We set up the tent by spreading the poles on the ground.","imageKeyword":"tent setup"},
{"word":"courageous","level":2,"definition":"brave","example":"The courageous lifeguard jumped in to help the swimmer.","imageKeyword":"lifeguard"},
{"word":"honest","level":2,"definition":"telling the truth","example":"I was honest and told Mom I spilled the milk.","imageKeyword":"spilled milk"},
{"word":"loyal","level":2,"definition":"sticking with a friend","example":"Our loyal dog waited by the door every day.","imageKeyword":"dog waiting"},
{"word":"selfish","level":2,"definition":"caring only about you, not others","example":"It is selfish to take all the crayons and share none.","imageKeyword":"crayons"},
{"word":"thoughtful","level":2,"definition":"kind and careful about others","example":"It was thoughtful to make a card for our neighbor.","imageKeyword":"greeting card"},
{"word":"determined","level":2,"definition":"not giving up","example":"I was determined to finish the puzzle, even when it was hard.","imageKeyword":"determined child working hard"},
{"word":"about","level":2,"definition":"on the subject of","example":"We talked about planets during science.","imageKeyword":"planets"},
{"word":"act","level":2,"definition":"to do something","example":"We must act fast before the ice cream melts.","imageKeyword":"kid acting quickly"},
{"word":"action","level":2,"definition":"a thing someone does","example":"His quick action saved the cat from the tree.","imageKeyword":"rescuing cat from tree"},
{"word":"add","level":2,"definition":"to put together","example":"Add two more blocks to make the tower taller.","imageKeyword":"stack blocks"},
{"word":"address","level":2,"definition":"where someone lives","example":"I wrote my address on the postcard.","imageKeyword":"postcard"},
{"word":"adult","level":2,"definition":"a grown-up","example":"An adult helped us cross the street.","imageKeyword":"crosswalk"},
{"word":"afraid","level":2,"definition":"feeling like something bad might happen","example":"I was afraid in the dark until I turned on the lamp.","imageKeyword":"lamp"},
{"word":"again","level":2,"definition":"one more time","example":"He read his favorite poem again before bed.","imageKeyword":"reading poem"},
{"word":"agree","level":2,"definition":"to say yes to the same idea","example":"We agree that cleaning up makes the room nice.","imageKeyword":"kids agree"},
{"word":"alive","level":2,"definition":"living","example":"The plant looks alive when its leaves are green.","imageKeyword":"green plant"},
{"word":"alone","level":2,"definition":"by yourself","example":"I was alone in my room reading quietly.","imageKeyword":"reading alone"},
{"word":"also","level":2,"definition":"in addition; as well","example":"I brought water, and I also packed a snack.","imageKeyword":"snack"},
{"word":"always","level":2,"definition":"every time","example":"I always wash my hands before eating.","imageKeyword":"handwashing"},
{"word":"any","level":2,"definition":"some","example":"Do you have any pencils I can borrow?","imageKeyword":"pencils"},
{"word":"appear","level":2,"definition":"to show up","example":"A rainbow can appear after a storm.","imageKeyword":"rainbow"},
{"word":"arm","level":2,"definition":"the body part from shoulder to hand","example":"I carried the bag on my arm.","imageKeyword":"arm"},
{"word":"arrive","level":2,"definition":"to get to a place","example":"We arrive at school when the first bell rings.","imageKeyword":"school bus"},
{"word":"ask","level":2,"definition":"to use words to find out something you want to know","example":"I ask my teacher when I do not understand.","imageKeyword":"question"},
{"word":"asleep","level":2,"definition":"sleeping","example":"The baby was asleep in the stroller.","imageKeyword":"sleeping baby"},
{"word":"attack","level":2,"definition":"to try to hurt","example":"The goose tried to attack me, so I stepped back.","imageKeyword":"goose"},
{"word":"attempt","level":2,"definition":"a try","example":"My first attempt at juggling dropped the balls.","imageKeyword":"juggling"},
{"word":"attention","level":2,"definition":"watching and listening carefully","example":"Pay attention when I show the steps.","imageKeyword":"child listening with hand on ear"},
{"word":"awake","level":2,"definition":"not sleeping","example":"I stayed awake to hear the thunder.","imageKeyword":"child awake in bed at night"},
{"word":"backpack","level":2,"definition":"a bag you wear on your back","example":"I stuffed my lunch into my backpack.","imageKeyword":"backpack"},
{"word":"balance","level":2,"definition":"to stay steady and not fall","example":"I used my arms to balance on the log.","imageKeyword":"balance log"},
{"word":"balloon","level":2,"definition":"a rubber ball filled with air","example":"The balloon floated up when I let go.","imageKeyword":"balloon"},
{"word":"bare","level":2,"definition":"with nothing on top; uncovered","example":"My bare feet felt the cool grass.","imageKeyword":"bare feet"},
{"word":"bargain","level":2,"definition":"a good deal for a low price","example":"He found a bargain on the used bike and saved twenty dollars.","imageKeyword":"sale tag"},
{"word":"base","level":2,"definition":"the bottom part","example":"The base of the statue is made of stone.","imageKeyword":"statue base"},
{"word":"basic","level":2,"definition":"simple and important","example":"A basic rule is to be kind.","imageKeyword":"kindness"},
{"word":"battle","level":2,"definition":"a big fight","example":"The knights had a battle in our pretend game.","imageKeyword":"toy knights"},
{"word":"beach","level":2,"definition":"sandy land by the ocean","example":"We built a sandcastle at the beach.","imageKeyword":"sandcastle"},
{"word":"beam","level":2,"definition":"a line of light","example":"A beam from the flashlight lit the hallway.","imageKeyword":"flashlight beam"},
{"word":"because","level":2,"definition":"for the reason that","example":"I wore a hat because the sun was bright.","imageKeyword":"sun hat"},
{"word":"become","level":2,"definition":"to start to be","example":"Ice can become water when it gets warm.","imageKeyword":"ice melting water"},
{"word":"beg","level":2,"definition":"to ask for something in a way that shows you really want it","example":"The puppy begged for a bite by staring at my plate.","imageKeyword":"begging puppy"},
{"word":"begin","level":2,"definition":"to start","example":"We begin the race when the whistle blows.","imageKeyword":"whistle"},
{"word":"behavior","level":2,"definition":"how someone acts","example":"Good behavior means listening and sharing.","imageKeyword":"two kids sharing pizza slice"},
{"word":"believe","level":2,"definition":"to think something is true","example":"I believe the lost kitten will be found.","imageKeyword":"lost kitten"},
{"word":"better","level":2,"definition":"of higher quality than something else","example":"My handwriting looks better after practice.","imageKeyword":"handwriting"},
{"word":"bicycle","level":2,"definition":"a bike with two wheels","example":"I rode my bicycle down the sidewalk slowly.","imageKeyword":"bicycle"},
{"word":"blink","level":2,"definition":"to close and open your eyes quickly","example":"I blinked when the camera flash was bright.","imageKeyword":"blink"},
{"word":"block","level":2,"definition":"a section of a street between two corners","example":"The store is two blocks from our school.","imageKeyword":"city block"},
{"word":"blossom","level":2,"definition":"to produce flowers; to begin to flower","example":"The apple tree began to blossom in the warm spring sun.","imageKeyword":"cherry blossoms"},
{"word":"bossy","level":2,"definition":"always telling others what to do","example":"Being bossy can hurt friends' feelings.","imageKeyword":"child pointing finger at others"},
{"word":"bounce","level":2,"definition":"to spring up and down","example":"The ball will bounce if you drop it.","imageKeyword":"bouncing ball"},
{"word":"breakfast","level":2,"definition":"the first meal of the day","example":"I ate eggs for breakfast before school.","imageKeyword":"breakfast"},
{"word":"breathe","level":2,"definition":"to take air in and out","example":"I breathe slowly when I feel upset.","imageKeyword":"deep breath"},
{"word":"bright","level":2,"definition":"full of light","example":"The bright sun made me squint.","imageKeyword":"bright sun"},
{"word":"bring","level":2,"definition":"to carry something to a place or person","example":"Please bring your library book to school tomorrow.","imageKeyword":"library book"},
{"word":"broad","level":2,"definition":"very wide, stretching far from side to side","example":"The river is broad, so we used a boat.","imageKeyword":"wide river"},
{"word":"build","level":2,"definition":"to make by putting parts together","example":"We build a birdhouse with wood and nails.","imageKeyword":"birdhouse"},
{"word":"bundle","level":2,"definition":"a group tied together","example":"Dad carried a bundle of sticks for the fire.","imageKeyword":"bundle sticks"},
{"word":"butter","level":2,"definition":"a soft food made from milk","example":"I spread butter on warm toast.","imageKeyword":"butter toast"},
{"word":"cactus","level":2,"definition":"a desert plant with spines","example":"The cactus has sharp spines, so I do not touch it.","imageKeyword":"cactus"},
{"word":"calendar","level":2,"definition":"a chart of days and months","example":"I circled my birthday on the calendar.","imageKeyword":"calendar"},
{"word":"camel","level":2,"definition":"a desert animal with humps","example":"A camel stores fat in its humps.","imageKeyword":"camel"},
{"word":"camp","level":2,"definition":"to sleep outdoors","example":"We camped in a tent and heard owls.","imageKeyword":"camping"},
{"word":"capture","level":2,"definition":"to catch and hold","example":"The net can capture the butterfly for a quick look.","imageKeyword":"butterfly net"},
{"word":"careful","level":2,"definition":"trying not to make mistakes","example":"Be careful with scissors because they are sharp.","imageKeyword":"scissors"},
{"word":"carpet","level":2,"definition":"soft floor covering","example":"I sat on the carpet for story time.","imageKeyword":"class carpet"},
{"word":"cart","level":2,"definition":"a small wagon","example":"We pushed the cart through the grocery store.","imageKeyword":"shopping cart"},
{"word":"carve","level":2,"definition":"to cut a shape into something","example":"We carved a face into the pumpkin.","imageKeyword":"carved pumpkin"},
{"word":"ceiling","level":2,"definition":"the top part of a room, above your head","example":"The ceiling fan spun above my head.","imageKeyword":"ceiling fan"},
{"word":"center","level":2,"definition":"the middle","example":"The star is in the center of the flag.","imageKeyword":"star in middle of flag"},
{"word":"chance","level":2,"definition":"a time when you can try something","example":"I got a chance to be line leader today.","imageKeyword":"line leader"},
{"word":"change","level":2,"definition":"to become different","example":"Leaves change color in the fall.","imageKeyword":"fall leaves"},
{"word":"choice","level":2,"definition":"something you pick","example":"My choice was the blue marker.","imageKeyword":"blue marker"},
{"word":"circle","level":2,"definition":"a round shape","example":"I drew a circle around the correct answer.","imageKeyword":"circle"},
{"word":"climb","level":2,"definition":"to go up using hands and feet","example":"I climbed the ladder to the slide.","imageKeyword":"playground ladder"},
{"word":"close","level":2,"definition":"to shut","example":"Please close the door, so it stays quiet.","imageKeyword":"closed door"},
{"word":"clue","level":2,"definition":"a hint that helps you know","example":"A muddy footprint was a clue that someone came in.","imageKeyword":"footprint"},
{"word":"coast","level":2,"definition":"land next to the ocean","example":"We drove along the coast and saw waves.","imageKeyword":"ocean coast"},
{"word":"comfort","level":2,"definition":"to help someone feel better","example":"A hug can comfort a sad friend.","imageKeyword":"hug"},
{"word":"common","level":2,"definition":"happening a lot","example":"It is common to see squirrels in this park.","imageKeyword":"squirrel"},
{"word":"complain","level":2,"definition":"to say you are unhappy about something","example":"I did not complain about chores; I just did them.","imageKeyword":"chores"},
{"word":"confuse","level":2,"definition":"to mix up","example":"I confuse left and right, so I check my hands.","imageKeyword":"confused child looking at two doors"},
{"word":"connect","level":2,"definition":"to join together","example":"We connect the train cars with a hook.","imageKeyword":"toy train"},
{"word":"corner","level":2,"definition":"where two sides meet","example":"The spider hid in the corner of the room.","imageKeyword":"spider corner"},
{"word":"cost","level":2,"definition":"how much money something takes","example":"The cost of the toy was three dollars.","imageKeyword":"three dollar toy price"},
{"word":"cotton","level":2,"definition":"a soft plant fiber","example":"The cotton ball felt fluffy.","imageKeyword":"cotton ball"},
{"word":"course","level":2,"definition":"a path or track to follow","example":"The obstacle course had cones to run around.","imageKeyword":"obstacle course"},
{"word":"crash","level":2,"definition":"to hit with a loud noise","example":"The wave crashed against the rocks.","imageKeyword":"wave crash"},
{"word":"make","level":2,"definition":"to build or create something; also to cause something to happen","example":"We make a paper snowflake by folding and cutting.","imageKeyword":"paper snowflake"},
{"word":"crumble","level":2,"definition":"to break into small pieces","example":"The dry cookie began to crumble in my hand.","imageKeyword":"crumbs"},
{"word":"cuddle","level":2,"definition":"to hug close","example":"I cuddled my teddy when I felt scared.","imageKeyword":"teddy bear"},
{"word":"custom","level":2,"definition":"a special way people do things","example":"In our family, a custom is singing at birthdays.","imageKeyword":"birthday song"},
{"word":"cycle","level":2,"definition":"a pattern that repeats","example":"The water cycle includes rain and clouds.","imageKeyword":"water cycle"},
{"word":"danger","level":2,"definition":"something that could hurt you","example":"The wet floor is a danger because it is slippery.","imageKeyword":"wet floor"},
{"word":"dark","level":2,"definition":"with little light","example":"It was dark, so I used a nightlight.","imageKeyword":"nightlight"},
{"word":"deal","level":2,"definition":"an agreement between people","example":"We made a deal: I clean up, then I play.","imageKeyword":"handshake"},
{"word":"delay","level":2,"definition":"to make something late","example":"A flat tire can delay the trip.","imageKeyword":"flat tire"},
{"word":"delight","level":2,"definition":"great happiness","example":"It was a delight to find a note in my lunch.","imageKeyword":"lunch note"},
{"word":"deny","level":2,"definition":"to say something is not true","example":"I could not deny it because the crumbs were on my shirt.","imageKeyword":"crumbs shirt"},
{"word":"depend","level":2,"definition":"to need someone or something; also to be decided by something","example":"Plants depend on water to grow.","imageKeyword":"watering plant"},
{"word":"destroy","level":2,"definition":"to break so it cannot be used","example":"The storm can destroy a sandcastle in minutes.","imageKeyword":"sandcastle waves"},
{"word":"dig","level":2,"definition":"to make a hole with hands or a tool","example":"We dig in the garden to plant seeds.","imageKeyword":"digging"},
{"word":"dinner","level":2,"definition":"the evening meal","example":"We ate soup for dinner.","imageKeyword":"dinner bowl"},
{"word":"find","level":2,"definition":"to locate something","example":"I need to find my lost library book before it is due.","imageKeyword":"child searching for lost book"},
{"word":"distance","level":2,"definition":"how far apart things are","example":"The distance to the park is two blocks.","imageKeyword":"road"},
{"word":"dizzy","level":2,"definition":"feeling like you are spinning","example":"I felt dizzy after turning in circles.","imageKeyword":"spinning"},
{"word":"dollar","level":2,"definition":"money worth 100 cents","example":"I saved one dollar in my piggy bank.","imageKeyword":"dollar"},
{"word":"donate","level":2,"definition":"to give away for free to help people in need","example":"We donate canned food to the shelter.","imageKeyword":"food donation"},
{"word":"doorway","level":2,"definition":"an opening for a door","example":"I stood in the doorway and waved goodbye.","imageKeyword":"doorway"},
{"word":"downstairs","level":2,"definition":"on a lower floor","example":"My shoes are downstairs by the door.","imageKeyword":"shoes by door at bottom of stairs"},
{"word":"drift","level":2,"definition":"to move slowly","example":"The leaf drifted down onto the pond.","imageKeyword":"leaf on water"},
{"word":"drown","level":2,"definition":"to go under water and not be able to breathe","example":"We wear life jackets so no one can drown.","imageKeyword":"life jacket"},
{"word":"earn","level":2,"definition":"to get by working","example":"I earn a sticker when I help clean up.","imageKeyword":"reward sticker"},
{"word":"earth","level":2,"definition":"the planet we live on","example":"Earth looks blue in pictures from space.","imageKeyword":"planet earth"},
{"word":"edge","level":2,"definition":"the outside line of something","example":"I stayed away from the edge of the pool.","imageKeyword":"pool edge"},
{"word":"enter","level":2,"definition":"to go in","example":"We enter the classroom quietly.","imageKeyword":"classroom door"},
{"word":"escape","level":2,"definition":"to get away","example":"The hamster tried to escape the cage, so we closed it.","imageKeyword":"hamster cage"},
{"word":"exact","level":2,"definition":"completely correct; with no mistakes","example":"The exact answer was 15, not 14.","imageKeyword":"correct checkmark on paper"},
{"word":"fair","level":2,"definition":"treating people the same and right","example":"It is fair when everyone gets one turn.","imageKeyword":"equal sharing among kids"},
{"word":"famous","level":2,"definition":"known by many people","example":"The famous statue is in the city square.","imageKeyword":"statue"},
{"word":"far","level":2,"definition":"not near","example":"My grandma lives far away, so we call her.","imageKeyword":"phone call"},
{"word":"farm","level":2,"definition":"a place where crops or animals are raised","example":"On the farm, we fed chickens corn.","imageKeyword":"farm"},
{"word":"fence","level":2,"definition":"a barrier around a place","example":"The fence kept the dog in the yard.","imageKeyword":"fence"},
{"word":"field","level":2,"definition":"an open area of land","example":"We played soccer in the field.","imageKeyword":"soccer field"},
{"word":"fill","level":2,"definition":"to make full","example":"Fill the bottle with water from the sink.","imageKeyword":"fill bottle"},
{"word":"finish","level":2,"definition":"to end","example":"I will finish my book before bedtime.","imageKeyword":"bedtime reading"},
{"word":"fit","level":2,"definition":"to be the right size","example":"The key did not fit the lock, so we tried another.","imageKeyword":"key lock"},
{"word":"flour","level":2,"definition":"powder used for baking","example":"We mixed flour into the batter.","imageKeyword":"flour"},
{"word":"foam","level":2,"definition":"lots of tiny bubbles","example":"Foam formed on the waves near the shore.","imageKeyword":"sea foam"},
{"word":"fold","level":2,"definition":"to bend over","example":"Fold the paper to make a card.","imageKeyword":"folding paper"},
{"word":"follow","level":2,"definition":"to go after","example":"The ducklings follow their mother to the pond.","imageKeyword":"ducklings"},
{"word":"fork","level":2,"definition":"a tool with prongs for eating","example":"I used a fork to pick up noodles.","imageKeyword":"fork"},
{"word":"friendship","level":2,"definition":"being friends and caring","example":"Our friendship grew because we helped each other.","imageKeyword":"friends"},
{"word":"frighten","level":2,"definition":"to scare","example":"The loud bang could frighten the puppy.","imageKeyword":"loud noise"},
{"word":"front","level":2,"definition":"the part that faces forward","example":"Sit in the front row, so you can see the board.","imageKeyword":"front row"},
{"word":"frozen","level":2,"definition":"turned to ice","example":"The pond was frozen, so we stayed off it.","imageKeyword":"frozen pond"},
{"word":"gentleman","level":2,"definition":"a polite man","example":"The gentleman held the door for us.","imageKeyword":"holding door"},
{"word":"glad","level":2,"definition":"happy","example":"I was glad when my team won.","imageKeyword":"smiling child celebrating"},
{"word":"glide","level":2,"definition":"to move smoothly","example":"The ice skater could glide without falling.","imageKeyword":"ice skating"},
{"word":"glitter","level":2,"definition":"to sparkle","example":"The stars glitter in the night sky.","imageKeyword":"sparkle"},
{"word":"goal","level":2,"definition":"something you want to do","example":"My goal is to read ten books this month.","imageKeyword":"reading goal"},
{"word":"grasp","level":2,"definition":"to hold tightly","example":"I grasped the rail as I climbed the stairs.","imageKeyword":"hand rail"},
{"word":"greet","level":2,"definition":"to say hello","example":"We greet our teacher each morning.","imageKeyword":"hello"},
{"word":"grin","level":2,"definition":"a big smile","example":"I could not stop my grin when I saw the surprise.","imageKeyword":"big smile"},
{"word":"groan","level":2,"definition":"to make a deep sound when in pain or upset","example":"I groaned when I bumped my toe.","imageKeyword":"child stubbing toe"},
{"word":"grow","level":2,"definition":"to get bigger","example":"My sunflower can grow taller than me.","imageKeyword":"sunflower"},
{"word":"guard","level":2,"definition":"to watch and protect","example":"The dog guards the yard by barking at strangers.","imageKeyword":"guard dog"},
{"word":"guess","level":2,"definition":"to try to answer without knowing","example":"I guess the number of jellybeans in the jar.","imageKeyword":"jellybeans"},
{"word":"habit","level":2,"definition":"something you do often","example":"Brushing my teeth is a good habit.","imageKeyword":"toothbrush"},
{"word":"hallway","level":2,"definition":"a long passage inside a building","example":"We walked quietly down the hallway.","imageKeyword":"school hallway"},
{"word":"handful","level":2,"definition":"as much as your hand can hold","example":"I grabbed a handful of popcorn.","imageKeyword":"popcorn"},
{"word":"harm","level":2,"definition":"hurt or damage","example":"Glass on the ground can harm bare feet.","imageKeyword":"caution sharp glass on ground"},
{"word":"harvest","level":2,"definition":"to pick crops","example":"We harvest apples from the tree in fall.","imageKeyword":"apple picking"},
{"word":"heal","level":2,"definition":"to get better after being hurt or sick","example":"My scraped knee will heal with a bandage.","imageKeyword":"bandage"},
{"word":"hidden","level":2,"definition":"not easy to see","example":"The hidden key was under the mat.","imageKeyword":"key under mat"},
{"word":"hint","level":2,"definition":"a small clue","example":"She gave me a hint by pointing to the picture.","imageKeyword":"pointing"},
{"word":"history","level":2,"definition":"stories and facts from long ago","example":"In history class we learned about old ships.","imageKeyword":"old ship"},
{"word":"holiday","level":2,"definition":"a special day","example":"On the holiday, we visited family and ate pie.","imageKeyword":"family dinner"},
{"word":"hop","level":2,"definition":"to jump on one foot","example":"I can hop like a bunny across the rug.","imageKeyword":"hop"},
{"word":"horizon","level":2,"definition":"where the sky seems to meet the land","example":"The sun sank below the horizon.","imageKeyword":"sunset"},
{"word":"hurt","level":2,"definition":"to feel pain","example":"My arm hurt after I fell off the swing.","imageKeyword":"hurt arm"},
{"word":"hurry","level":2,"definition":"to move quickly","example":"We hurry, so we do not miss the bus.","imageKeyword":"running to bus"},
{"word":"idea","level":2,"definition":"a thought or plan","example":"My idea was to build a fort with blankets.","imageKeyword":"blanket fort"},
{"word":"ignore","level":2,"definition":"to not pay attention","example":"I ignore the buzzing fly and keep reading.","imageKeyword":"fly"},
{"word":"include","level":2,"definition":"to have as a part","example":"The lunch will include fruit and milk.","imageKeyword":"lunch tray"},
{"word":"inside","level":2,"definition":"in the inner part","example":"The note was inside the envelope.","imageKeyword":"envelope"},
{"word":"invite","level":2,"definition":"to ask someone to come","example":"I invite my neighbor to my party.","imageKeyword":"party invite"},
{"word":"jacket","level":2,"definition":"a short coat","example":"I zipped my jacket because it was chilly.","imageKeyword":"jacket"},
{"word":"judge","level":2,"definition":"to decide what is best","example":"The teachers judged which painting was the best.","imageKeyword":"ribbon"},
{"word":"jump","level":2,"definition":"to push off the ground","example":"I can jump over the puddle.","imageKeyword":"jump puddle"},
{"word":"key","level":2,"definition":"something that opens a lock","example":"The key turned, and the door opened.","imageKeyword":"key"},
{"word":"kind","level":2,"definition":"nice and caring","example":"It is kind to share your seat.","imageKeyword":"child offering seat to friend"},
{"word":"knee","level":2,"definition":"the joint in your leg","example":"I bent my knee to tie my shoe.","imageKeyword":"leg with arrow pointing to knee"},
{"word":"kneel","level":2,"definition":"to rest on your knees","example":"I kneel to look closely at the ant hill.","imageKeyword":"ant hill"},
{"word":"knock","level":2,"definition":"to tap on a door","example":"I knock before I enter a room.","imageKeyword":"knocking"},
{"word":"lantern","level":2,"definition":"a lamp you can carry","example":"We carried a lantern on the night walk.","imageKeyword":"lantern"},
{"word":"laugh","level":2,"definition":"to make a happy sound","example":"The joke made us laugh until our sides hurt.","imageKeyword":"laughing"},
{"word":"leaf","level":2,"definition":"the flat green part of a plant","example":"A yellow leaf fell from the tree.","imageKeyword":"fall leaf"},
{"word":"leak","level":2,"definition":"to let water or other fluid drip out through a small hole","example":"The bottle began to leak, making a wet spot.","imageKeyword":"leaking bottle"},
{"word":"learn","level":2,"definition":"to get new knowledge","example":"I learn new words when I read every day.","imageKeyword":"reading"},
{"word":"least","level":2,"definition":"the smallest amount","example":"Pick the least messy paint color for the table.","imageKeyword":"paint"},
{"word":"library","level":2,"definition":"a place to borrow books","example":"We whispered in the library and chose books.","imageKeyword":"library"},
{"word":"limit","level":2,"definition":"the farthest point or amount","example":"The speed limit sign says 25.","imageKeyword":"speed limit"},
{"word":"listen","level":2,"definition":"to use your ears","example":"Listen for the timer bell.","imageKeyword":"ear hearing bell ring"},
{"word":"lunch","level":2,"definition":"a midday meal","example":"I ate a sandwich for lunch.","imageKeyword":"lunch"},
{"word":"machine","level":2,"definition":"a tool with moving parts","example":"The washing machine spins the clothes.","imageKeyword":"washing machine"},
{"word":"magic","level":2,"definition":"special power that does not seem real","example":"She believed in magic after the coin disappeared from her hand.","imageKeyword":"magic trick"},
{"word":"major","level":2,"definition":"big or important","example":"A major storm can close schools.","imageKeyword":"storm"},
{"word":"marble","level":2,"definition":"a small glass ball","example":"The marble rolled under the couch.","imageKeyword":"marble"},
{"word":"mask","level":2,"definition":"a cover for your face","example":"I wore a mask shaped like a tiger.","imageKeyword":"tiger mask"},
{"word":"matter","level":2,"definition":"anything that takes up space","example":"Air is matter even though you cannot see it.","imageKeyword":"air"},
{"word":"memory","level":2,"definition":"something you recall","example":"My best memory is building snowmen with Dad.","imageKeyword":"snowman"},
{"word":"message","level":2,"definition":"words someone sends to another person","example":"I left a message on the fridge for Dad.","imageKeyword":"sticky note on fridge"},
{"word":"minute","level":2,"definition":"a short time, 60 seconds","example":"Wait one minute, and the timer will ring.","imageKeyword":"timer"},
{"word":"mirror","level":2,"definition":"a shiny flat thing that shows your face when you look at it","example":"I saw my messy hair in the mirror.","imageKeyword":"mirror"},
{"word":"mist","level":2,"definition":"very thin cloud near the ground that makes things hard to see clearly","example":"Morning mist made the grass look shiny.","imageKeyword":"morning mist"},
{"word":"mix","level":2,"definition":"to stir together","example":"Mix the paint to make purple.","imageKeyword":"mix paint"},
{"word":"model","level":2,"definition":"a small copy of something","example":"We made a model of the solar system.","imageKeyword":"solar system model"},
{"word":"mood","level":2,"definition":"how you feel","example":"My mood became happy when the sun came out.","imageKeyword":"happy sun"},
{"word":"move","level":2,"definition":"to change position","example":"Please move your chair closer to the table.","imageKeyword":"chair"},
{"word":"mystery","level":2,"definition":"something hard to explain","example":"It was a mystery who ate the last cupcake.","imageKeyword":"missing cupcake"},
{"word":"nature","level":2,"definition":"plants, animals, and outdoors","example":"We explored nature and found acorns.","imageKeyword":"acorn"},
{"word":"near","level":2,"definition":"close by","example":"Sit near the front, so you can hear.","imageKeyword":"near"},
{"word":"neatly","level":2,"definition":"in a clean and tidy way","example":"She wrote neatly, so every letter was clear.","imageKeyword":"neat writing"},
{"word":"never","level":2,"definition":"not ever","example":"I never touch a hot stove.","imageKeyword":"hot stove"},
{"word":"noisy","level":2,"definition":"full of sound","example":"The room was noisy with all the kids talking.","imageKeyword":"cafeteria"},
{"word":"north","level":2,"definition":"one direction on a compass","example":"The compass needle points north.","imageKeyword":"compass"},
{"word":"note","level":2,"definition":"a short written message","example":"I wrote a note to my teacher about my absence.","imageKeyword":"note"},
{"word":"object","level":2,"definition":"something you can see or touch","example":"The ball is an object that can roll.","imageKeyword":"ball"},
{"word":"ocean","level":2,"definition":"a very large body of salt water","example":"The ocean waves crashed on the shore.","imageKeyword":"ocean waves"},
{"word":"offer","level":2,"definition":"to give or present","example":"I offer my seat to someone who is tired.","imageKeyword":"offering seat"},
{"word":"opinion","level":2,"definition":"what you think","example":"In my opinion, chocolate ice cream is best.","imageKeyword":"ice cream"},
{"word":"opposite","level":2,"definition":"completely different","example":"Hot is the opposite of cold.","imageKeyword":"hot cold"},
{"word":"order","level":2,"definition":"a way things are arranged","example":"Put the steps in order from first to last.","imageKeyword":"steps"},
{"word":"outside","level":2,"definition":"not inside","example":"We played outside under the big tree.","imageKeyword":"play outside"},
{"word":"over","level":2,"definition":"above or across","example":"The plane flew over our house.","imageKeyword":"plane"},
{"word":"palace","level":2,"definition":"a large home for a king or queen","example":"The palace had shiny floors and tall doors.","imageKeyword":"palace"},
{"word":"path","level":2,"definition":"a way to walk","example":"We followed the path through the woods.","imageKeyword":"forest path"},
{"word":"pause","level":2,"definition":"to stop for a short time","example":"I paused to tie my shoe during the run.","imageKeyword":"tie shoe"},
{"word":"picnic","level":2,"definition":"a meal eaten outside","example":"We had a picnic on a blanket in the park.","imageKeyword":"picnic"},
{"word":"planet","level":2,"definition":"a big round thing in space that goes around a star","example":"Earth is a planet that goes around the sun.","imageKeyword":"planet"},
{"word":"plastic","level":2,"definition":"a light strong material used to make bottles, toys, and many other things","example":"The plastic bottle can be recycled.","imageKeyword":"plastic bottle"},
{"word":"playground","level":2,"definition":"a place to play outside at school","example":"We raced to the playground after class.","imageKeyword":"playground"},
{"word":"polite","level":2,"definition":"showing good manners","example":"It is polite to say excuse me.","imageKeyword":"polite"},
{"word":"praise","level":2,"definition":"to say something good about someone","example":"My teacher praised my neat work with a gold star.","imageKeyword":"gold star"},
{"word":"prepare","level":2,"definition":"to get ready by doing what is needed","example":"We prepare for the trip by packing snacks.","imageKeyword":"packing snacks"},
{"word":"price","level":2,"definition":"how much it costs","example":"The price on the tag was five dollars.","imageKeyword":"price tag"},
{"word":"prize","level":2,"definition":"something you win","example":"I won a prize for the best costume.","imageKeyword":"trophy"},
{"word":"protect","level":2,"definition":"to keep safe","example":"Sunscreen helps protect my skin from sunburn.","imageKeyword":"sunscreen"},
{"word":"quiet","level":2,"definition":"with little noise","example":"The room was quiet during the test.","imageKeyword":"quiet classroom"},
{"word":"quiz","level":2,"definition":"a short test","example":"We had a quiz on spelling words.","imageKeyword":"quiz"},
{"word":"raise","level":2,"definition":"to lift","example":"Raise your hand if you know the answer.","imageKeyword":"raise hand"},
{"word":"range","level":2,"definition":"an area between two ends","example":"The mountain range looked like a row of teeth.","imageKeyword":"mountains"},
{"word":"reach","level":2,"definition":"to stretch to touch","example":"I could not reach the top shelf.","imageKeyword":"reach shelf"},
{"word":"recycle","level":2,"definition":"to use again by making something new","example":"We recycle cans by putting them in the blue bin.","imageKeyword":"recycling bin"},
{"word":"refund","level":2,"definition":"money given back","example":"The store gave a refund when the toy was broken.","imageKeyword":"refund"},
{"word":"relax","level":2,"definition":"to rest and feel calm","example":"I relax by listening to soft music.","imageKeyword":"relax music"},
{"word":"rescue","level":2,"definition":"to save from danger","example":"The firefighters rushed in to rescue the kitten from the tree.","imageKeyword":"firefighter"},
{"word":"respect","level":2,"definition":"to treat someone kindly and fairly","example":"We show respect by listening when others speak.","imageKeyword":"students listening respectfully"},
{"word":"result","level":2,"definition":"what happens in the end","example":"The result of watering was a taller plant.","imageKeyword":"growing plant"},
{"word":"return","level":2,"definition":"to go back or give back","example":"I will return the library book tomorrow.","imageKeyword":"return book"},
{"word":"river","level":2,"definition":"a flowing stream of water","example":"The river moved fast after the rain.","imageKeyword":"river"},
{"word":"role","level":2,"definition":"a part in a play or job","example":"My role in the play is the narrator.","imageKeyword":"narrator"},
{"word":"route","level":2,"definition":"the way to go","example":"The bus route stops at our corner.","imageKeyword":"bus route"},
{"word":"safe","level":2,"definition":"not in danger","example":"Wear a helmet to stay safe on your bike.","imageKeyword":"helmet"},
{"word":"sail","level":2,"definition":"to travel by boat","example":"We watched a boat sail across the bay.","imageKeyword":"sailboat"},
{"word":"save","level":2,"definition":"to keep for later","example":"I will save my dessert for after dinner.","imageKeyword":"save dessert"},
{"word":"scared","level":2,"definition":"feeling fear about something","example":"I felt scared during the thunder, so I held my blanket.","imageKeyword":"scared child under blanket"},
{"word":"scatter","level":2,"definition":"to spread out","example":"The wind began to scatter the papers.","imageKeyword":"papers flying"},
{"word":"score","level":2,"definition":"to get points in a game","example":"She managed to score the winning basket just as the buzzer sounded.","imageKeyword":"scoreboard"},
{"word":"shade","level":2,"definition":"a place where sunlight is blocked, so it is cooler","example":"We sat in the shade under a tree.","imageKeyword":"tree shade"},
{"word":"shore","level":2,"definition":"land next to water","example":"We found shells on the shore.","imageKeyword":"shore shells"},
{"word":"signal","level":2,"definition":"a sound, light, or movement that gives a message","example":"The traffic signal turned green, so cars went.","imageKeyword":"traffic light"},
{"word":"simple","level":2,"definition":"easy; not complex","example":"A simple snack is an apple.","imageKeyword":"apple"},
{"word":"slippery","level":2,"definition":"easy to slide on","example":"The icy step was slippery, so I held the rail.","imageKeyword":"icy steps"},
{"word":"smell","level":2,"definition":"to notice with your nose","example":"I can smell popcorn from the kitchen.","imageKeyword":"child sniffing popcorn"},
{"word":"snap","level":2,"definition":"to break with a quick sound","example":"The twig snapped under my shoe.","imageKeyword":"snapped twig"},
{"word":"soak","level":2,"definition":"to become very wet","example":"The rain soaked my shoes on the way to school.","imageKeyword":"wet socks"},
{"word":"special","level":2,"definition":"different in a good way","example":"This is a special day because it is your birthday.","imageKeyword":"birthday"},
{"word":"store","level":2,"definition":"a place to buy things","example":"We went to the store for bread.","imageKeyword":"store"},
{"word":"strong","level":2,"definition":"having a lot of power","example":"A strong rope can pull the sled.","imageKeyword":"thick strong rope pulling sled"},
{"word":"stuck","level":2,"definition":"unable to move","example":"My zipper was stuck, so I asked for help.","imageKeyword":"stuck zipper"},
{"word":"suggest","level":2,"definition":"to offer an idea","example":"I suggest we bring water on the hike.","imageKeyword":"water bottle"},
{"word":"support","level":2,"definition":"to hold up or help","example":"The beam supports the roof above us.","imageKeyword":"wood beam"},
{"word":"surface","level":2,"definition":"the top layer","example":"Bubbles rose to the surface of the water.","imageKeyword":"water surface"},
{"word":"swallow","level":2,"definition":"to move food down your throat","example":"I swallowed the water after I took a sip.","imageKeyword":"drinking"},
{"word":"sweep","level":2,"definition":"to clean with a broom","example":"I sweep the floor to collect the crumbs.","imageKeyword":"broom"},
{"word":"sweet","level":2,"definition":"tasting like sugar","example":"The sweet strawberry tasted like candy.","imageKeyword":"strawberry"},
{"word":"talent","level":2,"definition":"something you are good at","example":"My talent is drawing animals.","imageKeyword":"drawing"},
{"word":"taste","level":2,"definition":"flavor in your mouth","example":"The lemon taste made my lips pucker.","imageKeyword":"lemon"},
{"word":"team","level":2,"definition":"a group working together","example":"Our team passed the ball to score.","imageKeyword":"sports team"},
{"word":"tease","level":2,"definition":"to make fun of","example":"Do not tease; use kind words.","imageKeyword":"kind words"},
{"word":"temperature","level":2,"definition":"how hot or cold something is","example":"The temperature was very low today.","imageKeyword":"thermometer"},
{"word":"tend","level":2,"definition":"to take care of","example":"We tend the garden by pulling weeds.","imageKeyword":"garden"},
{"word":"tightly","level":2,"definition":"holding or fitting firmly, not loose","example":"Hold the kite string tightly in the wind.","imageKeyword":"kite string"},
{"word":"little","level":2,"definition":"small","example":"A little seed can grow into a tall tree.","imageKeyword":"seed"},
{"word":"track","level":2,"definition":"a path or a place to run","example":"We ran one lap around the track.","imageKeyword":"running track"},
{"word":"travel","level":2,"definition":"to go from place to place","example":"We travel by train to visit Aunt May.","imageKeyword":"train"},
{"word":"trick","level":2,"definition":"something that surprises or fools","example":"The magic trick made the coin disappear.","imageKeyword":"magic coin"},
{"word":"trust","level":2,"definition":"to believe someone will do the right thing","example":"I trust my friend to keep my secret safe.","imageKeyword":"trust"},
{"word":"turn","level":2,"definition":"to spin or change direction; also a chance to do something","example":"She turned the key to open the door.","imageKeyword":"turning key in lock"},
{"word":"under","level":2,"definition":"below","example":"The puppy hid under the table.","imageKeyword":"puppy under table"},
{"word":"upstairs","level":2,"definition":"on a higher floor","example":"My backpack is upstairs in my room.","imageKeyword":"backpack in bedroom upstairs"},
{"word":"usual","level":2,"definition":"what happens most of the time","example":"My usual snack is a banana.","imageKeyword":"banana"},
{"word":"visit","level":2,"definition":"to go see","example":"We visit the dentist twice a year.","imageKeyword":"dentist"},
{"word":"voice","level":2,"definition":"the sound of a person talking","example":"I recognized Dad's voice on the phone.","imageKeyword":"phone"},
{"word":"vote","level":2,"definition":"to choose by marking a choice","example":"Adults vote to pick a leader.","imageKeyword":"voting"},
{"word":"wait","level":2,"definition":"to stay until something happens","example":"We wait for the bus in a line.","imageKeyword":"bus stop"},
{"word":"warmth","level":2,"definition":"a nice cozy heat","example":"The blanket gave warmth on a cold night.","imageKeyword":"warm blanket"},
{"word":"warn","level":2,"definition":"to tell about danger","example":"I warned my brother that the pan was hot.","imageKeyword":"hot pan"},
{"word":"waterfall","level":2,"definition":"water that falls over a cliff","example":"The waterfall was loud like a drum.","imageKeyword":"waterfall"},
{"word":"weather","level":2,"definition":"what the sky is like outside","example":"The weather was windy, so my hat flew.","imageKeyword":"windy"},
{"word":"wheel","level":2,"definition":"a round part that rolls","example":"The wheel turned as the bike moved.","imageKeyword":"bike wheel"},
{"word":"yesterday","level":2,"definition":"the day before today","example":"Yesterday we painted a big mural.","imageKeyword":"calendar day"},
{"word":"admiral","level":2,"definition":"a top leader in the navy","example":"The admiral gave orders to all the ships in the fleet.","imageKeyword":"admiral navy"},
{"word":"album","level":2,"definition":"a book for holding photos","example":"We put our vacation photos in an album.","imageKeyword":"photo album"},
{"word":"alley","level":2,"definition":"a narrow path between buildings","example":"The cat ran down the alley to hide.","imageKeyword":"alley path"},
{"word":"amber","level":2,"definition":"a warm golden-yellow color","example":"The leaves turned a beautiful amber in the fall.","imageKeyword":"amber autumn leaves"},
{"word":"antenna","level":2,"definition":"a thin part on an insect's head used to feel things","example":"The butterfly moved its antenna to sense the flower.","imageKeyword":"insect antenna"},
{"word":"applause","level":2,"definition":"clapping hands to show you liked something","example":"The audience gave loud applause after the song.","imageKeyword":"applause clapping"},
{"word":"apricot","level":2,"definition":"a small orange fruit with soft skin","example":"She ate a ripe apricot for her snack.","imageKeyword":"apricot fruit"},
{"word":"arch","level":2,"definition":"a curved shape like the top of a door","example":"They walked under the stone arch to enter the garden.","imageKeyword":"stone arch"},
{"word":"atlas","level":2,"definition":"a book of maps","example":"We used an atlas to find where France is.","imageKeyword":"atlas maps"},
{"word":"avalanche","level":2,"definition":"a big slide of snow down a mountain","example":"The loud noise caused an avalanche on the mountain.","imageKeyword":"avalanche snow"},
{"word":"badge","level":2,"definition":"a small pin or tag that shows who you are","example":"The police officer wore a shiny badge.","imageKeyword":"badge pin"},
{"word":"bagpipe","level":2,"definition":"something you blow into to make music, with pipes and a bag","example":"The man played the bagpipe at the parade.","imageKeyword":"bagpipe instrument"},
{"word":"balcony","level":2,"definition":"a small platform on the outside of a building","example":"She waved from the balcony above the street.","imageKeyword":"balcony building"},
{"word":"banjo","level":2,"definition":"a round thing with strings that you pluck to make music","example":"He played a happy tune on the banjo.","imageKeyword":"banjo instrument"},
{"word":"banner","level":2,"definition":"a long piece of cloth with words or pictures","example":"They hung a welcome banner over the door.","imageKeyword":"banner sign"},
{"word":"basin","level":2,"definition":"a wide bowl used to hold water","example":"She filled the basin with warm water to wash her hands.","imageKeyword":"water basin"},
{"word":"bay","level":2,"definition":"a part of the sea that curves into the land","example":"The boats floated calmly in the bay.","imageKeyword":"bay water"},
{"word":"beacon","level":2,"definition":"a bright light that guides people","example":"The lighthouse beacon helped ships find land.","imageKeyword":"lighthouse beacon"},
{"word":"bead","level":2,"definition":"a small round piece used to make jewelry","example":"He strung a bead onto the necklace.","imageKeyword":"bead jewelry"},
{"word":"beeswax","level":2,"definition":"wax made by bees to build their hive","example":"Candles can be made from beeswax.","imageKeyword":"beeswax candle"},
{"word":"bellows","level":2,"definition":"a tool that blows air to make a fire bigger","example":"He used the bellows to fan the flames.","imageKeyword":"bellows fire"},
{"word":"binoculars","level":2,"definition":"a tool you look through to see far away","example":"She used binoculars to watch the birds.","imageKeyword":"binoculars"},
{"word":"birch","level":2,"definition":"a tree with white bark","example":"The birch tree had smooth white bark.","imageKeyword":"birch tree"},
{"word":"biscuit","level":2,"definition":"a small, soft bread roll","example":"He ate a warm biscuit with butter.","imageKeyword":"biscuit bread"},
{"word":"blacksmith","level":2,"definition":"a person who makes things from metal","example":"The blacksmith hammered the hot iron.","imageKeyword":"blacksmith forge"},
{"word":"blaze","level":2,"definition":"a big bright fire","example":"The blaze lit up the dark forest.","imageKeyword":"blaze fire"},
{"word":"blueprint","level":2,"definition":"a plan or drawing for building something","example":"The builder followed the blueprint to make the house.","imageKeyword":"blueprint plan"},
{"word":"bluff","level":2,"definition":"a high steep cliff near water","example":"They stood on the bluff and looked at the river below.","imageKeyword":"cliff bluff"},
{"word":"bobsled","level":2,"definition":"a sled that races down an icy track","example":"The team raced the bobsled down the hill.","imageKeyword":"bobsled race"},
{"word":"bolt","level":2,"definition":"a metal pin used to hold things together","example":"He tightened the bolt with a wrench.","imageKeyword":"bolt and nut hardware"},
{"word":"bonfire","level":2,"definition":"a large fire built outside","example":"We roasted marshmallows around the bonfire at camp.","imageKeyword":"bonfire outdoors"},
{"word":"bookshelf","level":2,"definition":"a shelf where books are kept","example":"She put her new book on the bookshelf.","imageKeyword":"bookshelf"},
{"word":"bracelet","level":2,"definition":"a band of jewelry worn on the wrist","example":"She wore a silver bracelet on her wrist.","imageKeyword":"bracelet jewelry"},
{"word":"bramble","level":2,"definition":"a prickly bush with berries","example":"The bramble scratched his arm as he picked berries.","imageKeyword":"bramble bush"},
{"word":"brass","level":2,"definition":"a shiny yellow metal","example":"The brass doorknob gleamed in the light.","imageKeyword":"brass metal"},
{"word":"bridle","level":2,"definition":"straps put on a horse's head to control it","example":"He placed the bridle on the horse before riding.","imageKeyword":"bridle horse"},
{"word":"broth","level":2,"definition":"a thin soup made by cooking meat or vegetables","example":"Mom made chicken broth when I was sick.","imageKeyword":"broth soup"},
{"word":"bugle","level":2,"definition":"a small brass horn used in the army","example":"The soldier played the bugle at sunrise.","imageKeyword":"bugle horn"},
{"word":"bulb","level":2,"definition":"a round part of a plant that grows underground","example":"She planted a tulip bulb in the garden.","imageKeyword":"tulip bulb"},
{"word":"bulletin","level":2,"definition":"a short news report or notice","example":"The teacher posted a bulletin on the board.","imageKeyword":"bulletin board"},
{"word":"bunker","level":2,"definition":"a strong shelter built underground","example":"We hid in the bunker when the heavy storm came.","imageKeyword":"bunker shelter"},
{"word":"buoy","level":2,"definition":"a floating marker in the water","example":"The red buoy showed where the boats should stop.","imageKeyword":"buoy water"},
{"word":"canal","level":2,"definition":"a waterway dug for boats or watering land","example":"The boat traveled slowly along the canal.","imageKeyword":"canal waterway"},
{"word":"canopy","level":2,"definition":"a cover or roof made of cloth or leaves","example":"The forest canopy blocked the sunlight.","imageKeyword":"forest canopy"},
{"word":"caribou","level":2,"definition":"a large deer that lives in cold places","example":"The caribou walked across the cold snowy land.","imageKeyword":"caribou deer"},
{"word":"carousel","level":2,"definition":"a ride with horses that goes around in circles","example":"The children laughed on the carousel.","imageKeyword":"carousel ride"},
{"word":"cartwheel","level":2,"definition":"a move where you flip sideways on your hands","example":"She did a cartwheel across the grass.","imageKeyword":"cartwheel gymnastics"},
{"word":"cashew","level":2,"definition":"a curved nut that grows on a tree","example":"He snacked on a handful of cashew nuts.","imageKeyword":"cashew nut"},
{"word":"cedar","level":2,"definition":"a large tree with a nice smell","example":"The cedar tree made the yard smell fresh.","imageKeyword":"cedar tree"},
{"word":"cellar","level":2,"definition":"a room below the ground in a house","example":"We stored old boxes in the cellar.","imageKeyword":"cellar basement"},
{"word":"chapel","level":2,"definition":"a small place for prayer","example":"They got married in a little chapel.","imageKeyword":"chapel building"},
{"word":"chariot","level":2,"definition":"a two-wheeled cart pulled by horses","example":"The king rode a chariot pulled by two horses.","imageKeyword":"chariot horses"},
{"word":"chestnut","level":2,"definition":"a shiny brown nut that you can roast and eat","example":"We roasted chestnuts over the campfire.","imageKeyword":"chestnut nut"},
{"word":"chisel","level":2,"definition":"a sharp tool used to cut wood or stone","example":"The sculptor used a chisel to shape the statue.","imageKeyword":"chisel tool"},
{"word":"chord","level":2,"definition":"two or more musical notes played together","example":"He played a chord on the guitar.","imageKeyword":"guitar chord"},
{"word":"cider","level":2,"definition":"a drink made from apples","example":"We drank warm cider on a fall day.","imageKeyword":"apple cider"},
{"word":"clam","level":2,"definition":"a small sea animal with two shells","example":"We found a clam on the sandy beach.","imageKeyword":"clam shell"},
{"word":"cloak","level":2,"definition":"a loose coat worn over the shoulders","example":"The wizard wore a dark cloak.","imageKeyword":"cloak coat"},
{"word":"cobblestone","level":2,"definition":"a round stone used to make old roads","example":"They walked on the cobblestone street.","imageKeyword":"cobblestone road"},
{"word":"cocoon","level":2,"definition":"the wrap a caterpillar makes around itself before it becomes a moth","example":"The caterpillar spun a cocoon and later came out as a moth.","imageKeyword":"cocoon moth"},
{"word":"comet","level":2,"definition":"a bright ball of ice with a glowing tail that flies through space","example":"The comet lit up the night sky.","imageKeyword":"comet sky"},
{"word":"cork","level":2,"definition":"a soft light thing used to close bottles","example":"He pulled the cork out of the bottle.","imageKeyword":"cork bottle"},
{"word":"corral","level":2,"definition":"a fenced area for horses or cattle","example":"The cowboys led the horses into the corral.","imageKeyword":"corral fence"},
{"word":"cradle","level":2,"definition":"a small bed that rocks for a baby","example":"The baby slept in the cradle.","imageKeyword":"baby cradle"},
{"word":"crest","level":2,"definition":"the top of a hill or wave","example":"They reached the crest of the hill and saw the valley.","imageKeyword":"hill crest"},
{"word":"crumb","level":2,"definition":"a tiny piece of bread or cake","example":"She brushed the crumb off the table.","imageKeyword":"bread crumb"},
{"word":"cuff","level":2,"definition":"the end of a sleeve on a shirt","example":"He rolled up the cuff on his jacket.","imageKeyword":"shirt cuff"},
{"word":"cypress","level":2,"definition":"a tall thin evergreen tree","example":"The cypress trees lined the road.","imageKeyword":"cypress tree"},
{"word":"dagger","level":2,"definition":"a short pointed knife","example":"The old dagger was displayed in the museum.","imageKeyword":"museum dagger display"},
{"word":"dandelion","level":2,"definition":"a yellow flower that turns into fluffy white seeds","example":"She blew the dandelion seeds into the wind.","imageKeyword":"dandelion seeds"},
{"word":"deck","level":2,"definition":"a flat wooden floor outside a house","example":"We ate dinner on the deck in the backyard.","imageKeyword":"wooden deck"},
{"word":"delta","level":2,"definition":"land shaped like a triangle where a river meets the sea","example":"Many birds live in the river delta.","imageKeyword":"river delta"},
{"word":"dinghy","level":2,"definition":"a small boat","example":"They rowed the dinghy to the shore.","imageKeyword":"dinghy boat"},
{"word":"dome","level":2,"definition":"a round roof shaped like half a ball","example":"The dome of the building shone in the sun.","imageKeyword":"dome building"},
{"word":"donkey","level":2,"definition":"an animal like a small horse with long ears","example":"The donkey carried bags up the mountain path.","imageKeyword":"donkey animal"},
{"word":"doorbell","level":2,"definition":"a button that makes a sound at the door","example":"She pressed the doorbell and waited.","imageKeyword":"doorbell"},
{"word":"drawbridge","level":2,"definition":"a bridge that can be raised up","example":"The castle drawbridge was pulled up at night.","imageKeyword":"drawbridge castle"},
{"word":"drumstick","level":2,"definition":"a stick used to hit a drum","example":"He hit the drum with a drumstick.","imageKeyword":"drumstick for drum"},
{"word":"dune","level":2,"definition":"a hill of sand formed by wind","example":"They climbed the sand dune at the beach.","imageKeyword":"sand dune"},
{"word":"easel","level":2,"definition":"a stand that holds a painting","example":"The artist set the canvas on the easel.","imageKeyword":"easel painting"},
{"word":"elm","level":2,"definition":"a tall shade tree","example":"The elm tree gave shade in the park.","imageKeyword":"elm tree"},
{"word":"ember","level":2,"definition":"a small piece of glowing wood in a dying fire","example":"The ember glowed red in the fireplace.","imageKeyword":"ember fire"},
{"word":"emerald","level":2,"definition":"a bright green gemstone","example":"The ring had a beautiful emerald in it.","imageKeyword":"emerald gem"},
{"word":"falcon","level":2,"definition":"a fast bird that hunts other animals","example":"The falcon dove through the sky to catch its prey.","imageKeyword":"falcon bird"},
{"word":"fiddle","level":2,"definition":"a violin, mainly when playing folk music","example":"He played a lively tune on the fiddle.","imageKeyword":"fiddle violin"},
{"word":"fig","level":2,"definition":"a soft sweet fruit with tiny seeds inside","example":"He ate a fresh fig from the tree.","imageKeyword":"fig fruit"},
{"word":"fjord","level":2,"definition":"a long narrow strip of sea between tall rocks","example":"The boat sailed through the deep fjord.","imageKeyword":"fjord water"},
{"word":"flint","level":2,"definition":"a hard stone that makes sparks","example":"He struck the flint to start a fire.","imageKeyword":"flint stone"},
{"word":"forge","level":2,"definition":"a place where metal is heated and shaped","example":"The horseshoe was made in the hot forge.","imageKeyword":"forge blacksmith"},
{"word":"fresco","level":2,"definition":"a painting done on wet wall plaster","example":"The old church had a beautiful fresco on the ceiling.","imageKeyword":"fresco painting"},
{"word":"gale","level":2,"definition":"a very strong wind","example":"The gale blew the leaves off every tree.","imageKeyword":"gale wind"},
{"word":"galley","level":2,"definition":"a kitchen on a ship","example":"The cook worked in the ship's galley.","imageKeyword":"ship galley"},
{"word":"garnet","level":2,"definition":"a dark red gemstone","example":"Her necklace had a garnet that shone in the light.","imageKeyword":"garnet gem"},
{"word":"gazelle","level":2,"definition":"a fast, graceful animal that runs on open plains","example":"The gazelle leaped across the dry open land.","imageKeyword":"gazelle animal"},
{"word":"geyser","level":2,"definition":"a hot spring that shoots water into the air","example":"The geyser erupted and sprayed hot water.","imageKeyword":"geyser eruption"},
{"word":"gong","level":2,"definition":"a large metal disk that makes a deep sound when hit","example":"He struck the gong to start the show.","imageKeyword":"gong instrument"},
{"word":"granite","level":2,"definition":"a hard type of rock used in buildings","example":"The countertop was made of polished granite.","imageKeyword":"granite rock"},
{"word":"grapevine","level":2,"definition":"a climbing plant that grows grapes","example":"The grapevine covered the garden fence.","imageKeyword":"grapevine"},
{"word":"gravel","level":2,"definition":"small loose stones","example":"The path was covered with gravel.","imageKeyword":"gravel path"},
{"word":"griddle","level":2,"definition":"a flat pan used for cooking","example":"She cooked pancakes on the griddle.","imageKeyword":"griddle pancakes"},
{"word":"grove","level":2,"definition":"a small group of trees","example":"We walked through a grove of orange trees.","imageKeyword":"grove trees"},
{"word":"gutter","level":2,"definition":"a channel at the edge of a roof or road for water","example":"Rainwater flowed down the gutter.","imageKeyword":"rain gutter"},
{"word":"hammock","level":2,"definition":"a cloth bed that hangs between two posts","example":"He napped in the hammock under the trees.","imageKeyword":"hammock"},
{"word":"harp","level":2,"definition":"a tall thing with many strings that you pluck to make music","example":"The musician played a gentle tune on the harp.","imageKeyword":"harp instrument"},
{"word":"hazel","level":2,"definition":"a light brown-green color","example":"She has beautiful hazel eyes.","imageKeyword":"hazel eyes color"},
{"word":"hearth","level":2,"definition":"the floor of a fireplace","example":"The cat slept by the warm hearth.","imageKeyword":"hearth fireplace"},
{"word":"heron","level":2,"definition":"a tall bird with long legs that stands in water","example":"The heron waited by the pond to catch a fish.","imageKeyword":"heron bird"},
{"word":"hickory","level":2,"definition":"a tree with hard wood and edible nuts","example":"The hickory wood burned slowly in the fire.","imageKeyword":"hickory tree"},
{"word":"hilltop","level":2,"definition":"the very top of a hill","example":"You can see the whole town from the hilltop.","imageKeyword":"hilltop view"},
{"word":"holly","level":2,"definition":"a plant with shiny green leaves and red berries","example":"We hung holly on the door for the holiday.","imageKeyword":"holly berries"},
{"word":"honeycomb","level":2,"definition":"wax cells bees make to store honey","example":"The honeycomb was full of sweet golden honey.","imageKeyword":"honeycomb"},
{"word":"horseshoe","level":2,"definition":"a U-shaped metal piece nailed to a horse's hoof","example":"The blacksmith fitted a horseshoe on the horse.","imageKeyword":"horseshoe"},
{"word":"hourglass","level":2,"definition":"a glass timer with sand that flows through a narrow middle","example":"The hourglass showed five minutes had passed.","imageKeyword":"hourglass timer"},
{"word":"husk","level":2,"definition":"the dry outer cover of a seed or corn","example":"She peeled the husk off the ear of corn.","imageKeyword":"corn husk"},
{"word":"ibis","level":2,"definition":"a wading bird with a long curved bill","example":"The ibis poked its beak into the mud for food.","imageKeyword":"ibis bird"},
{"word":"igloo","level":2,"definition":"a dome-shaped house made of snow blocks","example":"The igloo kept the family warm inside.","imageKeyword":"igloo snow"},
{"word":"ivy","level":2,"definition":"a climbing plant with green leaves","example":"Ivy covered the old brick wall.","imageKeyword":"ivy wall"},
{"word":"jade","level":2,"definition":"a smooth green stone used in jewelry","example":"The necklace was carved from green jade.","imageKeyword":"jade stone"},
{"word":"javelin","level":2,"definition":"a long, light spear you throw in a sport","example":"He threw the javelin far across the field.","imageKeyword":"javelin throw"},
{"word":"kelp","level":2,"definition":"large seaweed that grows in the ocean","example":"The kelp swayed gently in the water.","imageKeyword":"kelp seaweed"},
{"word":"kennel","level":2,"definition":"a small shelter for a dog","example":"The puppy slept in its warm kennel.","imageKeyword":"dog kennel"},
{"word":"kindle","level":2,"definition":"to start a fire","example":"He used sticks to kindle a small campfire.","imageKeyword":"lighting campfire with sticks"},
{"word":"kingfisher","level":2,"definition":"a brightly colored bird that dives for fish","example":"The kingfisher dove into the stream and caught a fish.","imageKeyword":"kingfisher bird"},
{"word":"knapsack","level":2,"definition":"a bag carried on the back","example":"She packed her lunch in her knapsack.","imageKeyword":"knapsack bag"},
{"word":"lagoon","level":2,"definition":"a shallow body of water near the sea","example":"The lagoon was clear and full of fish.","imageKeyword":"lagoon water"},
{"word":"latch","level":2,"definition":"a small bar that keeps a door closed","example":"She lifted the latch and opened the gate.","imageKeyword":"door latch"},
{"word":"lava","level":2,"definition":"hot melted rock from a volcano","example":"The lava flowed down the side of the volcano.","imageKeyword":"lava volcano"},
{"word":"levee","level":2,"definition":"a wall built to keep a river from flooding","example":"The levee held back the rising water.","imageKeyword":"levee river"},
{"word":"lichen","level":2,"definition":"a flat plant-like growth on rocks and trees","example":"Green lichen covered the old stone wall.","imageKeyword":"lichen rock"},
{"word":"locket","level":2,"definition":"a small case on a necklace that holds a picture","example":"She kept a photo of her mom in her locket.","imageKeyword":"locket necklace"},
{"word":"loom","level":2,"definition":"a machine used to weave cloth","example":"He made a scarf on the loom.","imageKeyword":"weaving loom"},
{"word":"lynx","level":2,"definition":"a wild cat with tufted ears","example":"The lynx crept through the snowy forest.","imageKeyword":"lynx cat"},
{"word":"mango","level":2,"definition":"a sweet tropical fruit with orange flesh","example":"She cut the mango into slices.","imageKeyword":"mango fruit"},
{"word":"mantle","level":2,"definition":"a shelf above a fireplace","example":"They put family photos on the mantle.","imageKeyword":"fireplace mantle"},
{"word":"maple","level":2,"definition":"a tree with wide leaves that turn red in fall","example":"The maple tree turned bright red in autumn.","imageKeyword":"maple tree"},
{"word":"marsh","level":2,"definition":"wet, soft land often near water","example":"Frogs lived in the marsh by the river.","imageKeyword":"marsh wetland"},
{"word":"mast","level":2,"definition":"a tall pole on a ship that holds the sails","example":"The flag flew from the top of the mast.","imageKeyword":"ship mast"},
{"word":"moat","level":2,"definition":"a deep ditch of water around a castle","example":"The castle had a moat to keep enemies out.","imageKeyword":"castle moat"},
{"word":"mortar","level":2,"definition":"a thick paste used to hold bricks or stones together","example":"The builder spread mortar between the bricks.","imageKeyword":"bricklayer mortar"},
{"word":"mosaic","level":2,"definition":"a picture made from small colored pieces","example":"The mosaic on the wall showed a dolphin.","imageKeyword":"mosaic art"},
{"word":"mulberry","level":2,"definition":"a small dark purple fruit that grows on a tree","example":"We picked mulberries from the tree in the yard.","imageKeyword":"mulberry fruit"},
{"word":"muzzle","level":2,"definition":"the nose and mouth area of an animal","example":"The dog's muzzle was wet from drinking water.","imageKeyword":"dog snout nose close up"},
{"word":"nectar","level":2,"definition":"sweet juice inside flowers that bees collect","example":"The bee gathered nectar from the rose.","imageKeyword":"bee nectar flower"},
{"word":"nettle","level":2,"definition":"a plant that stings when you touch it","example":"He got stung by a nettle on the trail.","imageKeyword":"nettle plant"},
{"word":"nozzle","level":2,"definition":"the tip of a hose where water comes out","example":"She pointed the nozzle at the garden.","imageKeyword":"hose nozzle"},
{"word":"nutmeg","level":2,"definition":"a spice from a tropical seed","example":"Dad sprinkled nutmeg on the warm pie.","imageKeyword":"nutmeg spice"},
{"word":"oar","level":2,"definition":"a long pole with a flat end used to row a boat","example":"He dipped the oar into the water and pulled.","imageKeyword":"oar rowing"},
{"word":"oasis","level":2,"definition":"a green area with water in a desert","example":"They rested at the oasis in the hot desert.","imageKeyword":"oasis desert"},
{"word":"olive","level":2,"definition":"a small oval fruit used to make oil","example":"She put an olive on top of the pizza.","imageKeyword":"olive fruit"},
{"word":"ore","level":2,"definition":"rock that has metal inside","example":"The miners dug ore from deep underground.","imageKeyword":"ore rock"},
{"word":"otter","level":2,"definition":"a playful animal that swims in rivers","example":"The otter floated on its back in the stream.","imageKeyword":"otter animal"},
{"word":"pagoda","level":2,"definition":"a tower with many roofs found in Asia","example":"The pagoda had five levels with curved roofs.","imageKeyword":"pagoda tower"},
{"word":"parchment","level":2,"definition":"old paper made from animal skin","example":"The treasure map was drawn on parchment.","imageKeyword":"parchment scroll"},
{"word":"parsley","level":2,"definition":"a green herb used to flavor food","example":"She added parsley to the soup.","imageKeyword":"parsley herb"},
{"word":"pasture","level":2,"definition":"a field where animals eat grass","example":"The cows grazed in the green pasture.","imageKeyword":"pasture cows"},
{"word":"pebble","level":2,"definition":"a small smooth stone","example":"She skipped a pebble across the lake.","imageKeyword":"pebble stone"},
{"word":"pelican","level":2,"definition":"a large bird with a big pouch under its beak","example":"The pelican scooped fish into its beak.","imageKeyword":"pelican bird"},
{"word":"pendant","level":2,"definition":"a piece of jewelry that hangs from a chain","example":"He wore a gold pendant around his neck.","imageKeyword":"pendant necklace"},
{"word":"pier","level":2,"definition":"a platform that sticks out over water","example":"We walked along the pier and watched the waves.","imageKeyword":"pier ocean"},
{"word":"pigment","level":2,"definition":"a powder that gives color to paint","example":"The artist mixed red pigment into the paint.","imageKeyword":"pigment paint"},
{"word":"carefully","level":2,"definition":"with great care so you do not make mistakes","example":"He carefully carried the glass of water without spilling.","imageKeyword":"hands carefully stacking blocks"},
{"word":"accept","level":2,"definition":"to say yes to something offered","example":"She accepted the gift with a big smile.","imageKeyword":"two kids trading cards shaking hands"},
{"word":"quite","level":2,"definition":"more than a little but not completely","example":"The math puzzle was quite hard, but I figured it out after three tries.","imageKeyword":"kid thinking hard at math puzzle"},
{"word":"rise","level":2,"definition":"to go up or get higher","example":"We watched the sun rise higher and higher in the sky.","imageKeyword":"sunrise"},{"word":"although","level":2,"definition":"even though","example":"Although it was cold, he did not wear a jacket.","imageKeyword":"cold without jacket"},{"word":"unless","level":2,"definition":"except if; if not","example":"You can't go outside unless you finish your food.","imageKeyword":"child eating dinner before going outside"},{"word":"seldom","level":2,"definition":"not often; rarely","example":"Snow seldom falls in this warm town.","imageKeyword":"empty playground few people"},{"word":"eventually","level":2,"definition":"in the end, after a long time or much effort","example":"If you keep trying, you will eventually learn to ride a bike.","imageKeyword":"seed growing into flower stages"}];
