const LEVEL5D_BANK=[{"word":"accusatory","level":5,"definition":"showing that you think someone did something wrong","example":"Her accusatory tone made him feel guilty even though he was not at fault.","imageKeyword":"pointing finger"},
{"word":"acidity","level":5,"definition":"the level of acid in something","example":"The acidity of lemon juice makes it taste sour.","imageKeyword":"lemon acid"},
{"word":"acquaintance","level":5,"definition":"a person you know slightly but who is not a close friend","example":"She is an acquaintance from school, not someone I hang out with regularly.","imageKeyword":"casual greeting"},
{"word":"adjoining","level":5,"definition":"next to or joined with something","example":"The adjoining rooms shared a door between them.","imageKeyword":"connected rooms"},
{"word":"adornment","level":5,"definition":"a decorative item added for beauty","example":"The gold necklace was her favorite adornment for special occasions.","imageKeyword":"jewelry decoration"},
{"word":"affirmation","level":5,"definition":"a statement that something is true or a sign of support","example":"His nod was an affirmation that he agreed with the plan.","imageKeyword":"positive words mirror"},
{"word":"amnesty","level":5,"definition":"an official pardon for people who have broken the law","example":"The government granted amnesty to the prisoners of war.","imageKeyword":"pardon freedom"},
{"word":"animated","level":5,"definition":"full of life and energy, or made to appear to move","example":"He gave an animated description of his trip adventures.","imageKeyword":"lively person"},
{"word":"antagonist","level":5,"definition":"a person who opposes or fights against the main character","example":"The villain is the antagonist in most superhero stories.","imageKeyword":"villain character"},
{"word":"ardent","level":5,"definition":"showing very strong feelings or enthusiasm","example":"She was an ardent supporter of the school basketball team.","imageKeyword":"passionate fan"},
{"word":"aristocracy","level":5,"definition":"the highest social class, often with special privileges","example":"In old England, the aristocracy lived in grand estates.","imageKeyword":"noble palace"},
{"word":"articulation","level":5,"definition":"the clear speaking of words or the expression of thoughts","example":"Her articulation was so clear that everyone understood her speech.","imageKeyword":"clear speaking"},
{"word":"aspirant","level":5,"definition":"a person who hopes to achieve something","example":"Every aspirant for the team practiced extra hours after school.","imageKeyword":"goal reaching"},
{"word":"assertion","level":5,"definition":"a confident statement that something is true","example":"His assertion that the project would succeed turned out to be correct.","imageKeyword":"confident statement"},
{"word":"astute","level":5,"definition":"very good at grasping situations quickly","example":"The astute detective noticed the small detail everyone else missed.","imageKeyword":"sharp observer"},
{"word":"atrophy","level":5,"definition":"to become weaker because of not being used","example":"Muscles will atrophy if you don't exercise them regularly.","imageKeyword":"weak muscle"},
{"word":"audacity","level":5,"definition":"bold or daring behavior that might seem rude","example":"He had the audacity to ask the principal to cancel homework.","imageKeyword":"bold person"},
{"word":"auspicious","level":5,"definition":"showing signs that something will be successful","example":"A sunny morning seemed like an auspicious start to field day.","imageKeyword":"lucky sunrise"},
{"word":"authoritarian","level":5,"definition":"demanding that people obey rules fully without question","example":"The authoritarian ruler did not allow anyone to disagree.","imageKeyword":"strict ruler"},
{"word":"autonomy","level":5,"definition":"the right to govern yourself or make your own decisions","example":"Teenagers often want more autonomy from their parents.","imageKeyword":"independence freedom"},
{"word":"avarice","level":5,"definition":"an extreme desire for wealth or money","example":"The king's avarice led him to raise taxes on the poorest people.","imageKeyword":"greedy gold"},
{"word":"avid","level":5,"definition":"very eager and keen","example":"He is an avid reader who finishes three books every week.","imageKeyword":"eager reader"},
{"word":"axiom","level":5,"definition":"a statement accepted as true without proof","example":"It is an axiom in math that a whole is greater than any of its parts.","imageKeyword":"math truth"},
{"word":"belligerent","level":5,"definition":"hostile and ready to fight","example":"The belligerent bully was always picking arguments with classmates.","imageKeyword":"aggressive stance"},
{"word":"benevolence","level":5,"definition":"the quality of being kind and wanting to help others","example":"The benevolence of the donors helped build a new playground.","imageKeyword":"generous giving"},
{"word":"bewilder","level":5,"definition":"to confuse someone so much they do not know what to do","example":"The magic trick bewildered the entire crowd.","imageKeyword":"confused amazed"},
{"word":"blight","level":5,"definition":"a disease that damages plants or something that spoils things","example":"A blight destroyed most of the potato crop that year.","imageKeyword":"diseased plant"},
{"word":"bombard","level":5,"definition":"to attack with many things at once or ask many questions","example":"Reporters bombarded the mayor with questions about the new park.","imageKeyword":"many questions"},
{"word":"bounty","level":5,"definition":"a large amount of something, or a reward offered","example":"The autumn harvest brought a bounty of fruits and vegetables.","imageKeyword":"harvest abundance"},
{"word":"capitalize","level":5,"definition":"to use something to your advantage or to write in capital letters","example":"The team tried to capitalize on their early lead in the game.","imageKeyword":"opportunity seize"},
{"word":"capricious","level":5,"definition":"changing mood or behavior suddenly without reason","example":"The capricious weather went from sunny to stormy in minutes.","imageKeyword":"changing weather"},
{"word":"captivating","level":5,"definition":"very interesting and attractive","example":"The captivating story kept me reading until midnight.","imageKeyword":"enchanted reader"},
{"word":"catastrophic","level":5,"definition":"causing sudden great damage or suffering","example":"The catastrophic earthquake destroyed hundreds of buildings.","imageKeyword":"earthquake damage"},
{"word":"caustic","level":5,"definition":"able to burn or damage by chemical action, or very critical","example":"The caustic cleaning chemical came with a safety warning.","imageKeyword":"chemical warning"},
{"word":"cessation","level":5,"definition":"the stopping or ending of something","example":"The cessation of rain brought people back outside.","imageKeyword":"rain stopping"},
{"word":"chronological","level":5,"definition":"arranged in the order that things happened in time","example":"The biography tells the story in chronological order from earliest to latest events.","imageKeyword":"timeline order"},
{"word":"circumscribe","level":5,"definition":"to draw a line around or to limit something","example":"The rules circumscribe what students can do during lunch break.","imageKeyword":"circle boundary"},
{"word":"clamber","level":5,"definition":"to climb with difficulty using both hands and feet","example":"The children clambered over the rocky hillside to reach the top.","imageKeyword":"climbing rocks"},
{"word":"clandestine","level":5,"definition":"done secretly or kept hidden","example":"The spies held a clandestine meeting in the back of the bookstore.","imageKeyword":"secret meeting"},
{"word":"coalesce","level":5,"definition":"to come together and form one group or thing","example":"Several small streams coalesce into a river at the bottom of the valley.","imageKeyword":"streams merging"},
{"word":"cogent","level":5,"definition":"clear, logical, and convincing","example":"She made a cogent argument for why recess should be longer.","imageKeyword":"logical argument"},
{"word":"cognition","level":5,"definition":"the mental process of gaining knowledge through thinking","example":"Reading puzzles helps improve cognition and problem-solving skills.","imageKeyword":"glowing brain with gears"},
{"word":"coherence","level":5,"definition":"the quality of being logical and consistent","example":"The essay lacked coherence; the thoughts jumped around randomly.","imageKeyword":"connected puzzle"},
{"word":"commemoration","level":5,"definition":"something done to recall an important person or event","example":"The statue was built in commemoration of the town's founder.","imageKeyword":"memorial statue"},
{"word":"commencement","level":5,"definition":"the start of something or a graduation ceremony","example":"The commencement of the school year always feels exciting.","imageKeyword":"graduation ceremony"},
{"word":"compendium","level":5,"definition":"a collection of detailed facts on a subject","example":"The nature compendium had facts about every bird species in the state.","imageKeyword":"reference book"},
{"word":"complacency","level":5,"definition":"a feeling of satisfaction that stops you from trying harder","example":"Complacency after winning the first game led to losing the second.","imageKeyword":"sleeping on the job"},
{"word":"complementary","level":5,"definition":"combining well with something to make it better or complete","example":"The blue and orange decorations were complementary colors.","imageKeyword":"color wheel"},
{"word":"compliance","level":5,"definition":"doing what you are asked or ordered to do","example":"The school expects compliance with safety rules at all times.","imageKeyword":"following rules"},
{"word":"concession","level":5,"definition":"something you agree to give up in order to end a disagreement","example":"Both sides made concessions to reach a fair agreement.","imageKeyword":"compromise handshake"},
{"word":"concord","level":5,"definition":"a state of agreement and harmony","example":"The two rival teams reached concord and agreed to share the field.","imageKeyword":"harmony peace"},
{"word":"condemnation","level":5,"definition":"strong disapproval or declaring something is wrong","example":"The condemnation of bullying was clear in the principal's speech.","imageKeyword":"disapproval sign"},
{"word":"condescending","level":5,"definition":"acting as if you are better or smarter than other people","example":"His condescending tone made his classmates feel insulted.","imageKeyword":"looking down"},
{"word":"confluence","level":5,"definition":"a place where two rivers meet or where things come together","example":"The town was built at the confluence of two major rivers.","imageKeyword":"rivers meeting"},
{"word":"conjecture","level":5,"definition":"a guess or opinion based on incomplete facts","example":"Without proof, his theory remained just a conjecture.","imageKeyword":"guessing thinking"},
{"word":"conscription","level":5,"definition":"needing people by law to serve in the military","example":"During the war, conscription meant every young man had to join the army.","imageKeyword":"military draft"},
{"word":"consecrate","level":5,"definition":"to officially make something holy or dedicate it to a purpose","example":"The town gathered to consecrate the new memorial garden.","imageKeyword":"sacred ceremony"},
{"word":"consequential","level":5,"definition":"important or having big results","example":"The judge's consequential decision changed the law for everyone.","imageKeyword":"important decision"},
{"word":"conservatory","level":5,"definition":"a glass building where plants are grown or a school for music","example":"The conservatory was filled with tropical plants and flowers.","imageKeyword":"greenhouse plants"},
{"word":"consolidation","level":5,"definition":"combining things into a single more effective whole","example":"The consolidation of three small schools into one larger school saved money.","imageKeyword":"companies joining one"},
{"word":"constituency","level":5,"definition":"a group of voters in a particular district","example":"The politician visited his constituency to listen to their concerns.","imageKeyword":"voting citizens"},
{"word":"constitutional","level":5,"definition":"about a country's most important rules and laws","example":"Freedom of speech is a constitutional right in the United States.","imageKeyword":"constitution document"},
{"word":"consultation","level":5,"definition":"a meeting to discuss something or get advice","example":"The doctor scheduled a consultation to discuss the test results.","imageKeyword":"meeting advice"},
{"word":"consummate","level":5,"definition":"very skilled or perfect in every way","example":"She was a consummate performer who never made a mistake on stage.","imageKeyword":"perfect performance"},
{"word":"contagious","level":5,"definition":"able to spread from one person to another","example":"The flu is contagious, so stay home if you feel sick.","imageKeyword":"spreading germs"},
{"word":"contemplation","level":5,"definition":"deep or careful thought about something","example":"After much contemplation, she chose which college to attend.","imageKeyword":"person meditating thinking"},
{"word":"continuity","level":5,"definition":"the state of going on without interruption","example":"The continuity of the TV series was broken when they changed actors.","imageKeyword":"unbroken chain"},
{"word":"contradiction","level":5,"definition":"a situation where two things cannot both be true","example":"Saying you love animals but mistreating them is a contradiction.","imageKeyword":"opposite signs"},
{"word":"copious","level":5,"definition":"large in quantity or amount","example":"She took copious notes during the lecture to study later.","imageKeyword":"many notes"},
{"word":"cordial","level":5,"definition":"warm and friendly","example":"The host gave us a cordial welcome when we arrived at the party.","imageKeyword":"friendly greeting"},
{"word":"corroborate","level":5,"definition":"to confirm or support something with proof","example":"The witness was able to corroborate the story told by the victim.","imageKeyword":"confirming evidence"},
{"word":"creed","level":5,"definition":"a set of beliefs or principles that guide a person's life","example":"Their family creed was to always help neighbors in need.","imageKeyword":"guiding principles"},
{"word":"culpable","level":5,"definition":"deserving blame for something wrong","example":"The student who started the food fight was culpable for the mess.","imageKeyword":"blame responsibility"},
{"word":"cynical","level":5,"definition":"believing that people act only for selfish reasons","example":"He was cynical about the new rule, thinking it only helped teachers.","imageKeyword":"doubtful person"},
{"word":"daunting","level":5,"definition":"seeming difficult and scary to deal with","example":"Climbing the tall mountain was a daunting challenge for the hikers.","imageKeyword":"scary challenging obstacle"},
{"word":"decorum","level":5,"definition":"polite and proper behavior in a formal setting","example":"Students were reminded to show decorum during the assembly.","imageKeyword":"formal behavior"},
{"word":"defunct","level":5,"definition":"no longer existing or working","example":"The defunct factory had been closed for over ten years.","imageKeyword":"abandoned factory"},
{"word":"delineate","level":5,"definition":"to describe or draw something in careful detail","example":"The map delineated the borders between the three countries.","imageKeyword":"drawing borders"},
{"word":"demeanor","level":5,"definition":"the way a person looks and behaves","example":"His calm demeanor made everyone feel less nervous.","imageKeyword":"calm posture"},
{"word":"depiction","level":5,"definition":"a drawing, painting, or description of something","example":"The book included a detailed depiction of life in ancient Rome.","imageKeyword":"painting scene"},
{"word":"depletion","level":5,"definition":"the reduction or using up of a resource","example":"The depletion of fish in the lake worried local fishermen.","imageKeyword":"empty resource"},
{"word":"deportation","level":5,"definition":"forcing someone to leave a country","example":"The history lesson covered the deportation of people during the war.","imageKeyword":"exile leaving"},
{"word":"deprivation","level":5,"definition":"the state of not having something that is needed","example":"Sleep deprivation makes it hard to concentrate in school.","imageKeyword":"tired exhausted"},
{"word":"derogatory","level":5,"definition":"showing disrespect or a low view of someone","example":"Making derogatory comments about others is never acceptable.","imageKeyword":"mean words"},
{"word":"deterrent","level":5,"definition":"something that prevents people from doing something","example":"The alarm system acted as a deterrent against burglars.","imageKeyword":"warning alarm"},
{"word":"dexterity","level":5,"definition":"skill and ease in using your hands or body","example":"The surgeon needed great dexterity to perform the delicate operation.","imageKeyword":"skilled hands"},
{"word":"dichotomy","level":5,"definition":"a division into two completely different things","example":"There is a dichotomy between what he says and what he does.","imageKeyword":"split two"},
{"word":"dilapidated","level":5,"definition":"old and in very bad condition","example":"The dilapidated house had broken windows, and a sagging roof.","imageKeyword":"ruined house"},
{"word":"diligence","level":5,"definition":"careful and steady effort over time","example":"Through diligence and hard work, he improved his grades significantly.","imageKeyword":"hard work"},
{"word":"diminutive","level":5,"definition":"extremely small or tiny","example":"The diminutive hummingbird was barely bigger than my thumb.","imageKeyword":"tiny bird"},
{"word":"disclaimer","level":5,"definition":"a statement saying you are not responsible for something","example":"The product had a disclaimer warning that results may vary.","imageKeyword":"warning label"},
{"word":"discrepancy","level":5,"definition":"a difference between two things that should be the same","example":"There was a discrepancy between the two reports about what happened.","imageKeyword":"mismatch difference"},
{"word":"dismantle","level":5,"definition":"to take something apart piece by piece","example":"The workers dismantled the old playground to build a new one.","imageKeyword":"taking apart"},
{"word":"disparity","level":5,"definition":"a big difference or inequality between things","example":"The disparity in scores between the two teams was huge.","imageKeyword":"unequal balance"},
{"word":"dissolution","level":5,"definition":"the breaking up or ending of something","example":"The dissolution of the band upset their many fans.","imageKeyword":"breaking apart"},
{"word":"echelon","level":5,"definition":"a level or rank in a group","example":"Only the top echelon of the firm knew about the secret project.","imageKeyword":"hierarchy levels"},
{"word":"edifice","level":5,"definition":"a large and impressive building","example":"The stone edifice of the courthouse dominated the town square.","imageKeyword":"grand building"},
{"word":"egalitarian","level":5,"definition":"believing that all people should have equal rights","example":"The egalitarian society gave all an equal voice in decisions.","imageKeyword":"equal people"},
{"word":"elicit","level":5,"definition":"to draw out a response or information from someone","example":"The funny video elicited laughter from the whole class.","imageKeyword":"causing laughter"},
{"word":"emblem","level":5,"definition":"a symbol or design that stands for something","example":"The eagle is an emblem of the United States.","imageKeyword":"national symbol"},
{"word":"eradicate","level":5,"definition":"to completely destroy or get rid of something","example":"Scientists worked hard to eradicate the disease from the region.","imageKeyword":"eliminating germs"},
{"word":"esteem","level":5,"definition":"respect and admiration for someone","example":"The town held the volunteer firefighters in high esteem.","imageKeyword":"respect admiration"},
{"word":"ethical","level":5,"definition":"about what is right and wrong in how people act","example":"Returning lost money is the ethical thing to do.","imageKeyword":"angel devil on shoulders"},
{"word":"etiquette","level":5,"definition":"the rules of polite behavior in society","example":"Table etiquette includes not talking with your mouth full.","imageKeyword":"polite manners"},
{"word":"eulogy","level":5,"definition":"a speech praising someone who has recently died","example":"The family friend delivered a touching eulogy at the memorial.","imageKeyword":"memorial speech"},
{"word":"excise","level":5,"definition":"to cut something out or remove it","example":"The editor excised the boring paragraphs from the article.","imageKeyword":"cutting scissors"},
{"word":"exclamation","level":5,"definition":"a sudden cry or remark expressing surprise or what you feel","example":"\"Wow!\" is an exclamation that shows surprise or amazement.","imageKeyword":"surprised shout"},
{"word":"exemplary","level":5,"definition":"serving as a perfect example for others to follow","example":"Her exemplary behavior earned her the good citizenship award.","imageKeyword":"gold star"},
{"word":"exemption","level":5,"definition":"being free from a rule or duty that others must follow","example":"Students with allergies got an exemption from the peanut snack rule.","imageKeyword":"exception pass"},
{"word":"exodus","level":5,"definition":"a mass departure of people from a place","example":"There was an exodus from the city when the hurricane warning came.","imageKeyword":"crowd leaving"},
{"word":"expedient","level":5,"definition":"helpful or useful for a specific purpose, even if not fully fair","example":"Taking a shortcut seemed expedient but turned out to be longer.","imageKeyword":"shortcut path"},
{"word":"exploitation","level":5,"definition":"treating someone not fairly to benefit from their work","example":"The exploitation of workers who were paid unfairly led to new labor laws.","imageKeyword":"unfair labor"},
{"word":"exquisite","level":5,"definition":"very lovely and delicate","example":"The exquisite painting showed every tiny detail of the flower.","imageKeyword":"beautiful painting"},
{"word":"fallacy","level":5,"definition":"a false thought or a mistake in reasoning","example":"It is a fallacy that goldfish only have a three-second memory.","imageKeyword":"wrong idea"},
{"word":"feasibility","level":5,"definition":"if something is possible and practical to do","example":"The team studied the feasibility of building a treehouse in the schoolyard.","imageKeyword":"planning possible"},
{"word":"fervent","level":5,"definition":"having very strong feelings about something","example":"The fans gave a fervent cheer when their team scored.","imageKeyword":"passionate cheering"},
{"word":"flagrant","level":5,"definition":"shockingly bad and obvious","example":"Copying someone's homework is a flagrant violation of school rules.","imageKeyword":"obvious cheating"},
{"word":"fledgling","level":5,"definition":"a young bird learning to fly; also something new and inexperienced","example":"The fledgling company was just starting to find its first customers.","imageKeyword":"baby bird"},
{"word":"forbearance","level":5,"definition":"patient self-control and tolerance","example":"She showed forbearance by not getting angry at her little brother's mess.","imageKeyword":"patience calm"},
{"word":"forgo","level":5,"definition":"to decide not to have or do something","example":"He decided to forgo dessert, so he could save room for the main course.","imageKeyword":"saying no"},
{"word":"frivolous","level":5,"definition":"not important or serious; silly","example":"Buying toys with lunch money seemed like a frivolous decision.","imageKeyword":"silly spending"},
{"word":"gentry","level":5,"definition":"people of high social class just below the nobility","example":"The local gentry owned large farms throughout the countryside.","imageKeyword":"wealthy landowners"},
{"word":"gluttony","level":5,"definition":"eating or consuming far more than you need","example":"Eating an entire cake by yourself is an act of gluttony.","imageKeyword":"overeating feast"},
{"word":"harmonious","level":5,"definition":"working well together without conflict","example":"The harmonious bond between the two classes made the project fun.","imageKeyword":"harmony together"},
{"word":"hypocrisy","level":5,"definition":"pretending to believe something or behave in a way that you do not","example":"It is hypocrisy to tell others to be kind while being mean yourself.","imageKeyword":"two faces"},
{"word":"immunity","level":5,"definition":"a shield from disease or being free from a duty","example":"The vaccine gives immunity against the flu virus.","imageKeyword":"shield protection"},
{"word":"impasse","level":5,"definition":"a situation where no progress can be made","example":"The negotiation reached an impasse when neither side would compromise.","imageKeyword":"blocked road"},
{"word":"impeachment","level":5,"definition":"the process of charging a state official with wrongdoing","example":"The impeachment proceedings were broadcast on television.","imageKeyword":"court trial"},
{"word":"impromptu","level":5,"definition":"done without planning or getting ready","example":"The teacher gave an impromptu quiz that surprised everyone.","imageKeyword":"surprise test"},
{"word":"impunity","level":5,"definition":"freedom from punishment for doing something wrong","example":"The bully acted with impunity because no one reported his behavior.","imageKeyword":"no consequences"},
{"word":"inadvertent","level":5,"definition":"not done on purpose; accidental","example":"The inadvertent mistake on the form caused a week-long delay.","imageKeyword":"accidental spill"},
{"word":"inception","level":5,"definition":"the beginning or start of something","example":"Since its inception, the club has grown from five to fifty members.","imageKeyword":"starting point"},
{"word":"inclination","level":5,"definition":"a tendency or desire to do something","example":"His inclination toward science led him to join the robotics club.","imageKeyword":"leaning toward"},
{"word":"indictment","level":5,"definition":"a formal charge of a serious crime","example":"The grand jury issued an indictment against the accused person.","imageKeyword":"court charge"},
{"word":"indignation","level":5,"definition":"anger caused by something that seems unfair","example":"The unfair rule filled the students with indignation.","imageKeyword":"angry protest"},
{"word":"inertia","level":5,"definition":"the tendency of something to resist change in motion","example":"A ball at rest stays at rest because of inertia until a force moves it.","imageKeyword":"still object"},
{"word":"infallible","level":5,"definition":"never making mistakes or failing","example":"No human is infallible—everyone makes mistakes sometimes.","imageKeyword":"perfect record"},
{"word":"inference","level":5,"definition":"a conclusion reached based on proof and reasoning","example":"Based on the wet ground, her inference was that it had rained overnight.","imageKeyword":"clue deduction"},
{"word":"infringement","level":5,"definition":"breaking a rule or law, or violating someone's rights","example":"Copying a book without permission is an infringement of copyright.","imageKeyword":"rule violation"},
{"word":"inquisitive","level":5,"definition":"eager to learn and asking lots of questions","example":"The inquisitive child asked why the sky was blue.","imageKeyword":"curious child"},
{"word":"insatiable","level":5,"definition":"impossible to satisfy because you always want more","example":"His insatiable appetite for books meant he read one every two days.","imageKeyword":"endless hunger"},
{"word":"insolvency","level":5,"definition":"the state of not having enough money to pay debts","example":"The company's insolvency meant it could not pay its workers.","imageKeyword":"empty wallet"},
{"word":"integration","level":5,"definition":"combining things so they work as a unified whole","example":"The integration of art and science made the lesson more engaging.","imageKeyword":"combining subjects"},
{"word":"intervention","level":5,"definition":"stepping in to stop or change what is happening","example":"The teacher's intervention stopped the argument from getting worse.","imageKeyword":"doctor helping patient"},
{"word":"intimidation","level":5,"definition":"frightening someone to make them do what you want","example":"Bullying through intimidation is never acceptable behavior.","imageKeyword":"threatening stance"},
{"word":"itinerary","level":5,"definition":"a planned route or schedule for a trip","example":"Our itinerary included stops in three different cities over five days.","imageKeyword":"travel plan"},
{"word":"jubilee","level":5,"definition":"a special celebration for an important anniversary","example":"The school held a jubilee to mark its fiftieth year.","imageKeyword":"anniversary celebration"},
{"word":"jurisprudence","level":5,"definition":"the study and theory of law","example":"The professor taught jurisprudence at the law school.","imageKeyword":"law books"},
{"word":"lenient","level":5,"definition":"not strict in punishing or judging people","example":"The lenient teacher gave extra time for students to finish their work.","imageKeyword":"gentle teacher"},
{"word":"liberation","level":5,"definition":"setting prisoners or captives free","example":"The liberation of the prisoners was cheered across the country.","imageKeyword":"freedom celebration"},
{"word":"luminous","level":5,"definition":"producing or reflecting bright light","example":"The luminous full moon lit up the entire night sky.","imageKeyword":"bright moon"},
{"word":"malevolent","level":5,"definition":"wishing harm to others; evil","example":"The malevolent villain plotted to destroy the entire city.","imageKeyword":"evil villain"},
{"word":"manifesto","level":5,"definition":"a written statement of the beliefs and goals of a group","example":"The student council published a manifesto promising better lunch options.","imageKeyword":"declaration poster"},
{"word":"mediation","level":5,"definition":"helping two sides reach an agreement without going to court","example":"The school counselor provided mediation between the arguing students.","imageKeyword":"peace mediator"},
{"word":"mercenary","level":5,"definition":"a soldier who fights for money rather than for their own country","example":"The king hired mercenaries to fight in the war.","imageKeyword":"hired soldier"},
{"word":"meticulous","level":5,"definition":"giving great focus to every detail","example":"The meticulous artist spent hours perfecting each tiny stroke.","imageKeyword":"detailed work"},
{"word":"mitigate","level":5,"definition":"to make something bad less severe","example":"Wearing sunscreen helps mitigate the harmful effects of the sun.","imageKeyword":"reducing harm"},
{"word":"myriad","level":5,"definition":"a very large number of things","example":"A myriad of stars filled the clear night sky.","imageKeyword":"countless stars"},
{"word":"negligence","level":5,"definition":"failure to take proper care of something","example":"The accident was caused by negligence in maintaining the gear.","imageKeyword":"careless mistake"},
{"word":"nemesis","level":5,"definition":"a long-standing rival or enemy","example":"The two chess players had been each other's nemesis for years.","imageKeyword":"rival opponent"},
{"word":"nonchalant","level":5,"definition":"appearing calm and relaxed, not worried about anything","example":"She acted nonchalant about the test, but she had studied all weekend.","imageKeyword":"casual relaxed"},
{"word":"notoriety","level":5,"definition":"being famous for something bad","example":"The outlaw gained notoriety for robbing banks across three states.","imageKeyword":"infamous person"},
{"word":"nurture","level":5,"definition":"to care for and encourage the growth of someone or something","example":"Parents nurture their children by giving them love and support.","imageKeyword":"caring growth"},
{"word":"oblivious","level":5,"definition":"fully unaware of what is happening around you","example":"He was so focused on his book that he was oblivious to the noise.","imageKeyword":"person not noticing danger"},
{"word":"ominous","level":5,"definition":"giving the feeling that something bad will happen","example":"The ominous thunder made us hurry inside before the storm hit.","imageKeyword":"dark clouds"},
{"word":"oppression","level":5,"definition":"cruel and unfair treatment of people by those in power","example":"The people fought against oppression to gain their freedom.","imageKeyword":"chains bondage"},
{"word":"optimism","level":5,"definition":"hopefulness and confidence about the future","example":"His optimism about the project kept the team motivated.","imageKeyword":"bright sunshine"},
{"word":"ornate","level":5,"definition":"made pretty with many small details","example":"The ornate picture frame was covered in golden swirls and flowers.","imageKeyword":"decorated frame"},
{"word":"ostracize","level":5,"definition":"to exclude someone from a group","example":"It is wrong to ostracize a classmate just because they are different.","imageKeyword":"excluded alone"},
{"word":"paramount","level":5,"definition":"more important than anything else","example":"Safety is paramount when working in the science lab.","imageKeyword":"top priority"},
{"word":"penchant","level":5,"definition":"a strong liking or tendency toward something","example":"She had a penchant for collecting odd rocks from every trip.","imageKeyword":"favorite hobby"},
{"word":"penitent","level":5,"definition":"feeling sorry for doing something wrong","example":"The penitent student apologized sincerely for breaking the window.","imageKeyword":"sorry apology"},
{"word":"permeate","level":5,"definition":"to spread through every part of something","example":"The smell of fresh cookies permeated the entire house.","imageKeyword":"spreading aroma"},
{"word":"perpetuate","level":5,"definition":"to cause something to continue for a long time","example":"Sharing false rumors only perpetuates misunderstanding.","imageKeyword":"continuing cycle"},
{"word":"perseverance","level":5,"definition":"continuing to try hard even when things are difficult","example":"Her perseverance through months of practice made her a great swimmer.","imageKeyword":"never giving up"},
{"word":"pessimism","level":5,"definition":"a tendency to expect the worst outcome","example":"His pessimism made him think the team would lose before the game even started.","imageKeyword":"gloomy outlook"},
{"word":"placate","level":5,"definition":"to make someone less angry or upset","example":"She tried to placate her crying brother by offering him a cookie.","imageKeyword":"offering peace gift"},
{"word":"precinct","level":5,"definition":"a district of a city, especially for police or voting","example":"Each voting precinct has its own polling station.","imageKeyword":"district map"},
{"word":"predicament","level":5,"definition":"a difficult and unpleasant situation","example":"Getting locked out of the house was quite a predicament.","imageKeyword":"stuck trouble"},
{"word":"preemptive","level":5,"definition":"done before someone else can act, to prevent something","example":"The preemptive evacuation saved many lives before the flood hit.","imageKeyword":"acting first"},
{"word":"prerogative","level":5,"definition":"a special right that belongs to a particular person or group","example":"Choosing the movie was the birthday girl's prerogative.","imageKeyword":"special right"},
{"word":"prestige","level":5,"definition":"the respect and admiration earned through success","example":"Winning the national science fair brought prestige to the whole school.","imageKeyword":"trophy honor"},
{"word":"principled","level":5,"definition":"having strong moral rules that guide behavior","example":"The principled leader refused to lie even when it would have been easier.","imageKeyword":"person standing firm beliefs"},
{"word":"probation","level":5,"definition":"a period of testing to see if someone behaves well","example":"The student was put on probation and had to follow strict rules.","imageKeyword":"trial period"},
{"word":"proficiency","level":5,"definition":"a high degree of skill in something","example":"His proficiency in three languages impressed the interview panel.","imageKeyword":"skilled expert"},
{"word":"propensity","level":5,"definition":"a natural lean toward doing something often","example":"He has a propensity for asking questions in every class.","imageKeyword":"natural tendency"},
{"word":"proponent","level":5,"definition":"a person who supports and argues for something","example":"She is a proponent of longer recess times for students.","imageKeyword":"supporter advocate"},
{"word":"propriety","level":5,"definition":"correct and proper behavior","example":"The students showed propriety during the formal event.","imageKeyword":"formal etiquette manners"},
{"word":"prosperity","level":5,"definition":"the state of being successful and having wealth","example":"The prosperity of the town was visible in its new buildings and parks.","imageKeyword":"thriving town"},
{"word":"protagonist","level":5,"definition":"the main character in a story","example":"The protagonist of the novel was a brave girl on a quest.","imageKeyword":"main character"},
{"word":"provocation","level":5,"definition":"an action that is meant to make someone angry","example":"He ignored the provocation and walked away from the argument.","imageKeyword":"teasing anger"},
{"word":"purview","level":5,"definition":"the range of someone's authority or job","example":"Playground rules are within the purview of the recess monitors.","imageKeyword":"authority scope"},
{"word":"rebuke","level":5,"definition":"to criticize someone sharply for doing something wrong","example":"The coach rebuked the player for not following the team rules.","imageKeyword":"stern scolding"},
{"word":"redundant","level":5,"definition":"not needed because it repeats what has already been said or done","example":"Saying 'free gift' is redundant because all gifts are free.","imageKeyword":"extra repeated"},
{"word":"relinquish","level":5,"definition":"to give up power, control, or a possession","example":"The captain relinquished the ball to the referee after the whistle.","imageKeyword":"letting go"},
{"word":"remnant","level":5,"definition":"a small remaining piece of something larger","example":"The old wall was the last remnant of the original castle.","imageKeyword":"remaining piece"},
{"word":"remuneration","level":5,"definition":"payment for work done","example":"Fair remuneration for their work was what the employees demanded.","imageKeyword":"paycheck money"},
{"word":"renounce","level":5,"definition":"to formally give up something or say you no longer support it","example":"The prince renounced his claim to the throne.","imageKeyword":"giving up crown"},
{"word":"repercussion","level":5,"definition":"an unintended result of an action, often negative","example":"One repercussion of skipping practice was being benched for the game.","imageKeyword":"consequence result"},
{"word":"reprimand","level":5,"definition":"a formal statement of disapproval","example":"The student received a reprimand for talking during the test.","imageKeyword":"boss correcting employee"},
{"word":"resilience","level":5,"definition":"being able to heal quickly from problems","example":"Her resilience after the setback inspired her teammates to keep trying.","imageKeyword":"bouncing back"},
{"word":"resurgence","level":5,"definition":"a return to strength or popularity after a decline","example":"The old board game saw a resurgence when kids discovered it online.","imageKeyword":"comeback rising"},
{"word":"revere","level":5,"definition":"to have deep respect and admiration for someone","example":"The community revered the teacher who had taught there for forty years.","imageKeyword":"deep respect"},
{"word":"rudimentary","level":5,"definition":"basic and simple; at the earliest stage of development","example":"He had only a rudimentary understanding of how the engine worked.","imageKeyword":"simple basic"},
{"word":"sanctuary","level":5,"definition":"a safe place or a place where wildlife is protected","example":"The bird sanctuary protects hundreds of species during migration.","imageKeyword":"wildlife refuge"},
{"word":"secession","level":5,"definition":"officially leaving a group or country","example":"The secession of southern states led to the Civil War.","imageKeyword":"puzzle piece pulling away"},
{"word":"servitude","level":5,"definition":"the state of being a slave or being forced to work for others","example":"The prisoners were kept in servitude and forced to work long hours.","imageKeyword":"forced labor"},
{"word":"sporadic","level":5,"definition":"happening now and then without normal pattern","example":"The sporadic thunderstorms made it hard to plan outdoor activities.","imageKeyword":"scattered rain"},
{"word":"staunch","level":5,"definition":"very loyal and strong in support","example":"He was a staunch defender of animal rights.","imageKeyword":"loyal supporter"},
{"word":"strife","level":5,"definition":"angry fight and conflict","example":"Years of strife between the two families finally ended with a peace dinner.","imageKeyword":"conflict argument"},
{"word":"subjugate","level":5,"definition":"to bring under control by force","example":"The empire tried to subjugate smaller nations through military power.","imageKeyword":"forced control"},
{"word":"supremacy","level":5,"definition":"the state of having the most power or authority","example":"The team's supremacy in the league was clear from their undefeated record.","imageKeyword":"top power"},
{"word":"sustenance","level":5,"definition":"food and drink needed to stay alive","example":"The hikers packed enough sustenance for three days on the trail.","imageKeyword":"food water"},
{"word":"synthesis","level":5,"definition":"the combining of different thoughts or things to form something new","example":"Her essay was a synthesis of thoughts from three different books.","imageKeyword":"combining ideas"},
{"word":"temperament","level":5,"definition":"a person's natural character that affects how they behave","example":"The dog's calm temperament made it perfect for visiting hospitals.","imageKeyword":"calm nature"},
{"word":"totalitarian","level":5,"definition":"a system of state that controls every part of people's lives","example":"In a totalitarian state, the government decides what people can read and say.","imageKeyword":"strict control"},
{"word":"tranquility","level":5,"definition":"a state of peace and calm","example":"The tranquility of the lake at sunrise was breathtaking.","imageKeyword":"peaceful lake"},
{"word":"transparency","level":5,"definition":"openness and honesty, or being see-through","example":"Transparency in the state means citizens can see how decisions are made.","imageKeyword":"clear glass"},
{"word":"tribunal","level":5,"definition":"a special court set up to judge a particular matter","example":"The tribunal was formed to look into the unfair treatment of workers.","imageKeyword":"court hearing"},
{"word":"tumultuous","level":5,"definition":"very loud, confused, or full of strong emotions","example":"The tumultuous crowd cheered wildly when the winning goal was scored.","imageKeyword":"excited crowd"},
{"word":"tyranny","level":5,"definition":"cruel and unfair use of power by a ruler","example":"The people rebelled against the king's tyranny.","imageKeyword":"cruel ruler"},
{"word":"unilateral","level":5,"definition":"done by one side only without agreement from others","example":"The unilateral decision upset the other team members who were not asked.","imageKeyword":"one-sided choice"},
{"word":"unprecedented","level":5,"definition":"never having happened before","example":"AI is advancing at an unprecedented speed that surprises even the experts.","imageKeyword":"record breaking"},
{"word":"upheaval","level":5,"definition":"a big and sudden change that causes confusion","example":"Moving to a new country caused great upheaval in the family's life.","imageKeyword":"big change"},
{"word":"usurp","level":5,"definition":"to take power or a position by force without the right to do so","example":"The villain tried to usurp the throne from the rightful king.","imageKeyword":"seizing throne"},
{"word":"utopian","level":5,"definition":"imagining a perfect society where all things are ideal","example":"The story described a utopian world without poverty or war.","imageKeyword":"dreamy ideal society"},
{"word":"validate","level":5,"definition":"to prove that something is correct or acceptable","example":"The test helped validate her theory about plant growth.","imageKeyword":"checkmark approval"},
{"word":"vehement","level":5,"definition":"showing very strong feelings, especially anger or strong will","example":"His vehement protest against the unfair rule impressed the principal.","imageKeyword":"passionate protest"},
{"word":"viable","level":5,"definition":"capable of working well; practical","example":"Solar power is a viable alternative to burning fossil fuels.","imageKeyword":"working solution"},
{"word":"vigilant","level":5,"definition":"keeping careful watch for danger or problems","example":"The lifeguard remained vigilant while the children played in the pool.","imageKeyword":"watchful guard"},
{"word":"vindicate","level":5,"definition":"to prove that someone who was blamed is actually not at fault","example":"The new proof vindicated the student who had been falsely accused.","imageKeyword":"proven innocent"},
{"word":"voracious","level":5,"definition":"wanting a great amount of something; very eager","example":"She was a voracious learner who took every class available.","imageKeyword":"eager hungry"},
{"word":"wane","level":5,"definition":"to slowly decrease in strength or importance","example":"His interest in the project began to wane after the first week.","imageKeyword":"fading moon"},
{"word":"zealous","level":5,"definition":"showing great energy and enthusiasm for something","example":"The zealous volunteers arrived early to set up the charity event.","imageKeyword":"enthusiastic helper"},
{"word":"abdicate","level":5,"definition":"to give up a position of power, especially a throne","example":"The king chose to abdicate, so his son could rule.","imageKeyword":"stepping down"},
{"word":"accolade","level":5,"definition":"an award or praise given for achievement","example":"Winning the spelling bee was the highest accolade of his school year.","imageKeyword":"award trophy"},
{"word":"affable","level":5,"definition":"friendly and easy to talk to","example":"The affable shopkeeper greeted every buyer with a warm smile.","imageKeyword":"friendly smile"},
{"word":"ambivalent","level":5,"definition":"having mixed feelings about something","example":"She felt ambivalent about moving—excited also sad to leave friends.","imageKeyword":"mixed feelings"},
{"word":"amenable","level":5,"definition":"willing to agree or cooperate","example":"The teacher was amenable to extending the deadline by one day.","imageKeyword":"agreeable person"},
{"word":"amicable","level":5,"definition":"friendly and without arguments","example":"The two neighbors reached an amicable agreement about the shared fence.","imageKeyword":"friendly handshake"},
{"word":"anecdotal","level":5,"definition":"based on its own stories rather than facts or research","example":"His proof was only anecdotal—just stories from friends, not real data.","imageKeyword":"storytelling"},
{"word":"antipathy","level":5,"definition":"a deep feeling of dislike","example":"Her antipathy toward spiders meant she refused to enter the basement.","imageKeyword":"strong dislike"},
{"word":"apathetic","level":5,"definition":"showing no interest or enthusiasm","example":"The apathetic crowd barely clapped after the show.","imageKeyword":"bored audience"},
{"word":"attrition","level":5,"definition":"a gradual reduction in numbers or strength","example":"The long war was won through attrition as the enemy slowly ran out of supplies.","imageKeyword":"erosion slow decay"},
{"word":"bravado","level":5,"definition":"a bold manner meant to impress or hide fear","example":"His bravado disappeared the moment he saw how high the diving board was.","imageKeyword":"pretending brave"},
{"word":"cavalier","level":5,"definition":"showing a lack of proper concern","example":"His cavalier attitude about homework led to poor grades.","imageKeyword":"careless shrug"},
{"word":"cede","level":5,"definition":"to give up power or land to another","example":"The country was forced to cede the island after losing the war.","imageKeyword":"surrendering land"},
{"word":"charlatan","level":5,"definition":"a person who pretends to have skills they do not have","example":"The charlatan claimed to be a doctor but had no real training.","imageKeyword":"fake pretender"},
{"word":"circumspect","level":5,"definition":"careful to think of all possibilities before acting","example":"The circumspect hiker checked the weather forecast three times before setting out.","imageKeyword":"careful planning"},
{"word":"commensurate","level":5,"definition":"matching in size or degree","example":"Her reward was commensurate with the effort she put into the project.","imageKeyword":"equal match"},
{"word":"conciliatory","level":5,"definition":"intended to make peace or reduce anger","example":"His conciliatory tone helped calm the disagreement.","imageKeyword":"peacemaking"},
{"word":"congenial","level":5,"definition":"pleasant and agreeable","example":"The congenial atmosphere at camp made everyone feel welcome.","imageKeyword":"welcoming place"},
{"word":"connive","level":5,"definition":"to secretly plan something dishonest","example":"The two students connived to share answers during the quiz.","imageKeyword":"sneaky plan"},
{"word":"contrite","level":5,"definition":"feeling very sorry for something wrong you did","example":"The contrite student wrote a heartfelt apology letter.","imageKeyword":"sorry face"},
{"word":"conundrum","level":5,"definition":"a confusing problem that is hard to solve","example":"How to fit everyone in one car was quite a conundrum.","imageKeyword":"puzzle problem"},
{"word":"cosmopolitan","level":5,"definition":"with people from many different countries","example":"New York is a cosmopolitan city where hundreds of languages are spoken.","imageKeyword":"diverse city"},
{"word":"credulous","level":5,"definition":"too willing to believe things without proof","example":"The credulous child believed every tall tale his older brother told.","imageKeyword":"gullible believing"},
{"word":"debacle","level":5,"definition":"a complete failure or disaster","example":"The field day was a debacle when the rain ruined every event.","imageKeyword":"disaster mess"},
{"word":"demagogue","level":5,"definition":"a leader who gains power by appealing to people's emotions and fears","example":"The demagogue used angry speeches to turn people against each other.","imageKeyword":"angry speaker"},
{"word":"denouncement","level":5,"definition":"a public statement that something is wrong or evil","example":"The principal's denouncement of cheating was clear and firm.","imageKeyword":"public statement"},
{"word":"deprecate","level":5,"definition":"to express disapproval of something","example":"The review deprecated the film for its unrealistic storyline.","imageKeyword":"thumbs down"},
{"word":"derelict","level":5,"definition":"in very poor state from neglect","example":"The derelict building was covered in vines and had no windows left.","imageKeyword":"abandoned building"},
{"word":"digression","level":5,"definition":"a short-term departure from the main subject","example":"After a brief digression about his trip, the teacher returned to the lesson.","imageKeyword":"side path"},
{"word":"dirge","level":5,"definition":"a slow, sad song or piece of music for the dead","example":"The big band played a dirge at the memorial ceremony.","imageKeyword":"sad music"},
{"word":"dissident","level":5,"definition":"a person who publicly disagrees with the state","example":"The dissident spoke out against the unfair laws despite the risks.","imageKeyword":"protester speaking"},
{"word":"docile","level":5,"definition":"quiet and easy to control","example":"The docile pony was perfect for young riders to learn on.","imageKeyword":"gentle pony"},
{"word":"egregious","level":5,"definition":"terrible or shocking","example":"The referee made an egregious error that changed the outcome of the game.","imageKeyword":"terrible mistake"},
{"word":"elusive","level":5,"definition":"difficult to find, catch, or achieve","example":"The elusive butterfly flew just out of reach every time.","imageKeyword":"escaping butterfly"},
{"word":"emissary","level":5,"definition":"a person sent on a special mission as a representative","example":"The queen sent an emissary to bring his message to the neighboring kingdom.","imageKeyword":"messenger envoy"},
{"word":"exonerate","level":5,"definition":"to officially declare that someone is not guilty","example":"New DNA proof exonerated the man who had been wrongly imprisoned.","imageKeyword":"freed from prison innocent"},
{"word":"extrapolate","level":5,"definition":"to guess about the future based on known facts","example":"From the first three test scores, we can extrapolate how students might do on the final.","imageKeyword":"predicting trend"},
{"word":"fastidious","level":5,"definition":"very careful about details, wanting all things to be correct","example":"The fastidious editor found each tiny spelling mistake in the book.","imageKeyword":"perfectionist detail"},
{"word":"fiasco","level":5,"definition":"a complete and embarrassing failure","example":"The school play was a fiasco when the stage collapsed during act two.","imageKeyword":"stage collapse"},
{"word":"filibuster","level":5,"definition":"a very long speech made to delay a vote in government","example":"The senator used a filibuster to prevent the bill from being voted on.","imageKeyword":"long speech"},
{"word":"fracas","level":5,"definition":"a noisy argument or fight","example":"A fracas broke out in the cafeteria when someone cut in line.","imageKeyword":"noisy argument"},
{"word":"acclimate","level":5,"definition":"to adjust to new conditions or setting","example":"It took a few weeks to acclimate to the hot desert weather.","imageKeyword":"adjusting temperature"},
{"word":"agnostic","level":5,"definition":"a person who believes it is impossible to know whether God exists","example":"As an agnostic, she kept an open mind about questions of faith.","imageKeyword":"open question"},
{"word":"alacrity","level":5,"definition":"eager willingness and speed","example":"The students accepted the extra recess with great alacrity.","imageKeyword":"eager running"},
{"word":"arbitrate","level":5,"definition":"to act as a neutral judge in a disagreement","example":"The teacher was asked to arbitrate the dispute about the ball game rules.","imageKeyword":"neutral judge"},
{"word":"ascendancy","level":5,"definition":"a position of growing power or sway","example":"The team's ascendancy in the league continued with five straight wins.","imageKeyword":"rising arrow"},
{"word":"whimsical","level":5,"definition":"playfully odd or fanciful","example":"The whimsical garden had statues of dancing frogs and singing birds.","imageKeyword":"playful garden"},
{"word":"zenith","level":5,"definition":"the highest point; the peak","example":"The sun reached its zenith at noon, shining directly overhead.","imageKeyword":"highest point"},
{"word":"amicably","level":5,"definition":"in a friendly and pleasant manner","example":"The two teams settled their disagreement amicably over lunch.","imageKeyword":"peaceful friendly agreement"},
{"word":"gratify","level":5,"definition":"to give pleasure or satisfaction","example":"It gratified the teacher to see her students succeed on the exam.","imageKeyword":"happy satisfaction"},
{"word":"personable","level":5,"definition":"having a pleasant appearance and manner","example":"The personable host made every guest feel welcome at the party.","imageKeyword":"warm host"},
{"word":"perilous","level":5,"definition":"full of danger or risk","example":"The perilous mountain path had no guardrails along the cliff edge.","imageKeyword":"dangerous path"},
{"word":"orthodontics","level":5,"definition":"the branch of dentistry that corrects teeth and jaw alignment","example":"She studied orthodontics so she could help people get straighter teeth.","imageKeyword":"dental braces"},
{"word":"palindrome","level":5,"definition":"a word or phrase that reads the same backward and forward","example":"The word 'racecar' is a famous palindrome.","imageKeyword":"mirror word"}];
