const LEVEL5A_BANK=[{"word":"administer","level":5,"definition":"to manage or be in charge of something","example":"The principal will administer the school while the boss is away.","imageKeyword":"office manager"},
{"word":"adversary","level":5,"definition":"a person who is on the other side or fights you","example":"In chess, your adversary sits across the board planning their next move.","imageKeyword":"chess opponents"},
{"word":"affluent","level":5,"definition":"having a lot of money; wealthy","example":"The affluent neighborhood had large houses with swimming pools.","imageKeyword":"wealthy mansion"},
{"word":"apprehend","level":5,"definition":"to catch or arrest someone","example":"The police were able to apprehend the thief before he left the mall.","imageKeyword":"police catching"},
{"word":"aspiration","level":5,"definition":"a strong hope or ambition to achieve something","example":"His aspiration to become an astronaut drove him to study science every day.","imageKeyword":"dreaming big"},
{"word":"augment","level":5,"definition":"to make something greater by adding to it","example":"Smart glasses augment what you see by adding helpful information to your view.","imageKeyword":"adding more"},
{"word":"austere","level":5,"definition":"plain and simple, without trim or comfort","example":"The monk's austere room had only a bed, a table, and a single candle.","imageKeyword":"bare room"},
{"word":"authenticate","level":5,"definition":"to prove something is real or genuine","example":"The museum expert could authenticate the painting as a real Picasso.","imageKeyword":"examining artwork"},
{"word":"avert","level":5,"definition":"to turn away or prevent something bad","example":"Quick thinking helped the pilot avert a crash by changing course.","imageKeyword":"avoiding danger"},
{"word":"benevolent","level":5,"definition":"kind and generous; wanting to help others","example":"The benevolent donor gave a million dollars to build a children's hospital.","imageKeyword":"giving charity"},
{"word":"biodiversity","level":5,"definition":"the range of plant and animal life in an area","example":"The rainforest has incredible biodiversity with thousands of different species.","imageKeyword":"rainforest animals"},
{"word":"candid","level":5,"definition":"truthful and direct; saying what you really think","example":"Her candid review of the movie said it was boring despite the great special effects.","imageKeyword":"honest speaking"},
{"word":"capitalism","level":5,"definition":"a system where people own their own businesses","example":"Under capitalism, people can start their own companies and earn profits.","imageKeyword":"business owner"},
{"word":"circumference","level":5,"definition":"the distance around the outside of a circle","example":"We measured the circumference of the basketball using a piece of string.","imageKeyword":"circle measurement"},
{"word":"clamor","level":5,"definition":"a loud noise or strong demand from many people","example":"There was a clamor in the cafeteria when someone spotted a bird inside.","imageKeyword":"noisy crowd"},
{"word":"coerce","level":5,"definition":"to force someone to do something against their will","example":"The bully tried to coerce younger kids into giving up their lunch money.","imageKeyword":"forcing action"},
{"word":"comprise","level":5,"definition":"to be made up of; to include","example":"The United States comprises many states and several territories.","imageKeyword":"parts whole"},
{"word":"concurrent","level":5,"definition":"happening at the same time","example":"The two concerts were concurrent, so we had to choose which one to attend.","imageKeyword":"simultaneous events"},
{"word":"confer","level":5,"definition":"to discuss something with others before deciding","example":"The judges needed to confer before announcing the winner.","imageKeyword":"judges discussing"},
{"word":"confiscate","level":5,"definition":"to take something away as punishment or by authority","example":"The teacher had to confiscate the toy because it was distracting the class.","imageKeyword":"taking away"},
{"word":"conscientious","level":5,"definition":"careful and thorough in doing work","example":"The conscientious student double-checked each answer before turning in the test.","imageKeyword":"careful worker"},
{"word":"copyright","level":5,"definition":"the legal right to control how creative work is used","example":"The author holds the copyright to her novel, so no one can copy it.","imageKeyword":"copyright symbol"},
{"word":"correlate","level":5,"definition":"to have a connection or bond between two things","example":"Scientists found that more exercise tends to correlate with better sleep.","imageKeyword":"connected data"},
{"word":"culminate","level":5,"definition":"to reach the highest point or final result","example":"Months of rehearsal will culminate in the big performance on Friday night.","imageKeyword":"grand finale"},
{"word":"curtail","level":5,"definition":"to reduce or limit something","example":"Bad weather forced the school to curtail outdoor recess to just ten minutes.","imageKeyword":"scissors cutting ribbon short"},
{"word":"deem","level":5,"definition":"to consider or judge something in a certain way","example":"The principal deemed the hallway mural appropriate and allowed it to stay.","imageKeyword":"judging decision"},
{"word":"devise","level":5,"definition":"to invent or plan something clever","example":"The kids had to devise a plan to rescue their kite from the tall tree.","imageKeyword":"planning strategy"},
{"word":"displace","level":5,"definition":"to force something or someone out of its usual place","example":"The flood will displace hundreds of families from their homes.","imageKeyword":"moving away"},
{"word":"disposable","level":5,"definition":"designed to be thrown away after one use","example":"The cafeteria switched from disposable plates to reusable trays.","imageKeyword":"throwaway cup"},
{"word":"diversity","level":5,"definition":"a range of different types of people or things","example":"Our school celebrates the diversity of cultures represented by its students.","imageKeyword":"diverse people"},
{"word":"domesticate","level":5,"definition":"to tame a wild animal for human use","example":"Thousands of years ago humans began to domesticate wolves into dogs.","imageKeyword":"tamed animal"},
{"word":"dominance","level":5,"definition":"having the most power or control","example":"The lion's dominance over the pride means it eats first.","imageKeyword":"alpha lion"},
{"word":"embargo","level":5,"definition":"an official ban on trading with a country","example":"The embargo prevented any ships from delivering goods to that nation.","imageKeyword":"blocked trade"},
{"word":"entrepreneur","level":5,"definition":"a person who starts and runs their own business","example":"The young entrepreneur sold handmade bracelets at the farmers market.","imageKeyword":"business starter"},
{"word":"enumerate","level":5,"definition":"to list things one by one","example":"The teacher asked us to enumerate all the planets in our solar system.","imageKeyword":"numbered list"},
{"word":"equitable","level":5,"definition":"fair and equal for all involved","example":"The teacher found an equitable way to divide the art supplies among all groups.","imageKeyword":"fair sharing"},
{"word":"ethic","level":5,"definition":"a moral principle that guides a person's behavior","example":"His strong work ethic meant he always finished his homework before playing.","imageKeyword":"moral compass"},
{"word":"evoke","level":5,"definition":"to bring a feeling or memory to mind","example":"The smell of cookies can evoke happy memories of visiting grandma's house.","imageKeyword":"triggering memory"},
{"word":"excerpt","level":5,"definition":"a short passage taken from a longer work","example":"The teacher read an excerpt from the novel to get students interested.","imageKeyword":"book passage"},
{"word":"fabricate","level":5,"definition":"to make something up or invent a false story","example":"He tried to fabricate an excuse for being late, but the teacher didn't believe him.","imageKeyword":"making up"},
{"word":"fiscal","level":5,"definition":"about budgets, taxes, and how money is managed","example":"The school's fiscal year begins in September when the new budget starts.","imageKeyword":"financial calendar"},
{"word":"foremost","level":5,"definition":"most important or leading","example":"She is the foremost expert on dinosaurs at the natural history museum.","imageKeyword":"number one"},
{"word":"formulate","level":5,"definition":"to create or develop a plan or idea with care","example":"The detective needed time to formulate a theory about who committed the crime.","imageKeyword":"creating plan"},
{"word":"fracture","level":5,"definition":"a crack or break, especially in a bone","example":"The X-ray showed a small fracture in her wrist from the skateboard fall.","imageKeyword":"broken bone"},
{"word":"franchise","level":5,"definition":"a business given permission to sell another company's products","example":"The ice cream shop is a franchise with identical stores in fifty cities.","imageKeyword":"chain store"},
{"word":"gauge","level":5,"definition":"to measure or guess something","example":"It's hard to gauge how long the trip will take without checking the map.","imageKeyword":"measuring tool"},
{"word":"governance","level":5,"definition":"the way a group or country is managed","example":"Good governance means leaders make fair decisions that help all.","imageKeyword":"government building"},
{"word":"immigrate","level":5,"definition":"to move to a new country to live there permanently","example":"Her grandparents chose to immigrate to America for better chances.","imageKeyword":"new country"},
{"word":"imminent","level":5,"definition":"about to happen very soon","example":"The dark clouds meant a thunderstorm was imminent.","imageKeyword":"approaching storm"},
{"word":"imperative","level":5,"definition":"very important and urgent","example":"It is imperative that everyone evacuate the building during a fire drill.","imageKeyword":"urgent important"},
{"word":"implicate","level":5,"definition":"to show that someone is involved in something wrong","example":"The fingerprints on the cookie jar implicate the youngest brother.","imageKeyword":"evidence pointing"},
{"word":"implicit","level":5,"definition":"suggested but not directly stated","example":"There was an implicit understanding that everyone would help clean up after the party.","imageKeyword":"unspoken rule"},
{"word":"inquiry","level":5,"definition":"the process of asking questions to find answers or info","example":"The detective's inquiry into the missing bike led him to check every garage.","imageKeyword":"asking questions"},
{"word":"intensify","level":5,"definition":"to become stronger or more extreme","example":"The storm will intensify overnight with winds reaching 80 miles per hour.","imageKeyword":"growing stronger"},
{"word":"leverage","level":5,"definition":"the power to influence a situation or outcome","example":"Having more data gave the team leverage to win the debate.","imageKeyword":"gaining advantage"},
{"word":"locomotive","level":5,"definition":"the engine that pulls a train","example":"The strong locomotive pulled fifty freight cars along the mountain tracks.","imageKeyword":"train engine"},
{"word":"lure","level":5,"definition":"to attract or tempt someone toward something","example":"The bright colors of the candy display lure children into the store.","imageKeyword":"tempting bait"},
{"word":"maximize","level":5,"definition":"to make as large or great as possible","example":"To maximize your score, answer every question even if you're not sure.","imageKeyword":"biggest possible"},
{"word":"medium","level":5,"definition":"a way of talking or expressing thoughts","example":"The internet has become the main medium for sharing news.","imageKeyword":"communication channel"},
{"word":"membrane","level":5,"definition":"a thin layer that covers or separates things","example":"The cell membrane controls what goes in and out of each cell.","imageKeyword":"thin layer"},
{"word":"minimize","level":5,"definition":"to reduce to the smallest possible amount","example":"Wearing sunscreen helps minimize the risk of sunburn.","imageKeyword":"reducing small"},
{"word":"negligible","level":5,"definition":"so small that it's not worth worrying about","example":"The difference between their test scores was negligible—only one point.","imageKeyword":"tiny amount"},
{"word":"network","level":5,"definition":"a group of connected people, computers, or things","example":"The city has a network of underground tunnels connecting all the buildings.","imageKeyword":"connected web"},
{"word":"nominal","level":5,"definition":"very small; in name only","example":"The museum charges a nominal fee of one dollar to help cover costs.","imageKeyword":"tiny price"},
{"word":"objection","level":5,"definition":"a reason for disagreeing with something","example":"Her main objection to the plan was that it would take too long.","imageKeyword":"raising hand"},
{"word":"obligate","level":5,"definition":"to require or force someone to do something","example":"The contract will obligate you to mow the lawn every Saturday.","imageKeyword":"bound duty"},
{"word":"obsolete","level":5,"definition":"no longer useful because something better exists","example":"Typewriters became obsolete once computers became widely available.","imageKeyword":"outdated technology"},
{"word":"optimum","level":5,"definition":"the best or most favorable","example":"The optimum temperature for growing tomatoes is around 75 degrees.","imageKeyword":"perfect condition"},
{"word":"oversee","level":5,"definition":"to watch over and direct work being done","example":"The construction manager will oversee the building of the new gym.","imageKeyword":"supervising work"},
{"word":"parameter","level":5,"definition":"a limit or boundary that defines how something works","example":"One parameter of the test was that all plants must get equal sunlight.","imageKeyword":"set boundaries"},
{"word":"participation","level":5,"definition":"joining in and being part of an activity","example":"Class participation counts for twenty percent of your final grade.","imageKeyword":"joining activity"},
{"word":"portfolio","level":5,"definition":"a set of work or investments","example":"The artist brought her portfolio of paintings to the gallery interview.","imageKeyword":"work collection"},
{"word":"prior","level":5,"definition":"coming before something else","example":"Prior to starting fifth grade, she read all summer to prepare.","imageKeyword":"before time"},
{"word":"projection","level":5,"definition":"an estimate of what will happen in the future","example":"The weather projection shows sunny skies for the rest of the week.","imageKeyword":"future forecast"},
{"word":"propagate","level":5,"definition":"to spread or reproduce","example":"Dandelions propagate by sending fluffy seeds floating through the wind.","imageKeyword":"spreading seeds"},
{"word":"recession","level":5,"definition":"a period when the economy shrinks and people have less money","example":"During the recession many stores closed because people stopped shopping.","imageKeyword":"declining economy"},
{"word":"refine","level":5,"definition":"to improve something by making small changes","example":"He continued to refine his essay until every sentence was clear and strong.","imageKeyword":"polishing work"},
{"word":"reliance","level":5,"definition":"dependence on something","example":"Our reliance on smartphones means we feel lost without them.","imageKeyword":"depending on"},
{"word":"reluctance","level":5,"definition":"the feeling of not wanting to do something","example":"His reluctance to try new foods meant he always ordered the same thing.","imageKeyword":"hesitating back"},
{"word":"scrutiny","level":5,"definition":"careful and detailed examination","example":"The judge gave each contestant's artwork scrutiny before choosing a winner.","imageKeyword":"close examination"},
{"word":"sibling","level":5,"definition":"a brother or sister","example":"She is the oldest of four siblings, with two brothers and one sister.","imageKeyword":"brother sister"},
{"word":"specify","level":5,"definition":"to state exactly and clearly","example":"Please specify which flavor of ice cream you want—vanilla or chocolate.","imageKeyword":"exact detail"},
{"word":"stance","level":5,"definition":"a position or attitude on an issue","example":"Her stance on homework was that it should never take more than thirty minutes.","imageKeyword":"firm position"},
{"word":"accountability","level":5,"definition":"the state of being responsible for your actions","example":"Students learn accountability by turning in their own homework on time.","imageKeyword":"responsibility"},
{"word":"altruistic","level":5,"definition":"caring about others more than yourself","example":"Her altruistic nature led her to donate all her birthday money to charity.","imageKeyword":"giving hands"},
{"word":"caveat","level":5,"definition":"a warning or condition to keep in mind","example":"The free trial came with one caveat: you must cancel before thirty days.","imageKeyword":"warning sign"},
{"word":"condone","level":5,"definition":"to accept behavior that most people think is wrong","example":"The school does not condone bullying of any kind.","imageKeyword":"turning blind eye"},
{"word":"dearth","level":5,"definition":"a lack or shortage of something","example":"The dearth of rain caused the flowers to wilt in the garden.","imageKeyword":"empty well"},
{"word":"definitive","level":5,"definition":"final, complete, and most authoritative","example":"The encyclopedia was the definitive guide to world animals.","imageKeyword":"final book"},
{"word":"ebbing","level":5,"definition":"slowly decreasing or fading","example":"Interest in the old playground was ebbing as the new one opened.","imageKeyword":"fading tide"},
{"word":"embody","level":5,"definition":"to represent an idea in a visible form","example":"The statue embodies the spirit of freedom and courage.","imageKeyword":"statue"},
{"word":"espouse","level":5,"definition":"to publicly support a belief or thought","example":"The mayor espoused the importance of keeping the river clean.","imageKeyword":"supporting sign"},
{"word":"foreseeable","level":5,"definition":"able to be predicted or expected","example":"There are no snow days in the foreseeable future.","imageKeyword":"crystal ball"},
{"word":"hinder","level":5,"definition":"to make it difficult for something to happen","example":"Loud noise from the street hindered our ability to concentrate.","imageKeyword":"obstacle block"},
{"word":"inconclusive","level":5,"definition":"not leading to a firm decision or result","example":"The test was inconclusive, so we had to try again.","imageKeyword":"question mark"},
{"word":"indispensable","level":5,"definition":"absolutely necessary; cannot do without","example":"Clean water is indispensable for survival.","imageKeyword":"essential water"},
{"word":"innovative","level":5,"definition":"introducing new and creative thoughts or methods","example":"Self-driving cars are one of the most innovative uses of artificial intelligence.","imageKeyword":"bright idea"},
{"word":"methodical","level":5,"definition":"done in an organized and careful way","example":"His methodical approach to cleaning meant each corner was spotless.","imageKeyword":"organized steps"},
{"word":"multifaceted","level":5,"definition":"having many different aspects or sides","example":"Climate change is a multifaceted problem affecting food, water, and weather.","imageKeyword":"many sides"},
{"word":"negate","level":5,"definition":"to cancel out or make something have no effect","example":"Eating a whole cake would negate the benefits of exercising.","imageKeyword":"cancel out"},
{"word":"obligatory","level":5,"definition":"required by a rule or law","example":"Wearing a helmet is obligatory when riding a motorcycle.","imageKeyword":"required helmet"},
{"word":"optimal","level":5,"definition":"the best possible for a given situation","example":"The optimal temperature for baking bread is 375 degrees.","imageKeyword":"perfect setting"},
{"word":"parity","level":5,"definition":"the state of being equal","example":"The team worked toward pay parity, so everyone earned the same wage.","imageKeyword":"equal signs"},
{"word":"prerequisite","level":5,"definition":"something needed before you can do something else","example":"Passing the swim test is a prerequisite for joining the diving team.","imageKeyword":"first step"},
{"word":"prohibitive","level":5,"definition":"so high in cost that it prevents action","example":"The prohibitive price of the toy meant she had to save for months.","imageKeyword":"expensive tag"},
{"word":"proportional","level":5,"definition":"matching in size or amount relative to something else","example":"The tip should be proportional to the quality of the service.","imageKeyword":"matching ratio"},
{"word":"pursuant","level":5,"definition":"done in accordance with a rule or agreement","example":"Pursuant to school policy, all visitors must sign in at the office.","imageKeyword":"following rule"},
{"word":"refute","level":5,"definition":"to prove that something is wrong","example":"She refuted the claim by showing her receipts as evidence.","imageKeyword":"disproving"},
{"word":"respective","level":5,"definition":"belonging separately to each one mentioned","example":"The students returned to their respective classrooms after lunch.","imageKeyword":"own seats"},
{"word":"revoke","level":5,"definition":"to officially cancel or take away a right","example":"The school may revoke your library card if you lose too many books.","imageKeyword":"canceled card"},
{"word":"solicit","level":5,"definition":"to ask for something from someone","example":"Volunteers went door to door to solicit donations for the food bank.","imageKeyword":"asking donation"},
{"word":"statutory","level":5,"definition":"required or established by law","example":"The statutory speed limit on this road is thirty miles per hour.","imageKeyword":"speed limit sign"},
{"word":"suffice","level":5,"definition":"to be enough for a particular purpose","example":"A simple apology will suffice—you don't need to buy a gift.","imageKeyword":"just enough"},
{"word":"surge","level":5,"definition":"a sudden powerful increase","example":"A surge of wind knocked the kite out of his hands.","imageKeyword":"power wave"},
{"word":"surmise","level":5,"definition":"to guess based on limited proof","example":"From the empty plate, she surmised that someone had eaten lunch.","imageKeyword":"guessing"},
{"word":"tangible","level":5,"definition":"able to be touched or felt; real and concrete","example":"The trophy was tangible proof of the team's hard work.","imageKeyword":"holding trophy"},
{"word":"tenuous","level":5,"definition":"very weak or slight; not strong","example":"The connection between the two clues was tenuous at best.","imageKeyword":"thin thread"},
{"word":"uphold","level":5,"definition":"to support or maintain a law or belief","example":"The court chose to uphold the original ruling.","imageKeyword":"holding up law"},
{"word":"wield","level":5,"definition":"to hold and use a tool or power","example":"The knight wielded a shining silver sword in battle.","imageKeyword":"holding sword"},
{"word":"abysmal","level":5,"definition":"very bad or of very poor quality","example":"The team's abysmal record of zero wins disappointed all.","imageKeyword":"deep pit"},
{"word":"accrue","level":5,"definition":"to increase over time through gradual addition","example":"Interest will accrue in your savings account each month.","imageKeyword":"growing coins"},
{"word":"acrimonious","level":5,"definition":"angry and bitter in tone","example":"The acrimonious debate left both sides feeling upset.","imageKeyword":"bitter argument"},
{"word":"adroit","level":5,"definition":"clever and skillful","example":"The adroit magician made the coin vanish from his hand.","imageKeyword":"skillful hands"},
{"word":"afoot","level":5,"definition":"happening or being planned","example":"Something mysterious was afoot when all the lights went out.","imageKeyword":"sneaky footsteps"},
{"word":"agonize","level":5,"definition":"to worry greatly about a choice","example":"He agonized over which dress to wear to the school dance.","imageKeyword":"worried thinking"},
{"word":"allay","level":5,"definition":"to reduce fear or worry","example":"The doctor's kind words helped allay the patient's fears about surgery.","imageKeyword":"calming hand"},
{"word":"aloof","level":5,"definition":"distant and not friendly or keen","example":"The new student seemed aloof, sitting alone at lunch every day.","imageKeyword":"sitting alone"},
{"word":"amalgam","level":5,"definition":"a mixture or blend of different things","example":"The city's culture is an amalgam of traditions from many countries.","imageKeyword":"mixed blend"},
{"word":"amenity","level":5,"definition":"a useful or pleasant feature of a place","example":"The hotel's amenities included a pool, gym, and free breakfast.","imageKeyword":"hotel pool"},
{"word":"amorphous","level":5,"definition":"having no clear shape or structure","example":"The amorphous blob of clay waited to be shaped into a vase.","imageKeyword":"shapeless blob"},
{"word":"anguish","level":5,"definition":"severe pain or suffering, especially emotional","example":"The anguish of losing her pet was written all over her face.","imageKeyword":"crying face"},
{"word":"aplomb","level":5,"definition":"self-confidence and composure","example":"She handled the surprise quiz with aplomb, finishing first.","imageKeyword":"calm confidence"},
{"word":"banal","level":5,"definition":"boring because it has been said too many times","example":"The speech was full of banal phrases like 'try your best.'","imageKeyword":"boring speech"},
{"word":"belie","level":5,"definition":"to give a false impression of something","example":"Her calm smile belied the nervousness she felt inside.","imageKeyword":"hidden feeling"},
{"word":"berate","level":5,"definition":"to scold someone angrily and at length","example":"The coach berated the team for not trying hard enough.","imageKeyword":"angry scolding"},
{"word":"bereft","level":5,"definition":"lacking something needed; deprived","example":"The garden looked bereft of color after the frost killed all the flowers.","imageKeyword":"bare garden"},
{"word":"blatant","level":5,"definition":"very clear and done without shame","example":"Copying answers from a neighbor is a blatant form of cheating.","imageKeyword":"obvious cheat"},
{"word":"blithe","level":5,"definition":"showing a carefree lack of concern","example":"His blithe attitude about the test worried his parents.","imageKeyword":"carefree skip"},
{"word":"bombastic","level":5,"definition":"using impressive words that sound important but mean little","example":"The politician's bombastic speech was full of big words but few ideas.","imageKeyword":"puffed up"},
{"word":"brandish","level":5,"definition":"to wave something around threateningly","example":"The pirate brandished his sword and shouted at the sailors.","imageKeyword":"waving sword"},
{"word":"brazen","level":5,"definition":"bold and shameless","example":"The brazen squirrel stole a sandwich right off the picnic table.","imageKeyword":"bold squirrel"},
{"word":"callous","level":5,"definition":"showing no concern for others' feelings","example":"His callous remark about her painting made her cry.","imageKeyword":"cold heart"},
{"word":"censure","level":5,"definition":"to express strong disapproval officially","example":"The student council voted to censure the member who broke the rules.","imageKeyword":"official scold"},
{"word":"penurious","level":5,"definition":"very poor; unwilling to spend money","example":"The penurious family could barely afford groceries each week.","imageKeyword":"empty pockets"},
{"word":"clout","level":5,"definition":"influence or power, especially in politics","example":"The principal had enough clout to change the school lunch menu.","imageKeyword":"powerful influence"},
{"word":"coffer","level":5,"definition":"a strongbox for money; funds or treasury","example":"The club's coffers were empty after paying for the field trip.","imageKeyword":"treasure chest"},
{"word":"comport","level":5,"definition":"to behave in a particular way","example":"She comported herself with dignity during the award event.","imageKeyword":"proper behavior"},
{"word":"consign","level":5,"definition":"to deliver or hand over something permanently","example":"Old toys were consigned to the donation box.","imageKeyword":"handing over box"},
{"word":"construe","level":5,"definition":"to interpret the meaning of something","example":"His silence was construed as agreement by the rest of the group.","imageKeyword":"interpreting sign"},
{"word":"corrosive","level":5,"definition":"tending to destroy or wear away slowly","example":"The corrosive acid slowly ate through the metal container.","imageKeyword":"acid bottle"},
{"word":"decry","level":5,"definition":"to publicly criticize something as bad or wrong","example":"Environmental groups decried the plan to cut down the old forest.","imageKeyword":"public protest"},
{"word":"delude","level":5,"definition":"to make someone believe something that is not true","example":"Don't delude yourself into thinking you can pass without studying.","imageKeyword":"false mirror"},
{"word":"deplore","level":5,"definition":"to feel strong disapproval of something","example":"Teachers deplore cheating because it hurts everyone's learning.","imageKeyword":"shaking head"},
{"word":"despot","level":5,"definition":"a ruler who uses power in a cruel way","example":"The despot forced the people to work without pay.","imageKeyword":"cruel king"},
{"word":"didactic","level":5,"definition":"intended to teach a moral lesson","example":"The didactic fable taught children the value of honesty.","imageKeyword":"teaching story"},
{"word":"diffident","level":5,"definition":"shy and lacking self-confidence","example":"The diffident boy spoke so quietly that nobody could hear him.","imageKeyword":"shy child"},
{"word":"disparate","level":5,"definition":"very different from each other","example":"The two sisters had disparate interests—one loved sports the other art.","imageKeyword":"different items"},
{"word":"edify","level":5,"definition":"to teach and improve someone morally or intellectually","example":"The documentary was designed to edify viewers about ocean life.","imageKeyword":"teaching light"},
{"word":"emaciated","level":5,"definition":"abnormally thin and weak from lack of food","example":"The emaciated stray cat was taken to a shelter for care.","imageKeyword":"thin cat"},
{"word":"embroil","level":5,"definition":"to involve someone in a conflict or difficult situation","example":"The argument embroiled the entire class in a heated debate.","imageKeyword":"tangled mess"},
{"word":"encumber","level":5,"definition":"to weigh down or make movement difficult","example":"The heavy backpack encumbered the hiker on the steep trail.","imageKeyword":"heavy load"},
{"word":"equivocal","level":5,"definition":"unclear or having more than one meaning","example":"His equivocal answer left everyone unsure whether he agreed or not.","imageKeyword":"unclear reply"},
{"word":"estrange","level":5,"definition":"to cause someone to become unfriendly or distant","example":"The argument estranged the two best friends for an entire year.","imageKeyword":"growing apart"},
{"word":"exhort","level":5,"definition":"to strongly urge someone to do something","example":"The principal exhorted students to read at least one book a week.","imageKeyword":"urging speech"},
{"word":"extenuate","level":5,"definition":"to make a fault seem less serious","example":"Her apology helped extenuate the offense in the teacher's eyes.","imageKeyword":"lessening blame"},
{"word":"extol","level":5,"definition":"to praise something with excitement","example":"The teacher extolled the benefits of reading every single day.","imageKeyword":"praising loudly"},
{"word":"facetious","level":5,"definition":"treating serious issues with deliberately inappropriate humor","example":"His facetious comment about the test made everyone laugh nervously.","imageKeyword":"joking face"},
{"word":"felicitous","level":5,"definition":"well-chosen and very right","example":"The teacher made a felicitous comparison between rivers and time.","imageKeyword":"perfect choice"},
{"word":"fetter","level":5,"definition":"to restrict or restrain someone's freedom","example":"Too many rules can fetter a student's new ideas.","imageKeyword":"chains"},
{"word":"fickle","level":5,"definition":"changing opinions or loyalty a lot","example":"The fickle weather changed from sunny to rainy three times today.","imageKeyword":"changing wind"},
{"word":"foment","level":5,"definition":"to stir up or encourage trouble","example":"The troublemaker tried to foment a food fight in the cafeteria.","imageKeyword":"stirring pot"},
{"word":"furtive","level":5,"definition":"secretive and trying to avoid being noticed","example":"The furtive glance at his neighbor's test paper was caught by the teacher.","imageKeyword":"sneaky look"},
{"word":"gauche","level":5,"definition":"lacking social grace; awkward","example":"It was gauche to start eating before everyone was seated at the table.","imageKeyword":"awkward moment"},
{"word":"genial","level":5,"definition":"friendly and cheerful","example":"The genial host greeted every guest with a warm handshake.","imageKeyword":"warm greeting"},
{"word":"glean","level":5,"definition":"to collect information bit by bit","example":"She gleaned useful facts from several different library books.","imageKeyword":"gathering bits"},
{"word":"guise","level":5,"definition":"an outward appearance used to hide the truth","example":"The spy entered the party in the guise of a waiter.","imageKeyword":"disguise mask"},
{"word":"hapless","level":5,"definition":"unlucky; unfortunate","example":"The hapless traveler lost his wallet, then missed his flight.","imageKeyword":"unlucky person"},
{"word":"harrowing","level":5,"definition":"very frightening or distressing","example":"The harrowing rescue of the trapped miners was shown on the news.","imageKeyword":"scary rescue"},
{"word":"haughty","level":5,"definition":"behaving in a proud and unfriendly way","example":"The haughty queen refused to speak with the common villagers.","imageKeyword":"snobby look"},
{"word":"idyllic","level":5,"definition":"very peaceful and pleasant","example":"The idyllic village had flower gardens, and a quiet stream.","imageKeyword":"peaceful village"},
{"word":"impeccable","level":5,"definition":"without any faults; perfect","example":"His impeccable spelling earned his first place in the spelling bee.","imageKeyword":"perfect score"},
{"word":"implacable","level":5,"definition":"impossible to satisfy or calm down","example":"The implacable critic never had a kind word for any performance.","imageKeyword":"unmovable rock"},
{"word":"impregnable","level":5,"definition":"impossible to defeat or capture","example":"The castle's thick walls made it seem impregnable to attackers.","imageKeyword":"strong fortress"},
{"word":"impropriety","level":5,"definition":"behavior that is not proper or acceptable","example":"Talking during the national anthem was considered an impropriety.","imageKeyword":"rude behavior"},
{"word":"inauspicious","level":5,"definition":"not showing signs of future success","example":"The inauspicious start to the game—two errors in the first inning—worried the fans.","imageKeyword":"bad start"},
{"word":"incorrigible","level":5,"definition":"impossible to correct or improve","example":"The incorrigible puppy kept chewing shoes no matter what we tried.","imageKeyword":"naughty puppy"},
{"word":"incredulous","level":5,"definition":"unwilling or unable to believe something","example":"She was incredulous when told she had won the grand prize.","imageKeyword":"shocked face"},
{"word":"indefatigable","level":5,"definition":"never getting tired or giving up","example":"The indefatigable runner completed five marathons in one year.","imageKeyword":"tireless runner"},
{"word":"indelible","level":5,"definition":"impossible to remove or forget","example":"The trip to the Grand Canyon left an indelible impression on her mind.","imageKeyword":"permanent mark"},
{"word":"indolent","level":5,"definition":"wanting to avoid action or work; lazy","example":"The indolent cat spent the entire day sleeping on the couch.","imageKeyword":"lazy cat"},
{"word":"inept","level":5,"definition":"lacking skill; clumsy","example":"His inept attempt at juggling sent all three balls rolling away.","imageKeyword":"clumsy juggler"},
{"word":"intractable","level":5,"definition":"very difficult to deal with or solve","example":"The intractable math problem stumped even the brightest students.","imageKeyword":"impossible puzzle"},
{"word":"irksome","level":5,"definition":"annoying and irritating","example":"The irksome buzzing of the fly made it hard to concentrate.","imageKeyword":"annoying fly"},
{"word":"judicious","level":5,"definition":"having or showing good judgment","example":"A judicious use of her allowance let her save enough for the bike.","imageKeyword":"wise spending"},
{"word":"latent","level":5,"definition":"existing but not yet visible or active","example":"His latent talent for singing was discovered during music class.","imageKeyword":"hidden talent"},
{"word":"laud","level":5,"definition":"to praise highly","example":"Critics lauded the young author for her brilliant first novel.","imageKeyword":"praising hands"},
{"word":"lethargic","level":5,"definition":"lacking energy; sluggish","example":"The hot day made the students feel lethargic during afternoon classes.","imageKeyword":"sleepy student"},
{"word":"levity","level":5,"definition":"humor or lack of seriousness, especially when it is not expected","example":"A bit of levity from the teacher helped ease the tension before the exam.","imageKeyword":"light laughter"},
{"word":"lofty","level":5,"definition":"very tall and impressive; also noble in aspiration","example":"The lofty mountain peaks were covered in snow year-round.","imageKeyword":"tall mountain"},
{"word":"ludicrous","level":5,"definition":"so foolish or unfair that it is amusing","example":"The idea of keeping a pet elephant in a tiny apartment is ludicrous.","imageKeyword":"silly idea"},
{"word":"malign","level":5,"definition":"to speak about someone in a harmful and untrue way","example":"It is wrong to malign someone behind their back.","imageKeyword":"harmful gossip"},
{"word":"malleable","level":5,"definition":"easily shaped or influenced","example":"Gold is one of the most malleable metals on Earth.","imageKeyword":"bending metal"},
{"word":"meritorious","level":5,"definition":"deserving reward or praise","example":"The student received an award for meritorious service to the town.","imageKeyword":"award ribbon"},
{"word":"misnomer","level":5,"definition":"a wrong or inaccurate name","example":"Calling a koala a bear is a misnomer because it is actually a marsupial.","imageKeyword":"wrong label"},
{"word":"modicum","level":5,"definition":"a small amount of something","example":"With a modicum of effort, you can keep your room tidy.","imageKeyword":"tiny bit"},
{"word":"mundane","level":5,"definition":"lacking excitement; ordinary","example":"Washing dishes is a mundane chore that still needs to be done.","imageKeyword":"boring chores"},
{"word":"nonplussed","level":5,"definition":"so surprised that you do not know how to react","example":"She was nonplussed when the principal announced a surprise holiday.","imageKeyword":"stunned look"},
{"word":"noxious","level":5,"definition":"harmful or poisonous","example":"Noxious fumes from the factory polluted the nearby lake.","imageKeyword":"toxic smoke"},
{"word":"nuance","level":5,"definition":"a subtle difference in meaning or quality","example":"Understanding the nuance between 'happy' and 'elated' improves your writing.","imageKeyword":"subtle shade"},
{"word":"obtuse","level":5,"definition":"slow to understand; not sharp-minded","example":"He was being obtuse on purpose, pretending not to understand the joke.","imageKeyword":"confused face"},
{"word":"odious","level":5,"definition":"very unpleasant; hateful","example":"The odious smell from the garbage made everyone cover their noses.","imageKeyword":"terrible smell"},
{"word":"omnipotent","level":5,"definition":"having unlimited power","example":"In the story, the wizard was omnipotent and could control the weather.","imageKeyword":"powerful wizard"},
{"word":"opportune","level":5,"definition":"happening at a very good or convenient time","example":"The rain stopped at an opportune moment, just before the outdoor concert.","imageKeyword":"perfect timing"},
{"word":"palatial","level":5,"definition":"resembling a palace; grand and spacious","example":"The palatial mansion had thirty rooms, and a marble staircase.","imageKeyword":"grand palace"},
{"word":"palliate","level":5,"definition":"to make something less severe without removing the cause","example":"Medicine can palliate the pain even if it cannot cure the illness.","imageKeyword":"easing pain"},
{"word":"palpable","level":5,"definition":"so strong that it can almost be felt or touched","example":"The tension in the room was palpable as the winner was announced.","imageKeyword":"thick tension"},
{"word":"panoramic","level":5,"definition":"giving a wide unobstructed view","example":"The panoramic view from the mountaintop showed the entire valley.","imageKeyword":"wide view"},
{"word":"pariah","level":5,"definition":"an outcast; someone avoided by others","example":"After telling on his teammates, he became a pariah in the group.","imageKeyword":"alone outsider"},
{"word":"pastoral","level":5,"definition":"showing a calm, peaceful countryside scene","example":"The pastoral landscape of green hills and grazing sheep calmed her mind.","imageKeyword":"countryside scene"},
{"word":"pathos","level":5,"definition":"a quality that evokes pity or sadness","example":"The ending of the movie was full of pathos that moved the audience to tears.","imageKeyword":"sad moment"},
{"word":"petulant","level":5,"definition":"childishly bad-tempered and sulky","example":"The petulant child stomped his feet when he did not get dessert.","imageKeyword":"pouting child"},
{"word":"bowstring","level":5,"definition":"the string on a bow used to shoot arrows","example":"He pulled back the bowstring and let the arrow fly.","imageKeyword":"bowstring arrow"},
{"word":"foxglove","level":5,"definition":"a tall plant with bell-shaped flowers","example":"The foxglove grew next to the garden wall.","imageKeyword":"foxglove flower"},
{"word":"inkwell","level":5,"definition":"a small pot that holds ink for writing","example":"He dipped his pen into the inkwell.","imageKeyword":"inkwell pen"},
{"word":"oxbow","level":5,"definition":"a U-shaped bend in a river","example":"The river formed an oxbow around the hill.","imageKeyword":"oxbow river"},
{"word":"molt","level":5,"definition":"to shed skin, feathers, or fur","example":"The snake molted its old skin and grew a new one.","imageKeyword":"molt snake"},
{"word":"abiotic","level":5,"definition":"not living; non-living parts of nature","example":"Rocks and water are abiotic parts of the environment.","imageKeyword":"abiotic rocks"},
{"word":"abscond","level":5,"definition":"to leave secretly and quickly","example":"The fox absconded with the farmer's chicken.","imageKeyword":"abscond escape"},
{"word":"copse","level":5,"definition":"a small, thick patch of trees or bushes","example":"Birds nested in the copse near the river.","imageKeyword":"copse trees"},
{"word":"desiccate","level":5,"definition":"to dry out completely","example":"The hot sun desiccated the fruit until it was like a chip.","imageKeyword":"desiccate dry"},
{"word":"efface","level":5,"definition":"to erase or wipe out","example":"Rain effaced the chalk drawing on the sidewalk.","imageKeyword":"efface erase"},
{"word":"bellicose","level":5,"definition":"wanting to fight or argue","example":"The bellicose dog growled at everyone who walked past the fence.","imageKeyword":"aggressive dog"}];
