const LEVEL1_BANK=[{"word":"puppy","level":1,"definition":"a baby dog","example":"The little puppy wagged its tail and licked my hand.","imageKeyword":"puppy"},
{"word":"kitten","level":1,"definition":"a baby cat","example":"The soft kitten curled up in my lap and purred.","imageKeyword":"kitten"},
{"word":"bunny","level":1,"definition":"a small rabbit","example":"The white bunny hopped across the grass.","imageKeyword":"bunny rabbit"},
{"word":"duckling","level":1,"definition":"a baby duck","example":"The yellow duckling followed its mother to the pond.","imageKeyword":"duckling"},
{"word":"chick","level":1,"definition":"a baby chicken","example":"The fluffy chick pecked at the seeds on the ground.","imageKeyword":"baby chick"},
{"word":"lamb","level":1,"definition":"a baby sheep","example":"The little lamb stayed close to its mother in the field.","imageKeyword":"lamb"},
{"word":"cub","level":1,"definition":"a baby bear or lion","example":"The bear cub played near the river while its mother watched.","imageKeyword":"bear cub"},
{"word":"fawn","level":1,"definition":"a baby deer","example":"The spotted fawn hid in the tall grass.","imageKeyword":"baby deer"},
{"word":"foal","level":1,"definition":"a baby horse","example":"The long-legged foal ran beside its mother.","imageKeyword":"baby horse"},
{"word":"pony","level":1,"definition":"a small horse","example":"She got to ride a pony at the farm.","imageKeyword":"pony"},
{"word":"rooster","level":1,"definition":"a male chicken that crows","example":"The rooster crowed loudly every morning at sunrise.","imageKeyword":"rooster"},
{"word":"hen","level":1,"definition":"a female chicken that lays eggs","example":"The hen sat on her eggs to keep them warm.","imageKeyword":"hen"},
{"word":"goose","level":1,"definition":"a large water bird with a long neck","example":"The goose honked and flapped its wings at us.","imageKeyword":"goose"},
{"word":"swan","level":1,"definition":"a large water bird with a long neck, often white","example":"The beautiful swan glided across the lake.","imageKeyword":"swan"},
{"word":"owl","level":1,"definition":"a bird that hunts at night","example":"The owl hooted from the tree when it got dark.","imageKeyword":"owl"},
{"word":"robin","level":1,"definition":"a small bird with a red or orange chest","example":"A robin sat on the fence singing a sweet song.","imageKeyword":"robin bird"},
{"word":"sparrow","level":1,"definition":"a small brown bird","example":"The tiny sparrow pecked crumbs from the sidewalk.","imageKeyword":"sparrow"},
{"word":"crow","level":1,"definition":"a big black bird","example":"The crow cawed loudly from the top of the tree.","imageKeyword":"crow"},
{"word":"eagle","level":1,"definition":"a very large bird that flies high","example":"The eagle soared high above the mountains.","imageKeyword":"eagle"},
{"word":"whale","level":1,"definition":"a very large sea mammal","example":"We saw a huge whale jump out of the ocean.","imageKeyword":"whale"},
{"word":"dolphin","level":1,"definition":"a smart sea mammal that swims and breathes air","example":"The dolphin leaped out of the water and splashed back in.","imageKeyword":"dolphin"},
{"word":"shark","level":1,"definition":"a big fish with sharp teeth","example":"The shark swam fast through the dark water.","imageKeyword":"shark"},
{"word":"turtle","level":1,"definition":"an animal with a hard shell","example":"The turtle pulled its head inside its shell.","imageKeyword":"turtle"},
{"word":"lizard","level":1,"definition":"a small animal with four legs and a tail","example":"A green lizard sat on the warm rock in the sun.","imageKeyword":"lizard"},
{"word":"frog","level":1,"definition":"a small green animal that jumps and lives near water","example":"The frog jumped off the lily pad into the pond.","imageKeyword":"frog"},
{"word":"toad","level":1,"definition":"like a frog but with rough dry skin","example":"The toad sat in the mud near the garden.","imageKeyword":"toad"},
{"word":"snail","level":1,"definition":"a tiny animal with a shell that moves slowly","example":"The snail left a shiny trail on the leaf.","imageKeyword":"snail"},
{"word":"worm","level":1,"definition":"a long thin animal with no legs","example":"After the rain, a worm came out of the dirt.","imageKeyword":"worm"},
{"word":"spider","level":1,"definition":"a small creature with eight legs","example":"The spider made a web between two branches.","imageKeyword":"spider"},
{"word":"beetle","level":1,"definition":"an insect with a hard shell","example":"A shiny black beetle crawled across the log.","imageKeyword":"beetle"},
{"word":"ladybug","level":1,"definition":"a small red bug with black spots","example":"A ladybug landed on my finger, and then flew away.","imageKeyword":"ladybug"},
{"word":"butterfly","level":1,"definition":"an insect with big colorful wings","example":"The orange butterfly flew from flower to flower.","imageKeyword":"butterfly"},
{"word":"caterpillar","level":1,"definition":"a small worm-like insect that becomes a butterfly or moth","example":"The green caterpillar munched on leaves all day.","imageKeyword":"caterpillar"},
{"word":"ant","level":1,"definition":"a tiny bug that lives in a group","example":"The ant carried a crumb back to its hill.","imageKeyword":"ant"},
{"word":"bee","level":1,"definition":"a flying bug that makes honey","example":"The bee buzzed around the yellow flowers.","imageKeyword":"bee"},
{"word":"squirrel","level":1,"definition":"a small animal with a bushy tail","example":"The squirrel hid a nut inside the tree hole.","imageKeyword":"squirrel"},
{"word":"raccoon","level":1,"definition":"an animal with black fur around its eyes like a mask","example":"A raccoon knocked over the trash can at night.","imageKeyword":"raccoon"},
{"word":"skunk","level":1,"definition":"a black and white animal that smells bad","example":"We smelled the skunk before we even saw it.","imageKeyword":"skunk"},
{"word":"beaver","level":1,"definition":"an animal that builds dams with sticks","example":"The beaver chewed on a log to build its home.","imageKeyword":"beaver"},
{"word":"moose","level":1,"definition":"a very big deer with large flat antlers","example":"The huge moose stood in the middle of the road.","imageKeyword":"moose"},
{"word":"toast","level":1,"definition":"bread that is cooked until brown","example":"I put butter on my toast for breakfast.","imageKeyword":"toast"},
{"word":"cereal","level":1,"definition":"food you eat with milk, often for breakfast","example":"He poured cereal into his bowl and added milk.","imageKeyword":"cereal bowl"},
{"word":"pancake","level":1,"definition":"a flat round food you eat for breakfast","example":"Dad made a pancake shaped like a smiley face.","imageKeyword":"pancake"},
{"word":"waffle","level":1,"definition":"a breakfast food with little squares on it","example":"I poured syrup into the squares of my waffle.","imageKeyword":"waffle"},
{"word":"oatmeal","level":1,"definition":"a hot breakfast food made from oats","example":"On cold mornings, I like a warm bowl of oatmeal.","imageKeyword":"oatmeal"},
{"word":"sandwich","level":1,"definition":"food made with bread and something inside","example":"Mom packed a peanut butter sandwich in my lunch box.","imageKeyword":"sandwich"},
{"word":"pretzel","level":1,"definition":"a twisted baked snack","example":"The salty pretzel was shaped like a knot.","imageKeyword":"pretzel"},
{"word":"cracker","level":1,"definition":"thin dry food that crunches","example":"She put cheese on each cracker.","imageKeyword":"cracker"},
{"word":"noodle","level":1,"definition":"long thin food made from dough","example":"He slurped up the long noodle with his spoon.","imageKeyword":"noodle"},
{"word":"muffin","level":1,"definition":"a small soft cake","example":"The blueberry muffin was still warm from the oven.","imageKeyword":"muffin"},
{"word":"cupcake","level":1,"definition":"a small cake with frosting on top","example":"She licked the pink frosting off her cupcake.","imageKeyword":"cupcake"},
{"word":"cookie","level":1,"definition":"a small sweet flat food","example":"Grandma baked chocolate chip cookies for us.","imageKeyword":"cookie"},
{"word":"doughnut","level":1,"definition":"round sweet food with a hole","example":"The doughnut was covered in sugar and sprinkles.","imageKeyword":"doughnut"},
{"word":"pudding","level":1,"definition":"a soft sweet food you eat with a spoon","example":"The chocolate pudding was cold and smooth.","imageKeyword":"pudding"},
{"word":"jelly","level":1,"definition":"a soft sweet spread for bread","example":"I like grape jelly on my toast.","imageKeyword":"jelly jar"},
{"word":"syrup","level":1,"definition":"a thick sweet liquid","example":"He poured syrup all over his pancakes.","imageKeyword":"maple syrup"},
{"word":"honey","level":1,"definition":"sweet food that bees make","example":"Bears love to eat honey from beehives.","imageKeyword":"honey jar"},
{"word":"popcorn","level":1,"definition":"corn that pops when you heat it","example":"We ate popcorn while we watched the movie.","imageKeyword":"popcorn"},
{"word":"yogurt","level":1,"definition":"thick creamy food made from milk","example":"He stirred the yogurt and added some berries on top.","imageKeyword":"yogurt"},
{"word":"grape","level":1,"definition":"a small round fruit that grows in bunches","example":"She picked a purple grape off the vine.","imageKeyword":"grape"},
{"word":"cherry","level":1,"definition":"a small round red fruit","example":"The cherry on top of the ice cream was bright red.","imageKeyword":"cherry"},
{"word":"peach","level":1,"definition":"a soft fruit with fuzzy skin","example":"Juice dripped down my chin when I bit the peach.","imageKeyword":"peach"},
{"word":"plum","level":1,"definition":"a small purple fruit","example":"The ripe plum was sweet and juicy.","imageKeyword":"plum"},
{"word":"melon","level":1,"definition":"a large fruit with a thick skin and soft inside","example":"We cut the melon into slices on a hot day.","imageKeyword":"melon slice"},
{"word":"berry","level":1,"definition":"a small juicy fruit","example":"We picked every berry from the bush in our yard.","imageKeyword":"berries"},
{"word":"lemon","level":1,"definition":"a sour yellow fruit","example":"The lemon was too sour to eat by itself.","imageKeyword":"lemon"},
{"word":"coconut","level":1,"definition":"a big brown fruit with white inside","example":"We cracked open the coconut and drank the water inside.","imageKeyword":"coconut"},
{"word":"peanut","level":1,"definition":"a small food that grows in a shell underground","example":"The elephant ate a peanut right from my hand.","imageKeyword":"peanut"},
{"word":"celery","level":1,"definition":"a long green crunchy vegetable","example":"She dipped the celery stick into peanut butter.","imageKeyword":"celery"},
{"word":"broccoli","level":1,"definition":"a green vegetable that looks like a tiny tree","example":"The broccoli on my plate looked like little trees.","imageKeyword":"broccoli"},
{"word":"lettuce","level":1,"definition":"green leaves you eat in a salad","example":"The rabbit munched on the fresh green lettuce.","imageKeyword":"lettuce"},
{"word":"pepper","level":1,"definition":"a crunchy vegetable that can be red, green, or yellow","example":"Mom cut up a red pepper for our salad.","imageKeyword":"bell pepper"},
{"word":"onion","level":1,"definition":"a round vegetable that makes you cry","example":"Cutting the onion made tears run down my face.","imageKeyword":"onion"},
{"word":"mushroom","level":1,"definition":"a type of fungus that grows in damp places","example":"The mushroom grew under the big tree after the rain.","imageKeyword":"mushroom"},
{"word":"stew","level":1,"definition":"a thick hot soup with meat and vegetables","example":"The warm stew was perfect on a cold winter night.","imageKeyword":"stew pot"},
{"word":"gravy","level":1,"definition":"a thick sauce you pour on meat","example":"He poured gravy all over his mashed potatoes.","imageKeyword":"gravy"},
{"word":"feast","level":1,"definition":"a very big special meal","example":"The family had a feast with turkey and pie.","imageKeyword":"feast table"},
{"word":"snack","level":1,"definition":"a small bit of food between meals","example":"After school, he had a snack of apples and cheese.","imageKeyword":"snack"},
{"word":"treat","level":1,"definition":"a special food you don't have every day","example":"Ice cream after dinner was a special treat.","imageKeyword":"treat"},
{"word":"slice","level":1,"definition":"a thin piece cut from something","example":"Can I have one slice of pizza, please?","imageKeyword":"pizza slice"},
{"word":"elbow","level":1,"definition":"the part in the middle of your arm that can bend","example":"She bumped her elbow on the table and said ouch.","imageKeyword":"elbow"},
{"word":"wrist","level":1,"definition":"where your hand meets your arm","example":"She wore a pretty bracelet on her wrist.","imageKeyword":"wrist"},
{"word":"ankle","level":1,"definition":"where your foot meets your leg","example":"He twisted his ankle when he jumped off the step.","imageKeyword":"ankle"},
{"word":"heel","level":1,"definition":"the back part of your foot","example":"Her shoe rubbed a blister on her heel.","imageKeyword":"heel foot"},
{"word":"thumb","level":1,"definition":"the short fat finger on your hand","example":"The baby sucked his thumb when he was sleepy.","imageKeyword":"thumb"},
{"word":"palm","level":1,"definition":"the flat inside part of your hand","example":"He held the coin in the palm of his hand.","imageKeyword":"palm hand"},
{"word":"fist","level":1,"definition":"a hand with all fingers closed tight","example":"He made a fist and knocked on the door.","imageKeyword":"fist"},
{"word":"chin","level":1,"definition":"the bottom part of your face","example":"Juice dripped down his chin when he ate the peach.","imageKeyword":"chin"},
{"word":"cheek","level":1,"definition":"the soft side of your face","example":"Grandma kissed him on the cheek.","imageKeyword":"cheek face"},
{"word":"forehead","level":1,"definition":"the flat part above your eyes","example":"Mom felt my forehead to see if I had a fever.","imageKeyword":"forehead"},
{"word":"eyebrow","level":1,"definition":"the line of hair above your eye","example":"He raised one eyebrow when he was surprised.","imageKeyword":"eyebrow"},
{"word":"eyelash","level":1,"definition":"tiny hairs on the edge of your eye","example":"An eyelash fell on her cheek, and she made a wish.","imageKeyword":"eyelash"},
{"word":"tongue","level":1,"definition":"the soft part inside your mouth","example":"The dog stuck out its tongue and licked my face.","imageKeyword":"tongue"},
{"word":"throat","level":1,"definition":"the inside of your neck where food and air pass","example":"My throat hurt so much I could not swallow.","imageKeyword":"throat"},
{"word":"shoulder","level":1,"definition":"where your arm connects to your body","example":"She carried the bag over her shoulder.","imageKeyword":"shoulder"},
{"word":"hip","level":1,"definition":"the wide part where your legs meet your body","example":"He put his hands on his hips and said stop.","imageKeyword":"hip"},
{"word":"spine","level":1,"definition":"the bones down your back that help you stand straight","example":"Stand up straight, so your spine is not curved.","imageKeyword":"spine"},
{"word":"rib","level":1,"definition":"the bones around your chest that protect your body","example":"He laughed so hard his ribs hurt.","imageKeyword":"rib cage"},
{"word":"skull","level":1,"definition":"the bone that covers your brain","example":"Helmets protect your skull if you fall.","imageKeyword":"skull"},
{"word":"muscle","level":1,"definition":"the part of your body that helps you move","example":"He flexed his arm to show his muscles.","imageKeyword":"muscle arm"},
{"word":"mitten","level":1,"definition":"a warm cover for your hand with no fingers","example":"She put on a fuzzy mitten to keep her hand warm.","imageKeyword":"mitten"},
{"word":"scarf","level":1,"definition":"a long cloth you wrap around your neck","example":"The red scarf kept her neck warm in the snow.","imageKeyword":"scarf"},
{"word":"hoodie","level":1,"definition":"a shirt with a hood on the back","example":"He pulled the hood of his hoodie over his head in the rain.","imageKeyword":"hoodie"},
{"word":"vest","level":1,"definition":"a jacket with no sleeves","example":"He wore a warm vest over his shirt.","imageKeyword":"vest"},
{"word":"apron","level":1,"definition":"cloth you wear to keep clean while cooking","example":"Mom tied her apron before she started baking.","imageKeyword":"apron"},
{"word":"sleeve","level":1,"definition":"the part of a shirt that covers your arm","example":"He rolled up his sleeve before washing his hands.","imageKeyword":"sleeve"},
{"word":"pocket","level":1,"definition":"a small bag sewn into clothes","example":"He put the rock in his pocket to save for later.","imageKeyword":"pocket"},
{"word":"zipper","level":1,"definition":"something that opens and closes your jacket","example":"He pulled up the zipper on his coat because it was cold.","imageKeyword":"zipper"},
{"word":"button","level":1,"definition":"a small round thing that holds clothes closed","example":"One button on his shirt popped off.","imageKeyword":"button shirt"},
{"word":"buckle","level":1,"definition":"a metal clip that holds a belt closed","example":"He snapped the buckle on his belt.","imageKeyword":"belt buckle"},
{"word":"lace","level":1,"definition":"the string you tie on a shoe","example":"She pulled the lace tight and tied a bow on her shoe.","imageKeyword":"shoe lace"},
{"word":"slipper","level":1,"definition":"a soft shoe you wear inside","example":"She put on her fuzzy slipper when she got out of bed.","imageKeyword":"slipper"},
{"word":"sandal","level":1,"definition":"an open shoe for warm weather","example":"He wore a sandal to the beach, so sand wouldn't stay in his shoe.","imageKeyword":"sandal"},
{"word":"sneaker","level":1,"definition":"a shoe for running and playing","example":"She put on her sneaker before going to the playground.","imageKeyword":"sneaker"},
{"word":"boot","level":1,"definition":"a tall shoe that covers your ankle","example":"He wore a rain boot, so his feet stayed dry.","imageKeyword":"rain boot"},
{"word":"collar","level":1,"definition":"the part of a shirt around your neck","example":"The tag on his collar was itchy.","imageKeyword":"shirt collar"},
{"word":"hem","level":1,"definition":"the bottom edge of a skirt or pants","example":"The hem of her dress dragged on the floor.","imageKeyword":"dress hem"},
{"word":"pajamas","level":1,"definition":"clothes you wear to bed","example":"She changed into her pajamas and brushed her teeth.","imageKeyword":"pajamas"},
{"word":"costume","level":1,"definition":"special clothes to look like someone else","example":"He wore a pirate costume for Halloween.","imageKeyword":"costume"},
{"word":"uniform","level":1,"definition":"the same clothes everyone in a group wears","example":"All the players wore the same team uniform.","imageKeyword":"uniform"},
{"word":"blanket","level":1,"definition":"a soft cover for your bed","example":"She pulled the warm blanket up to her chin.","imageKeyword":"blanket"},
{"word":"pillow","level":1,"definition":"a soft thing you rest your head on","example":"He fluffed his pillow before going to sleep.","imageKeyword":"pillow"},
{"word":"towel","level":1,"definition":"cloth you use to dry off","example":"She wrapped a towel around herself after her bath.","imageKeyword":"towel"},
{"word":"soap","level":1,"definition":"what you use to get clean","example":"The soap made lots of bubbles in the bath.","imageKeyword":"soap bubbles"},
{"word":"sponge","level":1,"definition":"a soft thing that soaks up water","example":"Dad wiped the table with a wet sponge.","imageKeyword":"sponge"},
{"word":"broom","level":1,"definition":"a long stick with bristles for sweeping","example":"She used the broom to sweep the crumbs off the floor.","imageKeyword":"broom"},
{"word":"bucket","level":1,"definition":"a big container you carry things in","example":"He filled the bucket with sand at the beach.","imageKeyword":"bucket"},
{"word":"ladder","level":1,"definition":"something with steps you climb up","example":"Dad used a ladder to reach the roof.","imageKeyword":"ladder"},
{"word":"drawer","level":1,"definition":"a box that slides in and out of a desk","example":"She put her socks in the top drawer.","imageKeyword":"drawer"},
{"word":"shelf","level":1,"definition":"a flat board on a wall for holding things","example":"The books sat in a row on the shelf.","imageKeyword":"bookshelf"},
{"word":"closet","level":1,"definition":"a small room where you keep clothes","example":"He hung his coat in the closet.","imageKeyword":"closet"},
{"word":"curtain","level":1,"definition":"cloth that covers a window","example":"She opened the curtain to let the sun in.","imageKeyword":"curtain"},
{"word":"rug","level":1,"definition":"a soft cloth on the floor","example":"The cat slept on the soft rug by the fire.","imageKeyword":"rug"},
{"word":"lamp","level":1,"definition":"something that gives light","example":"He turned on the lamp to read his book.","imageKeyword":"lamp"},
{"word":"candle","level":1,"definition":"a stick of wax that burns with a flame","example":"We lit a candle when the lights went out.","imageKeyword":"candle"},
{"word":"vase","level":1,"definition":"a jar you put flowers in","example":"She put the roses in a pretty vase.","imageKeyword":"vase flowers"},
{"word":"frame","level":1,"definition":"a border around a picture","example":"The photo was in a wooden frame on the wall.","imageKeyword":"picture frame"},
{"word":"envelope","level":1,"definition":"a paper cover for a letter","example":"She sealed the envelope and put a stamp on it.","imageKeyword":"envelope"},
{"word":"stamp","level":1,"definition":"a small sticker you put on mail","example":"You need a stamp to send a letter.","imageKeyword":"postage stamp"},
{"word":"package","level":1,"definition":"a box that is sent to you","example":"A big package came in the mail today.","imageKeyword":"package box"},
{"word":"scissors","level":1,"definition":"a tool for cutting paper","example":"She used scissors to cut out the paper star.","imageKeyword":"scissors"},
{"word":"glue","level":1,"definition":"a sticky liquid that holds things together","example":"He used glue to stick the picture on the poster.","imageKeyword":"glue bottle"},
{"word":"tape","level":1,"definition":"sticky strip for holding things","example":"He used tape to hang the drawing on the fridge.","imageKeyword":"tape roll"},
{"word":"crayon","level":1,"definition":"a colored stick for drawing","example":"She picked a red crayon to color the apple.","imageKeyword":"crayon"},
{"word":"chalk","level":1,"definition":"a soft stick for writing on a board","example":"He drew a rainbow on the sidewalk with chalk.","imageKeyword":"chalk"},
{"word":"eraser","level":1,"definition":"something that removes pencil marks","example":"She rubbed the eraser over her mistake.","imageKeyword":"eraser"},
{"word":"ruler","level":1,"definition":"a straight tool for measuring","example":"He used a ruler to draw a straight line.","imageKeyword":"ruler"},
{"word":"thermometer","level":1,"definition":"a tool that tells how hot or cold it is","example":"Mom put the thermometer in my mouth to check my temperature.","imageKeyword":"thermometer"},
{"word":"battery","level":1,"definition":"the thing that gives power to a toy","example":"The toy stopped working because the battery was dead.","imageKeyword":"battery"},
{"word":"switch","level":1,"definition":"the thing you flip to turn something on or off","example":"He flipped the switch and the room went dark.","imageKeyword":"light switch"},
{"word":"barn","level":1,"definition":"a building on a farm for animals","example":"The cows went into the big red barn at night.","imageKeyword":"barn"},
{"word":"stable","level":1,"definition":"a building where horses live","example":"The horse walked back into its stable after the ride.","imageKeyword":"horse stable"},
{"word":"cabin","level":1,"definition":"a small house made of wood","example":"We stayed in a cozy cabin in the mountains.","imageKeyword":"log cabin"},
{"word":"cottage","level":1,"definition":"a small pretty house","example":"The old woman lived in a little cottage by the woods.","imageKeyword":"cottage"},
{"word":"castle","level":1,"definition":"a big stone building where kings live","example":"The princess lived in a tall castle on the hill.","imageKeyword":"castle"},
{"word":"tower","level":1,"definition":"a tall thin building","example":"She looked out from the top of the tower.","imageKeyword":"tower"},
{"word":"bridge","level":1,"definition":"a road over water or a valley","example":"We walked across the bridge to get to the other side of the river.","imageKeyword":"bridge"},
{"word":"tunnel","level":1,"definition":"a road that goes through a mountain","example":"The train went into the dark tunnel.","imageKeyword":"tunnel"},
{"word":"harbor","level":1,"definition":"a safe place where boats park","example":"The boats were tied up in the harbor.","imageKeyword":"harbor boats"},
{"word":"island","level":1,"definition":"land with water all around it","example":"The island was so small you could walk around it in one hour.","imageKeyword":"island"},
{"word":"forest","level":1,"definition":"a big area full of trees","example":"They got lost in the dark forest.","imageKeyword":"forest"},
{"word":"meadow","level":1,"definition":"a big open field of grass and flowers","example":"The deer ate grass in the sunny meadow.","imageKeyword":"meadow"},
{"word":"pond","level":1,"definition":"a small body of water","example":"The ducks swam around the pond.","imageKeyword":"pond"},
{"word":"stream","level":1,"definition":"a small river","example":"We stepped on rocks to cross the stream.","imageKeyword":"stream"},
{"word":"cliff","level":1,"definition":"a very tall rock wall","example":"The bird nested on the high cliff.","imageKeyword":"cliff"},
{"word":"cave","level":1,"definition":"a hole in a rock or mountain","example":"The bear went into the dark cave to sleep.","imageKeyword":"cave"},
{"word":"desert","level":1,"definition":"a dry place with sand and no water","example":"Nothing grew in the hot desert except cactus.","imageKeyword":"desert"},
{"word":"jungle","level":1,"definition":"a thick forest with many plants","example":"Monkeys swung from tree to tree in the jungle.","imageKeyword":"jungle"},
{"word":"swamp","level":1,"definition":"wet muddy land with water","example":"The alligator hid in the dark swamp.","imageKeyword":"swamp"},
{"word":"valley","level":1,"definition":"low land between two mountains","example":"The little town sat in the green valley.","imageKeyword":"valley"},
{"word":"storm","level":1,"definition":"very bad weather with wind and rain","example":"The storm blew the tree branches everywhere.","imageKeyword":"storm"},
{"word":"thunder","level":1,"definition":"the loud boom sound in a storm","example":"The thunder was so loud it shook the windows.","imageKeyword":"thunder"},
{"word":"lightning","level":1,"definition":"a flash of light in the sky during a storm","example":"The lightning lit up the whole sky for a second.","imageKeyword":"lightning"},
{"word":"rainbow","level":1,"definition":"a colorful arc in the sky after rain","example":"After the rain stopped, a beautiful rainbow appeared.","imageKeyword":"rainbow"},
{"word":"breeze","level":1,"definition":"a gentle soft wind","example":"The light breeze made the leaves dance.","imageKeyword":"breeze wind"},
{"word":"frost","level":1,"definition":"thin ice that forms on cold mornings","example":"The grass was white with frost on the cold morning.","imageKeyword":"frost"},
{"word":"icicle","level":1,"definition":"a long pointed piece of ice hanging down","example":"A long icicle hung from the roof.","imageKeyword":"icicle"},
{"word":"puddle","level":1,"definition":"a small pool of water on the ground","example":"She jumped in every puddle on the way to school.","imageKeyword":"puddle"},
{"word":"mud","level":1,"definition":"wet dirt","example":"The pig rolled in the mud to stay cool.","imageKeyword":"mud"},
{"word":"dust","level":1,"definition":"tiny bits of dry dirt in the air","example":"The old book was covered in dust.","imageKeyword":"dust"},
{"word":"dew","level":1,"definition":"tiny water drops on grass in the morning","example":"The dew on the flowers sparkled in the sun.","imageKeyword":"morning dew"},
{"word":"fog","level":1,"definition":"a cloud close to the ground","example":"The fog was so thick we could not see the road.","imageKeyword":"fog"},
{"word":"hail","level":1,"definition":"balls of ice that fall from the sky","example":"The hail bounced off the car like little white stones.","imageKeyword":"hail"},
{"word":"blizzard","level":1,"definition":"a big snow storm with strong wind","example":"The blizzard dropped so much snow we could not open the door.","imageKeyword":"blizzard"},
{"word":"drought","level":1,"definition":"a long time with no rain","example":"The flowers died because of the long drought.","imageKeyword":"dry land"},
{"word":"flood","level":1,"definition":"when water covers land that is usually dry","example":"The river rose so high it caused a flood.","imageKeyword":"flood"},
{"word":"petal","level":1,"definition":"one soft piece of a flower","example":"A pink petal fell from the rose.","imageKeyword":"flower petal"},
{"word":"stem","level":1,"definition":"the long green part of a plant","example":"He held the flower by its long green stem.","imageKeyword":"plant stem"},
{"word":"root","level":1,"definition":"the part of a plant under the ground","example":"The tree's root went deep into the dirt.","imageKeyword":"tree root"},
{"word":"thorn","level":1,"definition":"a sharp point on a plant","example":"She pricked her finger on the rose's thorn.","imageKeyword":"thorn"},
{"word":"vine","level":1,"definition":"a plant that grows along the ground or up walls","example":"The vine climbed all the way up the old wall.","imageKeyword":"vine"},
{"word":"moss","level":1,"definition":"soft green material that grows on rocks","example":"The rocks were covered in soft green moss.","imageKeyword":"moss"},
{"word":"acorn","level":1,"definition":"a nut that falls from an oak tree","example":"The squirrel buried the acorn to eat later.","imageKeyword":"acorn"},
{"word":"pinecone","level":1,"definition":"the brown seed holder from a pine tree","example":"She picked up a pinecone from under the big tree.","imageKeyword":"pinecone"},
{"word":"seed","level":1,"definition":"a tiny thing that grows into a plant","example":"She planted a seed and watered it every day.","imageKeyword":"seed sprouting"},
{"word":"crawl","level":1,"definition":"to move on your hands and knees","example":"The baby learned to crawl before he could walk.","imageKeyword":"baby crawling"},
{"word":"leap","level":1,"definition":"to jump far","example":"The frog made a big leap across the pond.","imageKeyword":"leap jump"},
{"word":"skip","level":1,"definition":"to move with little hops and steps","example":"She liked to skip down the path singing a song.","imageKeyword":"girl skipping down sidewalk"},
{"word":"stomp","level":1,"definition":"to step down very hard","example":"He would stomp his feet when he was angry.","imageKeyword":"stomping foot"},
{"word":"tiptoe","level":1,"definition":"to walk very quietly on your toes","example":"She had to tiptoe past the sleeping baby.","imageKeyword":"tiptoe"},
{"word":"march","level":1,"definition":"to walk with big strong steps","example":"The soldiers march in a straight line.","imageKeyword":"marching"},
{"word":"dash","level":1,"definition":"to run very fast","example":"He made a quick dash to the door before it closed.","imageKeyword":"running fast"},
{"word":"chase","level":1,"definition":"to run after something","example":"The dog liked to chase the ball in the yard.","imageKeyword":"dog chasing"},
{"word":"grab","level":1,"definition":"to take something quickly with your hand","example":"She tried to grab the last cookie before her brother.","imageKeyword":"hand grabbing cookie from jar"},
{"word":"toss","level":1,"definition":"to throw something gently","example":"He would toss the ball to his friend.","imageKeyword":"tossing ball"},
{"word":"catch","level":1,"definition":"to take hold of something in the air","example":"She held out her hands to catch the ball.","imageKeyword":"catching ball"},
{"word":"squeeze","level":1,"definition":"to press something tight","example":"He gave his teddy bear a big squeeze.","imageKeyword":"squeeze hug"},
{"word":"stretch","level":1,"definition":"to make your body long","example":"The cat liked to stretch after a nap.","imageKeyword":"cat stretching after nap"},
{"word":"bend","level":1,"definition":"to make something not straight","example":"You need to bend down to pick up the toy.","imageKeyword":"person bending to touch toes"},
{"word":"twist","level":1,"definition":"to turn something around","example":"She had to twist the cap to open the bottle.","imageKeyword":"hands twisting jar lid open"},
{"word":"shake","level":1,"definition":"to move something back and forth fast","example":"He would shake the box to guess what was inside.","imageKeyword":"shaking salt shaker"},
{"word":"stir","level":1,"definition":"to move something around in a circle","example":"She used a spoon to stir the soup.","imageKeyword":"stirring"},
{"word":"pour","level":1,"definition":"to make liquid flow out","example":"Please pour some milk into my cup.","imageKeyword":"pitcher pouring water glass"},
{"word":"spill","level":1,"definition":"to let liquid fall by accident","example":"Be careful not to spill your juice on the table.","imageKeyword":"spilling"},
{"word":"drip","level":1,"definition":"when liquid falls drop by drop","example":"Water started to drip from the leaky roof.","imageKeyword":"dripping water"},
{"word":"splash","level":1,"definition":"to make water fly everywhere","example":"The kids love to splash in the pool.","imageKeyword":"splashing"},
{"word":"float","level":1,"definition":"to stay on top of water","example":"The rubber duck can float in the bathtub.","imageKeyword":"rubber duck floating in bath"},
{"word":"sink","level":1,"definition":"to go down under the water","example":"The heavy rock will sink to the bottom.","imageKeyword":"toy boat sinking in water"},
{"word":"melt","level":1,"definition":"to change from hard to soft or liquid","example":"The ice cream will melt if you leave it in the sun.","imageKeyword":"ice cream melting in sun"},
{"word":"freeze","level":1,"definition":"to get so cold it turns to ice","example":"The water will freeze into ice tonight.","imageKeyword":"freezing ice"},
{"word":"peel","level":1,"definition":"to take the skin off a fruit","example":"She had to peel the banana before eating it.","imageKeyword":"peeling banana"},
{"word":"chop","level":1,"definition":"to cut into pieces","example":"Dad helped chop the vegetables for dinner.","imageKeyword":"chopping"},
{"word":"grate","level":1,"definition":"to rub food on a tool to make tiny pieces","example":"He helped grate the cheese for the pizza.","imageKeyword":"grating cheese"},
{"word":"spread","level":1,"definition":"to put a thin layer on top","example":"She liked to spread butter on her toast.","imageKeyword":"spreading butter"},
{"word":"sprinkle","level":1,"definition":"to drop tiny bits on something","example":"He wanted to sprinkle sugar on his cereal.","imageKeyword":"sprinkling"},
{"word":"scoop","level":1,"definition":"to pick up with a spoon or hands","example":"She used a big spoon to scoop the ice cream.","imageKeyword":"scooping"},
{"word":"whisper","level":1,"definition":"to speak in a soft low voice","example":"She had to whisper, so the baby would not wake up.","imageKeyword":"child whispering in ear"},
{"word":"shout","level":1,"definition":"to say something very loud","example":"He had to shout, so his friend across the field could hear.","imageKeyword":"child cupping hands shouting"},
{"word":"giggle","level":1,"definition":"to laugh in a quiet silly way","example":"The joke made him giggle and cover his mouth.","imageKeyword":"children giggling covering mouths"},
{"word":"howl","level":1,"definition":"to make a long loud cry","example":"The wolf would howl at the moon every night.","imageKeyword":"wolf howling"},
{"word":"bark","level":1,"definition":"the sound a dog makes","example":"The dog would bark when someone knocked on the door.","imageKeyword":"dog barking"},
{"word":"roar","level":1,"definition":"a big loud sound like a lion","example":"The lion opened its mouth to roar.","imageKeyword":"lion roaring"},
{"word":"hum","level":1,"definition":"to make music with your mouth closed","example":"She liked to hum her favorite song while she worked.","imageKeyword":"humming"},
{"word":"clap","level":1,"definition":"to hit your hands together","example":"Everyone began to clap when the show ended.","imageKeyword":"clapping hands"},
{"word":"wave","level":1,"definition":"to move your hand to say hello or bye","example":"She would wave goodbye from the window.","imageKeyword":"waving hand"},
{"word":"nod","level":1,"definition":"to move your head up and down for yes","example":"He gave a nod to show he understood.","imageKeyword":"nodding yes"},
{"word":"peek","level":1,"definition":"to look quickly or secretly","example":"She tried to peek at her birthday present.","imageKeyword":"child peeking around corner"},
{"word":"stare","level":1,"definition":"to look at something for a long time","example":"He could not stop staring at the huge cake.","imageKeyword":"staring"},
{"word":"glance","level":1,"definition":"to look at something very quickly","example":"He took a quick glance at the clock.","imageKeyword":"quick look"},
{"word":"search","level":1,"definition":"to look carefully for something","example":"He had to search everywhere for his lost toy.","imageKeyword":"flashlight searching dark room"},
{"word":"discover","level":1,"definition":"to find something new","example":"She was excited to discover a frog under the log.","imageKeyword":"child finding frog under log"},
{"word":"notice","level":1,"definition":"to see something for the first time","example":"Did you notice the bird sitting on the fence?","imageKeyword":"eye spotting something on ground"},
{"word":"wonder","level":1,"definition":"to think about something you don't know","example":"I wonder what is inside that big box.","imageKeyword":"wondering thinking"},
{"word":"imagine","level":1,"definition":"to make pictures in your mind","example":"Close your eyes and imagine you are flying.","imageKeyword":"child with thought bubble dragon"},
{"word":"pretend","level":1,"definition":"to act like something that is not real","example":"Let's pretend we are pirates on a ship!","imageKeyword":"child pretending to be superhero cape"},
{"word":"promise","level":1,"definition":"to say you will really do something","example":"I promise I will clean my room after dinner.","imageKeyword":"promise pinky"},
{"word":"remind","level":1,"definition":"to help someone recall","example":"Please remind me to bring my book tomorrow.","imageKeyword":"reminder"},
{"word":"forget","level":1,"definition":"to not recall something","example":"Don't forget to pack your lunch!","imageKeyword":"person leaving keys on table"},
{"word":"belong","level":1,"definition":"to be in the right place","example":"These books belong on the top shelf.","imageKeyword":"toy in a box with name tag"},
{"word":"share","level":1,"definition":"to give part of yours to someone","example":"She learned to share her toys with her sister.","imageKeyword":"two kids sharing pizza slice"},
{"word":"trade","level":1,"definition":"to give something and get something back","example":"I will trade my apple for your orange.","imageKeyword":"kids trading lunch snacks"},
{"word":"borrow","level":1,"definition":"to use something and give it back","example":"Can I borrow your pencil? I will return it soon.","imageKeyword":"handing a book to friend"},
{"word":"lend","level":1,"definition":"to let someone use your thing","example":"She was kind to lend me her umbrella.","imageKeyword":"handing pencil to classmate"},
{"word":"gather","level":1,"definition":"to pick up and bring together","example":"Let's gather sticks to build a fort.","imageKeyword":"kids collecting sticks"},
{"word":"collect","level":1,"definition":"to get many of the same thing","example":"He liked to collect shiny rocks from the beach.","imageKeyword":"child collecting seashells bucket"},
{"word":"stack","level":1,"definition":"to put things on top of each other","example":"He liked to stack the blocks as high as he could.","imageKeyword":"stacking blocks"},
{"word":"wrap","level":1,"definition":"to cover something with paper or cloth","example":"She helped wrap the gift in pretty paper.","imageKeyword":"wrapping gift"},
{"word":"unwrap","level":1,"definition":"to take the cover off something","example":"He was so excited to unwrap his birthday present.","imageKeyword":"hands unwrapping birthday present"},
{"word":"tug","level":1,"definition":"to pull hard on something","example":"She had to tug the door hard to open it.","imageKeyword":"tugging pulling"},
{"word":"drag","level":1,"definition":"to pull something heavy along the ground","example":"He had to drag the heavy bag across the floor.","imageKeyword":"child dragging heavy backpack"},
{"word":"shove","level":1,"definition":"to push hard","example":"The wind would shove the door shut.","imageKeyword":"pushing hard"},
{"word":"tuck","level":1,"definition":"to push edges in to make neat","example":"Mom would tuck the blanket around him at bedtime.","imageKeyword":"tucking in"},
{"word":"hang","level":1,"definition":"to put something up so it is not on the ground","example":"Please hang your coat on the hook.","imageKeyword":"hanging coat"},
{"word":"fasten","level":1,"definition":"to close or attach something","example":"Please fasten your seatbelt before the car moves.","imageKeyword":"buckling seatbelt click"},
{"word":"attach","level":1,"definition":"to join one thing to another","example":"He used a clip to attach the paper to the board.","imageKeyword":"hands taping paper to wall"},
{"word":"repair","level":1,"definition":"to fix something broken","example":"Dad can repair the broken chair with glue.","imageKeyword":"hands fixing broken toy"},
{"word":"create","level":1,"definition":"to make something new","example":"She used paint to create a beautiful picture.","imageKeyword":"creating art"},
{"word":"design","level":1,"definition":"to plan what something will look like","example":"He wanted to design his own treehouse.","imageKeyword":"child drawing blueprint"},
{"word":"measure","level":1,"definition":"to find out how big something is","example":"She used a ruler to measure how tall the plant grew.","imageKeyword":"ruler measuring paper"},
{"word":"weigh","level":1,"definition":"to find out how heavy something is","example":"Let's weigh the pumpkin to see how heavy it is.","imageKeyword":"weighing scale"},
{"word":"count","level":1,"definition":"to say numbers to find how many","example":"Can you count how many apples are in the basket?","imageKeyword":"child counting on fingers"},
{"word":"sort","level":1,"definition":"to put things in groups","example":"She helped sort the socks by color.","imageKeyword":"sorting colored blocks into groups"},
{"word":"match","level":1,"definition":"to find two things that are the same","example":"Can you match the baby animal to its father?","imageKeyword":"matching pairs"},
{"word":"deliver","level":1,"definition":"to bring something to someone","example":"The mail carrier will deliver the package today.","imageKeyword":"mailman delivering package door"},
{"word":"fetch","level":1,"definition":"to go get something and bring it back","example":"The dog ran to fetch the stick I threw.","imageKeyword":"dog fetching"},
{"word":"vanish","level":1,"definition":"to disappear suddenly, like magic","example":"The magician made the coin vanish!","imageKeyword":"vanishing magic"},
{"word":"tiny","level":1,"definition":"so small you can barely see it or hold it","example":"The tiny ant carried a crumb ten times its size.","imageKeyword":"tiny ant on finger"},
{"word":"huge","level":1,"definition":"so big it fills up a room or towers over you","example":"The huge elephant was taller than the bus.","imageKeyword":"huge elephant next to car"},
{"word":"enormous","level":1,"definition":"so big you can hardly believe it","example":"The enormous whale made the boat look like a toy.","imageKeyword":"enormous whale next to small boat"},
{"word":"narrow","level":1,"definition":"not very wide","example":"The path was so narrow only one person could walk at a time.","imageKeyword":"narrow path"},
{"word":"wide","level":1,"definition":"going far from side to side","example":"The river was too wide to jump across.","imageKeyword":"wide river"},
{"word":"steep","level":1,"definition":"a hill that goes up fast","example":"The hill was so steep they had to crawl up it.","imageKeyword":"steep hill"},
{"word":"shallow","level":1,"definition":"with water that only reaches your ankles or knees","example":"The water was shallow enough for the little kids to stand in.","imageKeyword":"shallow water"},
{"word":"deep","level":1,"definition":"going far down","example":"The pool was too deep for her to touch the bottom.","imageKeyword":"deep water"},
{"word":"thick","level":1,"definition":"not thin; having a lot from one side to the other","example":"The thick book had over 300 pages.","imageKeyword":"thick book"},
{"word":"thin","level":1,"definition":"not thick; having very little from one side to the other","example":"The ice was too thin to walk on safely.","imageKeyword":"thin ice"},
{"word":"smooth","level":1,"definition":"not bumpy at all","example":"The rock was smooth like a piece of glass.","imageKeyword":"smooth stone"},
{"word":"rough","level":1,"definition":"bumpy and not smooth","example":"The tree bark felt rough under her fingers.","imageKeyword":"rough texture"},
{"word":"sharp","level":1,"definition":"with a point that can cut","example":"Be careful! That knife is very sharp.","imageKeyword":"sharp point"},
{"word":"dull","level":1,"definition":"not sharp at all","example":"The dull scissors could not cut the paper.","imageKeyword":"dull blade"},
{"word":"shiny","level":1,"definition":"bright and reflecting light","example":"The shiny coin sparkled in the sunlight.","imageKeyword":"shiny coin in sunlight"},
{"word":"damp","level":1,"definition":"a little bit wet","example":"The grass was damp from the morning dew.","imageKeyword":"damp"},
{"word":"soaking","level":1,"definition":"completely wet, with water dripping off","example":"He was soaking wet after playing in the rain.","imageKeyword":"soaking wet"},
{"word":"dry","level":1,"definition":"not wet at all","example":"She waited for her hair to get dry after her bath.","imageKeyword":"dry cracked ground"},
{"word":"sticky","level":1,"definition":"something that holds on to your fingers","example":"His hands were sticky from the candy.","imageKeyword":"sticky hands"},
{"word":"slimy","level":1,"definition":"wet and slippery in a yucky way","example":"The slimy slug left a trail on the sidewalk.","imageKeyword":"slimy"},
{"word":"fluffy","level":1,"definition":"soft and light like a cloud","example":"The fluffy kitten looked like a little cotton ball.","imageKeyword":"fluffy"},
{"word":"fuzzy","level":1,"definition":"covered in soft short hair","example":"The fuzzy peach tickled his lip.","imageKeyword":"fuzzy"},
{"word":"cozy","level":1,"definition":"warm and comfortable","example":"The cozy bed made her want to stay asleep.","imageKeyword":"cozy fireplace room"},
{"word":"chilly","level":1,"definition":"a little cold","example":"The chilly wind made her wish she had a jacket.","imageKeyword":"chilly"},
{"word":"freezing","level":1,"definition":"so cold like ice","example":"The water was freezing so no one wanted to swim.","imageKeyword":"freezing cold"},
{"word":"boiling","level":1,"definition":"so hot with lots of bubbles","example":"The boiling water was too hot to touch.","imageKeyword":"boiling water"},
{"word":"warm","level":1,"definition":"a nice heat that feels good","example":"The warm sun felt nice on her face.","imageKeyword":"warm sun"},
{"word":"fierce","level":1,"definition":"dangerously strong and ready to attack","example":"The fierce lion roared and showed its sharp teeth.","imageKeyword":"fierce tiger"},
{"word":"gentle","level":1,"definition":"soft and careful","example":"He was gentle when he held the baby bird.","imageKeyword":"gentle hands"},
{"word":"brave","level":1,"definition":"not afraid to do scary things","example":"The brave knight went into the dark cave.","imageKeyword":"brave knight"},
{"word":"shy","level":1,"definition":"afraid to talk to new people","example":"The shy girl hid behind her mother.","imageKeyword":"shy child"},
{"word":"proud","level":1,"definition":"happy about something you did well","example":"She felt proud when she finished the hard puzzle.","imageKeyword":"proud child trophy"},
{"word":"curious","level":1,"definition":"wanting to know about things","example":"The curious cat peeked inside the open box.","imageKeyword":"curious cat"},
{"word":"grumpy","level":1,"definition":"in a bad mood","example":"He was grumpy because he did not sleep well.","imageKeyword":"grumpy face"},
{"word":"cheerful","level":1,"definition":"happy and smiling","example":"The cheerful girl sang a song on the way to school.","imageKeyword":"cheerful"},
{"word":"lonely","level":1,"definition":"sad because you are alone","example":"The lonely puppy sat by the door waiting for someone to play.","imageKeyword":"lonely"},
{"word":"calm","level":1,"definition":"quiet and not upset","example":"The lake was calm and still like a mirror.","imageKeyword":"calm water"},
{"word":"wild","level":1,"definition":"not tame, living free in nature","example":"The wild horse ran free across the plains.","imageKeyword":"wild horse"},
{"word":"tame","level":1,"definition":"friendly and used to people","example":"The tame rabbit let the children pet it.","imageKeyword":"tame pet"},
{"word":"plain","level":1,"definition":"not fancy, with nothing on it","example":"He wanted a plain white T-shirt with no picture.","imageKeyword":"plain white t-shirt"},
{"word":"fancy","level":1,"definition":"having a lot of pretty things on it","example":"She wore a fancy dress with sparkles to the party.","imageKeyword":"fancy dress"},
{"word":"ripe","level":1,"definition":"ready to eat (for fruit)","example":"The ripe banana was yellow and sweet.","imageKeyword":"ripe fruit"},
{"word":"rotten","level":1,"definition":"old and bad to eat","example":"The rotten apple was brown and smelled terrible.","imageKeyword":"rotten apple"},
{"word":"fresh","level":1,"definition":"just made or picked, not old","example":"The fresh bread smelled wonderful from the oven.","imageKeyword":"fresh bread"},
{"word":"stale","level":1,"definition":"old and not fresh anymore","example":"The stale crackers were not crunchy anymore.","imageKeyword":"stale food"},
{"word":"bitter","level":1,"definition":"a strong taste that is not sweet","example":"The dark chocolate tasted bitter to her.","imageKeyword":"bitter taste"},
{"word":"sour","level":1,"definition":"a sharp taste like lemon","example":"The sour candy made her face scrunch up.","imageKeyword":"sour face"},
{"word":"salty","level":1,"definition":"tasting like salt","example":"The ocean water was too salty to drink.","imageKeyword":"salty"},
{"word":"juicy","level":1,"definition":"full of liquid inside","example":"The juicy orange dripped down his chin.","imageKeyword":"juicy orange"},
{"word":"crunchy","level":1,"definition":"making a loud sound when you bite","example":"The crunchy carrot snapped when she bit it.","imageKeyword":"crunchy"},
{"word":"creamy","level":1,"definition":"smooth and soft like cream","example":"The creamy soup was thick and warm.","imageKeyword":"creamy"},
{"word":"silent","level":1,"definition":"making no sound at all","example":"The house was silent because everyone was asleep.","imageKeyword":"silent quiet"},
{"word":"loud","level":1,"definition":"making a lot of noise","example":"The loud music made it hard to talk.","imageKeyword":"loud"},
{"word":"hollow","level":1,"definition":"with nothing in it at all","example":"The hollow log made a drum sound when she hit it.","imageKeyword":"hollow log"},
{"word":"solid","level":1,"definition":"hard and not hollow","example":"The solid rock was too heavy to lift.","imageKeyword":"solid rock"},
{"word":"loose","level":1,"definition":"not tight","example":"His loose tooth wiggled when he touched it.","imageKeyword":"loose tooth"},
{"word":"tight","level":1,"definition":"fitting very close, hard to move","example":"The lid was on so tight he could not open the jar.","imageKeyword":"tight lid"},
{"word":"crooked","level":1,"definition":"not straight, bent","example":"The old fence was crooked and leaning to one side.","imageKeyword":"crooked leaning fence"},
{"word":"straight","level":1,"definition":"going one way without bending","example":"She drew a straight line with her ruler.","imageKeyword":"straight line"},
{"word":"crowded","level":1,"definition":"full of too many people or things","example":"The bus was so crowded there was no place to sit.","imageKeyword":"crowded"},
{"word":"empty","level":1,"definition":"with nothing inside","example":"The empty jar had no cookies left.","imageKeyword":"empty jar"},
{"word":"whole","level":1,"definition":"all of it, nothing missing","example":"He ate the whole pizza by himself!","imageKeyword":"whole complete"},
{"word":"spare","level":1,"definition":"extra, in case you need it","example":"Mom keeps a spare key under the mat.","imageKeyword":"spare key"},
{"word":"certain","level":1,"definition":"you know it is true for sure","example":"I am certain I left my bag on the chair.","imageKeyword":"confident child pointing"},
{"word":"strange","level":1,"definition":"odd or not like what you thought","example":"She heard a strange noise coming from the closet.","imageKeyword":"strange odd"},
{"word":"wonderful","level":1,"definition":"very good and nice","example":"The birthday party was wonderful!","imageKeyword":"wonderful"},
{"word":"terrible","level":1,"definition":"so bad it makes you upset or scared","example":"The terrible storm knocked down many trees.","imageKeyword":"terrible storm damage"},
{"word":"perfect","level":1,"definition":"nothing wrong at all","example":"She drew a perfect circle without any bumps.","imageKeyword":"perfect circle"},
{"word":"ugly","level":1,"definition":"not nice to look at","example":"The ugly duckling grew into a beautiful swan.","imageKeyword":"ugly duckling"},
{"word":"beautiful","level":1,"definition":"so lovely it makes you stop and stare","example":"The sunset painted the sky in beautiful colors.","imageKeyword":"beautiful sunset"},
{"word":"clever","level":1,"definition":"smart and good at thinking","example":"The clever fox found a way out of the trap.","imageKeyword":"clever fox"},
{"word":"foolish","level":1,"definition":"not smart, silly in a bad way","example":"It was foolish to go outside without a coat in the snow.","imageKeyword":"person walking in rain no umbrella"},
{"word":"greedy","level":1,"definition":"wanting too much for yourself","example":"The greedy boy took all the cookies and shared none.","imageKeyword":"greedy"},
{"word":"generous","level":1,"definition":"happy to give to others","example":"He was generous and shared his lunch with his friend.","imageKeyword":"generous sharing"},
{"word":"patient","level":1,"definition":"able to wait and stay calm","example":"Be patient — your turn will come soon.","imageKeyword":"patient waiting"},
{"word":"stubborn","level":1,"definition":"will not change your mind","example":"The stubborn mule would not move no matter what.","imageKeyword":"stubborn mule"},
{"word":"lazy","level":1,"definition":"not wanting to work or move","example":"The lazy cat slept all day in the sunny spot.","imageKeyword":"lazy cat"},
{"word":"busy","level":1,"definition":"doing many things with no free time","example":"The bees were very busy making honey.","imageKeyword":"busy bee"},
{"word":"clumsy","level":1,"definition":"bumping into things a lot","example":"The clumsy puppy tripped over its own feet.","imageKeyword":"clumsy"},
{"word":"graceful","level":1,"definition":"moving in a pretty smooth way","example":"The graceful dancer spun without falling.","imageKeyword":"graceful dancer"},
{"word":"quickly","level":1,"definition":"in a fast way","example":"She quickly grabbed her bag and ran to school.","imageKeyword":"quickly fast"},
{"word":"slowly","level":1,"definition":"in a not-fast way","example":"The turtle walked slowly across the road.","imageKeyword":"slowly turtle"},
{"word":"quietly","level":1,"definition":"without making noise","example":"She quietly closed the door, so the baby would not wake.","imageKeyword":"finger over lips shush"},
{"word":"loudly","level":1,"definition":"with a lot of noise","example":"The baby cried loudly in the middle of the night.","imageKeyword":"loudly"},
{"word":"gently","level":1,"definition":"in a soft careful way","example":"She gently placed the egg in the basket.","imageKeyword":"hand gently petting kitten"},
{"word":"suddenly","level":1,"definition":"it came out of nowhere with no warning","example":"Suddenly the lights went out, and the room was dark.","imageKeyword":"suddenly surprise"},
{"word":"already","level":1,"definition":"it was done or it happened before now","example":"She was surprised he had already finished his homework.","imageKeyword":"homework finished on desk"},
{"word":"almost","level":1,"definition":"very close but not quite","example":"He almost caught the ball, but it slipped away.","imageKeyword":"hand almost catching ball"},
{"word":"barely","level":1,"definition":"only just, by a tiny bit","example":"He could barely reach the top shelf on his toes.","imageKeyword":"barely reaching"},
{"word":"perhaps","level":1,"definition":"maybe, it might happen","example":"Perhaps we will go to the park if it stops raining.","imageKeyword":"maybe perhaps"},
{"word":"exactly","level":1,"definition":"just right; not more or less","example":"That is exactly what I was looking for!","imageKeyword":"puzzle piece fitting perfectly"},
{"word":"instead","level":1,"definition":"in place of something else","example":"It rained, so we played inside instead.","imageKeyword":"apple chosen instead of candy"},
{"word":"anyway","level":1,"definition":"even so, no matter what","example":"It was raining, but she went outside anyway.","imageKeyword":"girl walking in rain smiling"},
{"word":"forever","level":1,"definition":"for all time, never ending","example":"I wish summer could last forever.","imageKeyword":"stars in night sky"},
{"word":"apart","level":1,"definition":"away from each other","example":"The two friends lived far apart but still wrote letters.","imageKeyword":"apart separate"},
{"word":"together","level":1,"definition":"with each other","example":"The kids played together in the sandbox.","imageKeyword":"friends holding hands circle"},
{"word":"forward","level":1,"definition":"toward the front","example":"Take one step forward and two steps back.","imageKeyword":"arrow pointing forward"},
{"word":"backward","level":1,"definition":"toward the back","example":"She counted backward from ten to one.","imageKeyword":"person walking backward"},
{"word":"sideways","level":1,"definition":"to the left or right","example":"The crab walked sideways across the sand.","imageKeyword":"sideways crab"},
{"word":"beneath","level":1,"definition":"right below it","example":"The cat hid beneath the bed.","imageKeyword":"beneath under"},
{"word":"above","level":1,"definition":"higher than something","example":"The bird flew above the trees.","imageKeyword":"bird flying above house"},
{"word":"below","level":1,"definition":"lower than something","example":"The fish swam below the boat.","imageKeyword":"below under"},
{"word":"beside","level":1,"definition":"next to","example":"She sat beside her best friend.","imageKeyword":"two friends sitting on bench"},
{"word":"between","level":1,"definition":"in the middle of two things","example":"The ball rolled between the two chairs.","imageKeyword":"cat sitting between two boxes"},
{"word":"among","level":1,"definition":"in a group of many things","example":"He found his toy among all the others in the box.","imageKeyword":"toy in box full of toys"},
{"word":"toward","level":1,"definition":"in the direction of","example":"The puppy ran toward its owner.","imageKeyword":"dog running toward owner"},
{"word":"against","level":1,"definition":"touching and leaning on","example":"He leaned against the wall and waited for his friend.","imageKeyword":"against wall"},
{"word":"through","level":1,"definition":"from one side to the other","example":"The train went through the long tunnel.","imageKeyword":"through tunnel"},
{"word":"across","level":1,"definition":"from one side to the other side","example":"She swam across the pool to the other end.","imageKeyword":"bridge going across river"},
{"word":"along","level":1,"definition":"following the edge or line of","example":"They walked along the path by the river.","imageKeyword":"along path"},
{"word":"around","level":1,"definition":"in a circle","example":"The dog ran around the tree three times.","imageKeyword":"around circle"},
{"word":"beyond","level":1,"definition":"past, farther away than","example":"The park is just beyond those tall trees.","imageKeyword":"park behind trees"},
{"word":"during","level":1,"definition":"at the same time as something else","example":"She fell asleep during the movie.","imageKeyword":"clock showing time passing"},
{"word":"until","level":1,"definition":"up to the time that","example":"Wait here until I come back.","imageKeyword":"until waiting"},
{"word":"since","level":1,"definition":"from that time to now","example":"She has been happy since she got the puppy.","imageKeyword":"calendar with days marked"},
{"word":"although","level":1,"definition":"even though","example":"Although it was cold, he did not wear a jacket.","imageKeyword":"cold without jacket"},
{"word":"whether","level":1,"definition":"if one thing or another","example":"I don't know whether to bring a coat or not.","imageKeyword":"child holding coat looking at sky"},
{"word":"unless","level":1,"definition":"only if not","example":"You can't go outside unless you finish your food.","imageKeyword":"child eating dinner before going outside"},
{"word":"while","level":1,"definition":"at the same time as","example":"She read a book while she waited for the bus.","imageKeyword":"while"},
{"word":"besides","level":1,"definition":"in addition to that, also","example":"Besides apples, she also likes grapes.","imageKeyword":"apples and grapes together"},
{"word":"within","level":1,"definition":"inside","example":"Stay within the lines when you color.","imageKeyword":"coloring inside the lines"},
{"word":"without","level":1,"definition":"not having","example":"He went to school without his lunch box.","imageKeyword":"empty lunchbox"},
{"word":"throughout","level":1,"definition":"in every part of","example":"Flowers grew throughout the whole garden.","imageKeyword":"flowers in every part of garden"},
{"word":"upon","level":1,"definition":"on top of (used in stories)","example":"Once upon a time, there was a little bear.","imageKeyword":"castle upon a hill"},
{"word":"pick up","level":1,"definition":"to lift something from the ground","example":"Please pick up your toys from the floor.","imageKeyword":"picking up"},
{"word":"put down","level":1,"definition":"to set something on a surface","example":"She put down the heavy bag on the table.","imageKeyword":"putting down"},
{"word":"look at","level":1,"definition":"to turn your eyes toward something","example":"Come look at this funny picture!","imageKeyword":"looking at"},
{"word":"come back","level":1,"definition":"to return to where you were","example":"The dog always comes back when I call his name.","imageKeyword":"coming back"},
{"word":"sit down","level":1,"definition":"to put your bottom on a chair","example":"Please sit down, so the movie can start.","imageKeyword":"sitting down"},
{"word":"stand up","level":1,"definition":"to get on your feet","example":"Everyone stand up when the teacher walks in.","imageKeyword":"standing up"},
{"word":"wake up","level":1,"definition":"to stop sleeping","example":"He woke up when the alarm clock rang.","imageKeyword":"waking up"},
{"word":"give up","level":1,"definition":"to stop trying","example":"Don't give up! You can do it if you keep trying.","imageKeyword":"giving up"},
{"word":"find out","level":1,"definition":"to learn or discover","example":"I want to find out what is in that box!","imageKeyword":"finding out"},
{"word":"turn off","level":1,"definition":"to make something stop working","example":"Please turn off the light before you sleep.","imageKeyword":"turning off"},
{"word":"turn on","level":1,"definition":"to make something start working","example":"Can you turn on the TV? My show is starting.","imageKeyword":"turning on"},
{"word":"fall down","level":1,"definition":"to drop to the ground","example":"The baby learned to walk but would fall down sometimes.","imageKeyword":"falling down"},
{"word":"get up","level":1,"definition":"to rise from bed or the floor","example":"It is time to get up and get ready for school.","imageKeyword":"getting up"},
{"word":"look out","level":1,"definition":"to be careful of danger","example":"Look out! There is a car coming!","imageKeyword":"look out warning"},
{"word":"hold on","level":1,"definition":"to grip tight or to wait","example":"Hold on tight, so you don't fall off the swing.","imageKeyword":"holding on"},
{"word":"clean up","level":1,"definition":"to make a place neat and tidy","example":"Let's clean up the mess before Mom gets home.","imageKeyword":"cleaning up"},
{"word":"hurry up","level":1,"definition":"to go faster","example":"Hurry up! The bus is about to leave!","imageKeyword":"person running to catch bus"},
{"word":"calm down","level":1,"definition":"to become less upset","example":"Take a deep breath and calm down.","imageKeyword":"calming down"},
{"word":"try on","level":1,"definition":"to put clothes on to see if they fit","example":"She wanted to try on the new shoes before buying them.","imageKeyword":"trying on"},
{"word":"throw away","level":1,"definition":"to put in the trash","example":"Please throw away the empty wrapper.","imageKeyword":"throwing away"},
{"word":"run out","level":1,"definition":"to have none left","example":"We ran out of milk, so Dad went to the store.","imageKeyword":"running out"},
{"word":"come in","level":1,"definition":"to enter a room or building","example":"Come in! It is too cold to stand outside.","imageKeyword":"coming in"},
{"word":"go away","level":1,"definition":"to leave, to move far from here","example":"The dark clouds will go away, and the sun will come out.","imageKeyword":"going away"},
{"word":"show off","level":1,"definition":"to try to impress people","example":"He liked to show off by doing tricks on his bike.","imageKeyword":"showing off"},
{"word":"figure out","level":1,"definition":"to solve or understand something","example":"She tried to figure out the answer to the riddle.","imageKeyword":"figuring out"},
{"word":"excited","level":1,"definition":"so happy you can barely wait","example":"He was excited about going to the zoo tomorrow.","imageKeyword":"excited"},
{"word":"nervous","level":1,"definition":"worried about what will happen","example":"He felt nervous before his first day of school.","imageKeyword":"nervous"},
{"word":"frightened","level":1,"definition":"so scared your heart pounds and you want to run","example":"The frightened rabbit ran when it heard the loud noise.","imageKeyword":"frightened scared"},
{"word":"surprised","level":1,"definition":"something you did not expect happened","example":"She was surprised to find a gift on her desk.","imageKeyword":"surprised"},
{"word":"confused","level":1,"definition":"unable to understand what is happening","example":"He was confused because the directions made no sense.","imageKeyword":"confused person with question marks"},
{"word":"disappointed","level":1,"definition":"sad because something did not happen the way you wanted","example":"She was disappointed when the trip was canceled.","imageKeyword":"disappointed"},
{"word":"frustrated","level":1,"definition":"upset because something is hard","example":"He got frustrated when the puzzle piece would not fit.","imageKeyword":"frustrated"},
{"word":"jealous","level":1,"definition":"wanting what someone else has","example":"She was jealous of her friend's new bike.","imageKeyword":"jealous"},
{"word":"embarrassed","level":1,"definition":"feeling silly in front of others","example":"He was embarrassed when he tripped in front of everyone.","imageKeyword":"embarrassed"},
{"word":"worried","level":1,"definition":"thinking bad things might happen","example":"He was worried his lost cat would not come home.","imageKeyword":"worried"},
{"word":"grateful","level":1,"definition":"glad and thankful for what you got","example":"She was grateful her friend helped her carry the books.","imageKeyword":"grateful thankful"},
{"word":"annoyed","level":1,"definition":"a bit mad about a small thing","example":"He was annoyed that his sister kept poking him.","imageKeyword":"annoyed face eye roll"},
{"word":"bored","level":1,"definition":"not interested, nothing to do","example":"On rainy days with nothing to do, she felt bored.","imageKeyword":"bored child staring at ceiling"},
{"word":"amazed","level":1,"definition":"so surprised in a good way","example":"She was amazed by the magic trick.","imageKeyword":"amazed"},
{"word":"terrified","level":1,"definition":"so scared you cannot move","example":"He was terrified of the thunder during the storm.","imageKeyword":"terrified"},
{"word":"furious","level":1,"definition":"so mad you want to yell","example":"He was furious when someone broke his favorite toy.","imageKeyword":"furious angry"},
{"word":"miserable","level":1,"definition":"so sad it hurts inside","example":"He felt miserable with a cold, and a sore throat.","imageKeyword":"miserable sick"},
{"word":"relieved","level":1,"definition":"happy that something bad did not happen","example":"She was relieved to find her lost homework in her bag.","imageKeyword":"relieved"},
{"word":"peaceful","level":1,"definition":"calm and quiet with no problems","example":"The sleeping baby looked so peaceful.","imageKeyword":"peaceful"},
{"word":"comfortable","level":1,"definition":"feeling good, not in pain","example":"The big soft chair was very comfortable.","imageKeyword":"comfortable"},
{"word":"uncomfortable","level":1,"definition":"not feeling good in your body","example":"The hard bench was uncomfortable to sit on.","imageKeyword":"person sitting on hard rock"},
{"word":"exhausted","level":1,"definition":"so tired you can barely move","example":"After running all day, she was exhausted.","imageKeyword":"exhausted tired"},
{"word":"delighted","level":1,"definition":"so happy you want to jump up and down","example":"She was delighted when she saw the surprise party.","imageKeyword":"delighted"},
{"word":"gloomy","level":1,"definition":"dark and sad feeling","example":"The rainy day made everyone feel gloomy.","imageKeyword":"gloomy"},
{"word":"hopeful","level":1,"definition":"feeling like good things will happen","example":"He was hopeful that tomorrow would be a sunny day.","imageKeyword":"child wishing on star"},
{"word":"cranky","level":1,"definition":"grouchy and easy to upset","example":"Babies get cranky when they are tired and hungry.","imageKeyword":"cranky"},
{"word":"content","level":1,"definition":"happy with what you have","example":"The cat looked content sleeping in the warm sun.","imageKeyword":"content happy"},
{"word":"eager","level":1,"definition":"really wanting to do something","example":"The eager puppy waited by the door for its walk.","imageKeyword":"excited dog waiting at door"},
{"word":"homesick","level":1,"definition":"missing your home when you are away","example":"At camp, she felt homesick and missed her family.","imageKeyword":"child looking out window sad"},
{"word":"ashamed","level":1,"definition":"feeling bad about something you did wrong","example":"He was ashamed that he lied to his mom.","imageKeyword":"child hiding face ashamed"},
{"word":"before","level":1,"definition":"earlier in time; at a point in the past","example":"Wash your hands before you eat dinner.","imageKeyword":"before first"},
{"word":"after","level":1,"definition":"it comes next, not first","example":"We will have cake after we sing happy birthday.","imageKeyword":"after next"},
{"word":"next","level":1,"definition":"the one that comes right after","example":"What should we do next?","imageKeyword":"arrow pointing to next door"},
{"word":"then","level":1,"definition":"after that","example":"First she put on her shoes, then she went outside.","imageKeyword":"then after"},
{"word":"finally","level":1,"definition":"at last, after a long wait","example":"After trying many times, she finally did it!","imageKeyword":"finish line celebration"},
{"word":"meanwhile","level":1,"definition":"during the same time, somewhere else","example":"He was at school. Meanwhile, his dad baked a cake at home.","imageKeyword":"boy at school and dad baking at home split screen"},
{"word":"soon","level":1,"definition":"in a short time from now","example":"The bus will be here soon.","imageKeyword":"soon"},
{"word":"later","level":1,"definition":"after some time passes","example":"I will clean my room later.","imageKeyword":"clock hands moving forward"},
{"word":"early","level":1,"definition":"sooner than the set time","example":"She woke up early to watch the sunrise.","imageKeyword":"early morning"},
{"word":"late","level":1,"definition":"past the time it should be","example":"He was late for school because he overslept.","imageKeyword":"person rushing clock showing late"},
{"word":"beginning","level":1,"definition":"the start of something","example":"At the beginning of the story, a boy found a map.","imageKeyword":"beginning start"},
{"word":"middle","level":1,"definition":"the center part, not start or end","example":"In the middle of the night, she heard a noise.","imageKeyword":"middle center"},
{"word":"ending","level":1,"definition":"the last part of something","example":"The ending of the movie made everyone cry.","imageKeyword":"book closing last page"},
{"word":"moment","level":1,"definition":"a very short bit of time","example":"Wait just a moment while I tie my shoe.","imageKeyword":"moment"},
{"word":"sudden","level":1,"definition":"with no sign it was coming","example":"There was a sudden crash of thunder.","imageKeyword":"lightning bolt surprise"},
{"word":"recent","level":1,"definition":"just a short time ago","example":"In her recent painting, she drew a rainbow.","imageKeyword":"fresh newspaper today date"},
{"word":"daily","level":1,"definition":"happening every single day","example":"Brushing your teeth is a daily habit.","imageKeyword":"daily routine"},
{"word":"weekly","level":1,"definition":"happening once a week","example":"They had a weekly trip to the library.","imageKeyword":"weekly calendar"},
{"word":"whenever","level":1,"definition":"every time that","example":"Whenever it rains, the frogs come out.","imageKeyword":"frogs in rain puddles"},
{"word":"once","level":1,"definition":"one time","example":"He visited the ocean once and never forgot it.","imageKeyword":"finger holding up number one"},
{"word":"twice","level":1,"definition":"two times","example":"He knocked on the door twice.","imageKeyword":"twice two times"},
{"word":"often","level":1,"definition":"many times, again and again","example":"She often read books before bed.","imageKeyword":"often frequently"},
{"word":"seldom","level":1,"definition":"almost never happening","example":"Snow seldom falls in this warm town.","imageKeyword":"seldom rarely"},
{"word":"nowadays","level":1,"definition":"in the time we live in now","example":"Nowadays, most kids use computers at school.","imageKeyword":"nowadays modern"},
{"word":"eventually","level":1,"definition":"after a long time","example":"If you keep trying, you will eventually learn to ride a bike.","imageKeyword":"seed growing into flower stages"},
{"word":"dozen","level":1,"definition":"twelve of something","example":"Mom bought a dozen eggs at the store.","imageKeyword":"dozen eggs"},
{"word":"half","level":1,"definition":"one of two equal parts","example":"She ate half the sandwich and saved the rest.","imageKeyword":"half"},
{"word":"pair","level":1,"definition":"two things that go together","example":"He bought a new pair of shoes.","imageKeyword":"pair shoes"},
{"word":"entire","level":1,"definition":"all something from start to finish","example":"She read the entire book in one afternoon.","imageKeyword":"entire complete"},
{"word":"double","level":1,"definition":"two times as much","example":"She asked for a double scoop of ice cream.","imageKeyword":"two identical cookies side by side"},
{"word":"single","level":1,"definition":"only one","example":"There was a single flower growing in the crack.","imageKeyword":"single one"},
{"word":"plenty","level":1,"definition":"more than enough","example":"There is plenty of food for everyone.","imageKeyword":"overflowing fruit basket"},
{"word":"several","level":1,"definition":"more than two but not a lot","example":"She read several books over the weekend.","imageKeyword":"several few"},
{"word":"few","level":1,"definition":"a small number","example":"Only a few kids came to school on the snowy day.","imageKeyword":"three marbles in empty jar"},
{"word":"many","level":1,"definition":"a large number","example":"There were many stars in the sky that night.","imageKeyword":"many stars"},
{"word":"none","level":1,"definition":"not any, zero","example":"He looked in the cookie jar, but none were left.","imageKeyword":"none empty"},
{"word":"bunch","level":1,"definition":"a group of things together","example":"He picked a bunch of flowers for his mom.","imageKeyword":"bunch flowers"},
{"word":"pile","level":1,"definition":"things put on top of each other","example":"There was a pile of leaves in the yard.","imageKeyword":"pile leaves"},
{"word":"heap","level":1,"definition":"a big messy pile","example":"His dirty clothes made a heap on the floor.","imageKeyword":"heap pile"},
{"word":"piece","level":1,"definition":"one part of something bigger","example":"Can I have one piece of cake, please?","imageKeyword":"piece cake"},
{"word":"portion","level":1,"definition":"the amount of food for one person","example":"Each child got an equal portion of the pie.","imageKeyword":"portion serving"},
{"word":"amount","level":1,"definition":"how much of something there is","example":"A small amount of sugar makes the tea sweet.","imageKeyword":"pile of coins"},
{"word":"total","level":1,"definition":"all things added together","example":"The total number of students in class is twenty.","imageKeyword":"counting all fingers"},
{"word":"extra","level":1,"definition":"more than what is needed","example":"She packed an extra sandwich in case her friend forgot lunch.","imageKeyword":"extra cookie on plate"},
{"word":"enough","level":1,"definition":"as much as you need","example":"Do we have enough chairs for everyone?","imageKeyword":"glass filled exactly to top"},
{"word":"less","level":1,"definition":"a smaller amount","example":"She used less sugar in her tea today.","imageKeyword":"half empty glass"},
{"word":"more","level":1,"definition":"a bigger amount","example":"Can I have more juice, please?","imageKeyword":"overflowing cookie jar"},
{"word":"quarter","level":1,"definition":"one of four equal parts","example":"She ate a quarter of the pizza and saved the rest.","imageKeyword":"quarter fourth"},
{"word":"equal","level":1,"definition":"the same size or amount","example":"Make sure both pieces are equal.","imageKeyword":"equal same"},
{"word":"average","level":1,"definition":"not too much, not too little, in the middle","example":"It was an average day with nothing special happening.","imageKeyword":"medium sized cup between big and small"},
{"word":"shadow","level":1,"definition":"a dark shape made when something blocks light","example":"His shadow was very long in the afternoon sun.","imageKeyword":"shadow"},
{"word":"echo","level":1,"definition":"a sound that bounces back to you","example":"He shouted in the cave and heard his echo come back.","imageKeyword":"echo cave"},
{"word":"secret","level":1,"definition":"something only you know","example":"She whispered a secret into her friend's ear.","imageKeyword":"secret whisper"},
{"word":"surprise","level":1,"definition":"something you did not expect","example":"The birthday party was a big surprise!","imageKeyword":"surprise party"},
{"word":"mistake","level":1,"definition":"something you did wrong","example":"Everyone makes a mistake sometimes.","imageKeyword":"mistake error"},
{"word":"adventure","level":1,"definition":"an exciting trip or event","example":"Going into the dark cave was a real adventure.","imageKeyword":"adventure"},
{"word":"treasure","level":1,"definition":"something very valuable","example":"The pirates buried the treasure on the island.","imageKeyword":"treasure chest"},
{"word":"journey","level":1,"definition":"a long trip from one place to another","example":"The journey to grandma's house took three hours.","imageKeyword":"journey trip"},
{"word":"village","level":1,"definition":"a very small town","example":"The tiny village had only ten houses.","imageKeyword":"village"},
{"word":"dock","level":1,"definition":"a platform where boats are tied up","example":"They walked along the dock and looked at the boats.","imageKeyword":"boat dock"},
{"word":"crowd","level":1,"definition":"a large group of people","example":"A big crowd gathered to watch the parade.","imageKeyword":"crowd people"},
{"word":"trail","level":1,"definition":"a path through the woods","example":"They followed the trail deep into the forest.","imageKeyword":"trail path"},
{"word":"footprint","level":1,"definition":"the mark your foot makes","example":"She saw a footprint in the snow and followed it.","imageKeyword":"footprint"},
{"word":"pattern","level":1,"definition":"a design that repeats","example":"The zebra has a black and white stripe pattern.","imageKeyword":"pattern stripes"},
{"word":"riddle","level":1,"definition":"a tricky question for fun","example":"Can you solve this riddle?","imageKeyword":"riddle puzzle"},
{"word":"poem","level":1,"definition":"words that sound nice together","example":"She wrote a poem about her cat.","imageKeyword":"poem"},
{"word":"tale","level":1,"definition":"a story","example":"Grandpa told us a tale about a magic fish.","imageKeyword":"tale story"},
{"word":"legend","level":1,"definition":"a very old story that may or may not be true","example":"The legend says a dragon lived in that mountain.","imageKeyword":"legend dragon"},
{"word":"character","level":1,"definition":"a person or animal in a story","example":"My favorite character in the book is the clever fox.","imageKeyword":"story character"},
{"word":"chapter","level":1,"definition":"one part of a book","example":"We read one chapter of the book every night.","imageKeyword":"book chapter"},
{"word":"title","level":1,"definition":"the name of a book or story","example":"The title of the book was printed in big letters.","imageKeyword":"book title"},
{"word":"author","level":1,"definition":"the person who writes a book","example":"The author wrote my favorite story about dragons.","imageKeyword":"author writer"},
{"word":"paw","level":1,"definition":"an animal's foot","example":"The dog lifted its paw and shook my hand.","imageKeyword":"paw"},
{"word":"claw","level":1,"definition":"the sharp nail on an animal's foot","example":"The cat used its claw to climb the tree.","imageKeyword":"claw"},
{"word":"feather","level":1,"definition":"the soft covering on a bird","example":"A blue feather floated down from the sky.","imageKeyword":"feather"},
{"word":"fur","level":1,"definition":"the soft hair on an animal","example":"The rabbit's fur was as soft as a cloud.","imageKeyword":"fur"},
{"word":"scale","level":1,"definition":"a flat hard piece on a fish's body","example":"The fish's scale sparkled silver in the water.","imageKeyword":"fish scale"},
{"word":"wing","level":1,"definition":"the body part a bird uses to fly","example":"The bird spread its wing and took off.","imageKeyword":"bird wing"},
{"word":"beak","level":1,"definition":"the hard mouth part of a bird","example":"The bird used its beak to crack the seed.","imageKeyword":"beak"},
{"word":"nest","level":1,"definition":"a bird's home made of sticks","example":"Three eggs sat in the nest on the branch.","imageKeyword":"bird nest"},
{"word":"hive","level":1,"definition":"where bees live and make honey","example":"Hundreds of bees buzzed around the hive.","imageKeyword":"beehive"},
{"word":"den","level":1,"definition":"a wild animal's home","example":"The fox went into its den to sleep.","imageKeyword":"fox den"},
{"word":"burrow","level":1,"definition":"a hole in the ground where an animal lives","example":"The rabbit disappeared into its burrow.","imageKeyword":"rabbit burrow"},
{"word":"trap","level":1,"definition":"something used to catch animals","example":"The mouse walked right into the trap.","imageKeyword":"mouse trap"},
{"word":"leash","level":1,"definition":"a rope or strap for walking a dog","example":"He held the leash tight, so the dog would not run away.","imageKeyword":"dog leash"},
{"word":"tag","level":1,"definition":"a small label with words on it","example":"The tag on her shirt said her name.","imageKeyword":"name tag"},
{"word":"whisker","level":1,"definition":"long hair on a cat's face","example":"The cat's whisker twitched when it smelled the fish.","imageKeyword":"cat whisker"},
{"word":"tail","level":1,"definition":"the long part at the back of an animal","example":"The happy dog wagged its tail.","imageKeyword":"wagging tail"},
{"word":"hoof","level":1,"definition":"the hard bottom of a horse's foot","example":"The horse's hoof clip-clopped on the road.","imageKeyword":"horse hoof"},
{"word":"mane","level":1,"definition":"long hair on a horse's or lion's neck","example":"The lion's mane blew in the wind.","imageKeyword":"lion mane"},
{"word":"flock","level":1,"definition":"a group of birds","example":"A flock of geese flew over the house.","imageKeyword":"flock birds"},
{"word":"herd","level":1,"definition":"a group of large animals together","example":"A herd of cows walked across the field.","imageKeyword":"herd cows"},
{"word":"pack","level":1,"definition":"a group of wolves or dogs","example":"The pack of wolves hunted together.","imageKeyword":"wolf pack"},
{"word":"droplet","level":1,"definition":"a very small drop of water","example":"A droplet of rain landed on her nose.","imageKeyword":"water droplet"},
{"word":"ripple","level":1,"definition":"a small wave on water","example":"The stone made a ripple when it hit the lake.","imageKeyword":"water ripple"},
{"word":"bubble","level":1,"definition":"a ball of air in water or soap","example":"She blew a big bubble with her bubble wand.","imageKeyword":"soap bubble"},
{"word":"flame","level":1,"definition":"the bright burning part of a fire","example":"The candle's flame danced in the dark.","imageKeyword":"flame fire"},
{"word":"spark","level":1,"definition":"a tiny flash of fire","example":"A spark flew up from the campfire.","imageKeyword":"spark"},
{"word":"smoke","level":1,"definition":"the gray cloud that comes from fire","example":"Smoke rose from the chimney into the sky.","imageKeyword":"smoke"},
{"word":"ash","level":1,"definition":"the gray powder left after fire","example":"After the campfire, only ash was left.","imageKeyword":"ash"},
{"word":"dawn","level":1,"definition":"when the sun first comes up","example":"The rooster crowed at dawn.","imageKeyword":"dawn sunrise"},
{"word":"dusk","level":1,"definition":"when the sun is going down","example":"The fireflies came out at dusk.","imageKeyword":"dusk sunset"},
{"word":"midnight","level":1,"definition":"twelve o'clock at night","example":"The clock struck midnight and everyone was asleep.","imageKeyword":"midnight"},
{"word":"noon","level":1,"definition":"twelve o'clock in the day","example":"We eat lunch at noon every day.","imageKeyword":"noon midday"},
{"word":"passenger","level":1,"definition":"a person riding in a car or bus","example":"Every passenger on the bus found a seat.","imageKeyword":"passenger"},
{"word":"neighbor","level":1,"definition":"a person who lives near you","example":"Our neighbor brought us cookies when we moved in.","imageKeyword":"neighbor"},
{"word":"stranger","level":1,"definition":"a person you do not know","example":"Dad said never to talk to a stranger.","imageKeyword":"stranger"},
{"word":"parade","level":1,"definition":"people marching together down a street","example":"The parade had music and colorful floats.","imageKeyword":"parade"},
{"word":"audience","level":1,"definition":"people watching a show","example":"The audience clapped at the end of the play.","imageKeyword":"audience"},
{"word":"crew","level":1,"definition":"a group of people working together","example":"The crew fixed the road in just one day.","imageKeyword":"crew workers"},
{"word":"coach","level":1,"definition":"a person who teaches a sport","example":"The basketball coach taught them a new play during halftime.","imageKeyword":"coach"},
{"word":"chef","level":1,"definition":"a person who cooks food as a job","example":"The chef made the best soup I ever tasted.","imageKeyword":"chef cooking"},
{"word":"mayor","level":1,"definition":"the leader of a town","example":"The mayor cut the ribbon to open the new park.","imageKeyword":"mayor"},
{"word":"inventor","level":1,"definition":"a person who makes new things","example":"The inventor built a machine that could fly.","imageKeyword":"inventor"},
{"word":"princess","level":1,"definition":"the daughter of a king and queen","example":"The princess wore a golden crown on her head.","imageKeyword":"princess"},
{"word":"knight","level":1,"definition":"a soldier in armor from long ago","example":"The brave knight rode his horse into battle.","imageKeyword":"knight armor"},
{"word":"wizard","level":1,"definition":"a person with magic powers in stories","example":"The wizard waved his wand and made sparks fly.","imageKeyword":"wizard"},
{"word":"giant","level":1,"definition":"a very tall person in stories","example":"The giant was so big his head touched the clouds.","imageKeyword":"giant"},
{"word":"dwarf","level":1,"definition":"a very small person in stories","example":"The tiny dwarf lived inside the hollow tree.","imageKeyword":"dwarf"},
{"word":"monster","level":1,"definition":"a scary creature in stories","example":"The monster under the bed was just a pile of toys.","imageKeyword":"friendly monster"},
{"word":"dragon","level":1,"definition":"a big lizard that breathes fire in stories","example":"The dragon spread its wings and flew over the castle.","imageKeyword":"dragon"},
{"word":"fairy","level":1,"definition":"a tiny person with wings in stories","example":"The fairy sprinkled magic dust on the flowers.","imageKeyword":"fairy"},
{"word":"shield","level":1,"definition":"something you hold to stop things from hitting you","example":"The knight held up his shield to block the arrow.","imageKeyword":"shield"},
{"word":"sword","level":1,"definition":"a long sharp metal weapon from old times","example":"The hero pulled the sword from the stone.","imageKeyword":"sword"},
{"word":"wand","level":1,"definition":"a magic stick","example":"She waved her wand and the pumpkin became a coach.","imageKeyword":"magic wand"},
{"word":"throne","level":1,"definition":"a fancy chair for a king or queen","example":"The king sat on his golden throne.","imageKeyword":"throne"},
{"word":"crown","level":1,"definition":"a fancy hat for a king or queen","example":"The crown was covered in shiny jewels.","imageKeyword":"crown"},
{"word":"wobble","level":1,"definition":"to move side to side in an unsteady way","example":"The table started to wobble when she leaned on it.","imageKeyword":"toddler wobbling first steps"},
{"word":"tumble","level":1,"definition":"to fall and roll","example":"The blocks started to tumble when he pulled the bottom one.","imageKeyword":"child tumbling on grass"},
{"word":"snuggle","level":1,"definition":"to get close and cozy with someone","example":"The kitten liked to snuggle up next to its mother.","imageKeyword":"child snuggling teddy bear bed"},
{"word":"nibble","level":1,"definition":"to eat in tiny bites","example":"The mouse would nibble on the corner of the cracker.","imageKeyword":"mouse nibbling cheese"},
{"word":"snore","level":1,"definition":"to make noise while sleeping","example":"Grandpa would snore so loudly you could hear it downstairs.","imageKeyword":"snoring"},
{"word":"yawn","level":1,"definition":"to open your mouth wide when tired","example":"She started to yawn because it was past her bedtime.","imageKeyword":"yawning"},
{"word":"shiver","level":1,"definition":"to shake because you are cold","example":"Standing in the snow made her shiver.","imageKeyword":"shivering cold"},
{"word":"bloom","level":1,"definition":"when a flower opens up","example":"The roses bloom every spring in our garden.","imageKeyword":"blooming flower"},
{"word":"sprout","level":1,"definition":"when a plant first comes out of a seed","example":"A tiny green sprout poked out of the dirt.","imageKeyword":"sprout"},
{"word":"wilt","level":1,"definition":"when a plant droops because it needs water","example":"The flower started to wilt in the hot sun.","imageKeyword":"wilting flower"},
{"word":"scattered","level":1,"definition":"spread out in different places","example":"Toys were scattered all over the bedroom floor.","imageKeyword":"crayons scattered across floor"},
{"word":"rascal","level":1,"definition":"a naughty but funny child or animal","example":"That little rascal got into the cookie jar again!","imageKeyword":"mischievous puppy in cookie jar"},
{"word":"gigantic","level":1,"definition":"extremely big, bigger than big","example":"The gigantic dinosaur was bigger than our house.","imageKeyword":"gigantic dinosaur next to house"},
{"word":"itsy","level":1,"definition":"playfully tiny, smaller than your fingertip","example":"An itsy bitsy spider climbed up the water spout.","imageKeyword":"tiny spider"},
{"word":"whirl","level":1,"definition":"to spin around and around","example":"The leaves whirl in the wind like little dancers.","imageKeyword":"spinning top whirling"},
{"word":"sparkle","level":1,"definition":"to shine with little flashes of light","example":"The snow made everything sparkle in the sunshine.","imageKeyword":"sparkling"},
{"word":"flutter","level":1,"definition":"to move wings quickly up and down","example":"The butterfly would flutter from one flower to the next.","imageKeyword":"fluttering butterfly"},
{"word":"hear","level":1,"definition":"to notice sounds with your ears","example":"You can hear the crowd cheering at the basketball game from outside.","imageKeyword":"child listening to loud basketball crowd"},
{"word":"lose","level":1,"definition":"to not be able to find something, or to not win","example":"Our team didn't want to lose the basketball game, so we practiced every day.","imageKeyword":"basketball team losing game sad faces"},
{"word":"teach","level":1,"definition":"to help someone learn something new","example":"My big brother will teach me how to write my first code.","imageKeyword":"older kid teaching younger kid on computer"},
{"word":"take","level":1,"definition":"to get hold of something with your hands","example":"Please take a cookie from the plate.","imageKeyword":"hand taking cookie from plate"},
{"word":"than","level":1,"definition":"a word used to compare two things","example":"She scored more points than anyone else on the basketball team.","imageKeyword":"basketball scoreboard comparing two numbers"}];
