const LEVEL2D_BANK=[{"word":"pace","level":2,"definition":"the speed at which something moves or happens","example":"She set a fast pace and finished the race in first place.","imageKeyword":"running speed"},
{"word":"panel","level":2,"definition":"a flat piece that is part of a wall or machine","example":"The solar panel on the roof turns sunlight into power.","imageKeyword":"solar panel"},
{"word":"participate","level":2,"definition":"to join in and be part of an activity","example":"Everyone participated in the school talent show.","imageKeyword":"joining in"},
{"word":"passion","level":2,"definition":"a very strong love for something","example":"His passion for drawing led him to fill ten sketchbooks.","imageKeyword":"passionate artist"},
{"word":"passive","level":2,"definition":"not taking action, just letting things happen","example":"The cat was passive and just watched the mouse run by.","imageKeyword":"watching cat"},
{"word":"patent","level":2,"definition":"official right to be the only one who makes an invention","example":"The inventor got a patent so no one could copy her idea.","imageKeyword":"invention paper"},
{"word":"peer","level":2,"definition":"someone your own age or level","example":"He shared his story with his peers in reading circle.","imageKeyword":"classmates group"},
{"word":"perceive","level":2,"definition":"to see, hear, or feel something","example":"She perceived a change in the weather when clouds rolled in.","imageKeyword":"noticing clouds"},
{"word":"peril","level":2,"definition":"great danger that could cause death or serious harm","example":"The baby birds were in peril when the cat climbed the tree.","imageKeyword":"danger warning"},
{"word":"period","level":2,"definition":"a length of time","example":"We have a reading period every day after lunch.","imageKeyword":"clock period"},
{"word":"permanent","level":2,"definition":"lasting for all time and not going away","example":"The marker left a permanent stain on his white shirt.","imageKeyword":"permanent mark"},
{"word":"permit","level":2,"definition":"to allow someone to do something","example":"The teacher permitted the class to work outside today.","imageKeyword":"allowed pass"},
{"word":"persist","level":2,"definition":"to keep going even when it is hard","example":"She persisted in practicing until she could do a cartwheel.","imageKeyword":"keep trying"},
{"word":"perspective","level":2,"definition":"the way you see and think about something","example":"From the bird's perspective, the people below look tiny.","imageKeyword":"bird view"},
{"word":"phenomenon","level":2,"definition":"something odd or cool that happens","example":"A rainbow after a storm is a beautiful natural phenomenon.","imageKeyword":"rainbow sky"},
{"word":"philosophy","level":2,"definition":"a way of thinking about life and big questions","example":"Her philosophy is to be kind to everyone she meets.","imageKeyword":"thinking deeply"},
{"word":"physical","level":2,"definition":"about the body, or something you can see and touch","example":"Physical activity like running and jumping keeps your body strong and healthy.","imageKeyword":"child doing jumping jacks"},
{"word":"plea","level":2,"definition":"a serious and full of feeling request","example":"The lost kitten made a plea for help with its loud meowing.","imageKeyword":"begging kitten"},
{"word":"pledge","level":2,"definition":"a promise to do something good in the future","example":"He made a pledge to always tell the truth.","imageKeyword":"hand on heart"},
{"word":"plunge","level":2,"definition":"to jump or dive quickly into something","example":"He plunged into the lake to cool off on the hot day.","imageKeyword":"diving splash"},
{"word":"policy","level":2,"definition":"a rule or plan that a group follows","example":"The school policy says no hats inside the building.","imageKeyword":"rules poster"},
{"word":"polish","level":2,"definition":"to rub something until it shines","example":"He polished the old coin until it looked brand new.","imageKeyword":"shiny coin"},
{"word":"pose","level":2,"definition":"to stand or sit in a certain way for a picture","example":"The family posed together for a photo in front of the tree.","imageKeyword":"posing photo"},
{"word":"potential","level":2,"definition":"the ability to become something great in the future","example":"The coach said she has the potential to be a great swimmer.","imageKeyword":"growing potential"},
{"word":"poverty","level":2,"definition":"being very poor and not having basic needs","example":"Many groups work to end poverty around the world.","imageKeyword":"helping poor"},
{"word":"practical","level":2,"definition":"useful in real life, not just in theory","example":"A rain jacket is a practical gift for someone who walks to school.","imageKeyword":"useful jacket"},
{"word":"prefer","level":2,"definition":"to like one thing better than another","example":"I prefer chocolate ice cream over vanilla.","imageKeyword":"choosing favorite"},
{"word":"prejudice","level":2,"definition":"unfair feelings about someone before you know them","example":"Judging people by how they look is a form of prejudice.","imageKeyword":"unfair judgment"},
{"word":"preserve","level":2,"definition":"to keep something safe so it lasts a long time","example":"The museum preserves old paintings, so people can enjoy them for all time.","imageKeyword":"museum preserving"},
{"word":"pressure","level":2,"definition":"the force of pushing against something","example":"Too much pressure on the pencil will break the tip.","imageKeyword":"pressing hard"},
{"word":"presume","level":2,"definition":"to believe something is true without proof","example":"I presume she went home because her bag is gone.","imageKeyword":"guessing believe"},
{"word":"prevail","level":2,"definition":"to win or succeed after a struggle","example":"Good will prevail over evil in the end of the story.","imageKeyword":"victory triumph"},
{"word":"prevent","level":2,"definition":"to stop something from happening","example":"Wearing a helmet can prevent head injuries when biking.","imageKeyword":"helmet safety"},
{"word":"primary","level":2,"definition":"the most important or first","example":"Her primary goal this year is to learn multiplication.","imageKeyword":"number one"},
{"word":"principle","level":2,"definition":"a basic rule or belief that guides behavior","example":"Honesty is an important principle in our family.","imageKeyword":"rule belief"},
{"word":"priority","level":2,"definition":"the thing that matters most and should come first","example":"Safety is the top priority at the swimming pool.","imageKeyword":"first important"},
{"word":"privilege","level":2,"definition":"a special right that not everyone gets","example":"Using the computer lab is a privilege, not a right.","imageKeyword":"special access"},
{"word":"proceed","level":2,"definition":"to move forward or keep on doing something","example":"After the bell rings, proceed to the cafeteria for lunch.","imageKeyword":"moving forward"},
{"word":"process","level":2,"definition":"a series of steps to make or do something","example":"The process of making bread starts with mixing flour and water.","imageKeyword":"bread steps"},
{"word":"proclaim","level":2,"definition":"to announce something loudly and proudly","example":"The mayor proclaimed Saturday as Town Cleanup Day.","imageKeyword":"announcing loudly"},
{"word":"produce","level":2,"definition":"to make or grow something","example":"The farm produces fresh milk and eggs every day.","imageKeyword":"farm produce"},
{"word":"profit","level":2,"definition":"money earned after paying all the costs","example":"He sold his handmade bracelets for five dollars each and made a nice profit.","imageKeyword":"earning profit"},
{"word":"progress","level":2,"definition":"moving forward toward a goal","example":"She made great progress in reading this semester.","imageKeyword":"progress bar"},
{"word":"prohibit","level":2,"definition":"to say that something is not allowed by a rule","example":"The sign prohibits skateboarding in the parking lot.","imageKeyword":"no skateboard sign"},
{"word":"project","level":2,"definition":"a planned piece of work with a goal","example":"Our science project is to build a volcano that erupts.","imageKeyword":"science volcano"},
{"word":"promote","level":2,"definition":"to help something grow or become more popular","example":"The poster promotes reading by listing fun book titles.","imageKeyword":"book poster"},
{"word":"prompt","level":2,"definition":"done quickly without delay","example":"Thank you for your prompt reply to my question.","imageKeyword":"quick reply"},
{"word":"proof","level":2,"definition":"something that shows a fact is true","example":"The photo was proof that she had visited the Grand Canyon.","imageKeyword":"photo proof"},
{"word":"proportion","level":2,"definition":"how big one part is compared to the whole","example":"A large proportion of the class chose pizza as their favorite food.","imageKeyword":"pie chart"},
{"word":"propose","level":2,"definition":"to suggest an idea for others to think about","example":"She proposed having a movie night for the class party.","imageKeyword":"suggesting idea"},
{"word":"prospect","level":2,"definition":"the chance of something good happening in the future","example":"The prospect of a summer trip made the students excited.","imageKeyword":"exciting future"},
{"word":"prosper","level":2,"definition":"to do well and be successful","example":"The little shop prospered because everyone loved its cookies.","imageKeyword":"thriving shop"},
{"word":"provision","level":2,"definition":"supplies needed for a trip or activity","example":"They packed provisions for the hike including food and water.","imageKeyword":"packed supplies"},
{"word":"provoke","level":2,"definition":"to do something on purpose to make someone upset","example":"Don't provoke the dog by pulling its tail.","imageKeyword":"teasing dog"},
{"word":"publish","level":2,"definition":"to make writing available for people to read","example":"The school published a newspaper written by students.","imageKeyword":"newspaper print"},
{"word":"purchase","level":2,"definition":"to buy something","example":"He saved up to purchase a new bicycle for himself.","imageKeyword":"buying bike"},
{"word":"pursue","level":2,"definition":"to try to get or follow something","example":"He pursued his dream of becoming an artist by painting every day.","imageKeyword":"chasing dream"},
{"word":"qualify","level":2,"definition":"to meet the requirements for something","example":"You must be at least eight to qualify for the swim team.","imageKeyword":"meeting requirements"},
{"word":"quote","level":2,"definition":"to repeat someone else's exact words","example":"She quoted her favorite line from the book during show and tell.","imageKeyword":"quote marks"},
{"word":"random","level":2,"definition":"chosen without any plan or pattern","example":"The teacher picked a random name from the hat to go first.","imageKeyword":"picking hat"},
{"word":"ratio","level":2,"definition":"a comparison of two numbers showing how much of each","example":"The ratio of boys to girls in our class is three to two.","imageKeyword":"comparing numbers"},
{"word":"react","level":2,"definition":"to do something because of what just happened","example":"How did you react when you heard the good news?","imageKeyword":"surprised reaction"},
{"word":"realistic","level":2,"definition":"close to how things really are","example":"Her painting of the cat was so realistic it looked like a photo.","imageKeyword":"realistic painting"},
{"word":"realm","level":2,"definition":"a kingdom or area of interest","example":"In the realm of science, she was the top student.","imageKeyword":"kingdom realm"},
{"word":"rebel","level":2,"definition":"to fight against rules or authority","example":"The teenager rebelled by wearing mismatched socks to school.","imageKeyword":"breaking rules"},
{"word":"recall","level":2,"definition":"to remember something from the past","example":"I can recall the day we adopted our dog from the shelter.","imageKeyword":"remembering memory"},
{"word":"recommend","level":2,"definition":"to suggest that something is good","example":"I recommend this book because it is funny and exciting.","imageKeyword":"thumbs up book"},
{"word":"recover","level":2,"definition":"to get well again after being sick or hurt","example":"It took two weeks to recover from the flu.","imageKeyword":"getting better"},
{"word":"reference","level":2,"definition":"information you look at to help with something","example":"He used the dictionary as a reference to check the spelling.","imageKeyword":"reference book"},
{"word":"reflect","level":2,"definition":"to think carefully about something or to bounce backlight","example":"The lake reflected the mountains like a giant mirror.","imageKeyword":"lake reflection"},
{"word":"reform","level":2,"definition":"to change a system or rule to make it better","example":"The school reformed its lunch menu to include healthier choices.","imageKeyword":"improving change"},
{"word":"refuse","level":2,"definition":"to say no and not do something","example":"The stubborn mule refused to walk any further up the hill.","imageKeyword":"stubborn mule"},
{"word":"regard","level":2,"definition":"to think about someone or something in a certain way","example":"The students regard their teacher as very kind and fair.","imageKeyword":"looking up to"},
{"word":"register","level":2,"definition":"to sign up officially for something","example":"You must register before the first day of swim lessons.","imageKeyword":"signing up"},
{"word":"regret","level":2,"definition":"to feel sorry about something you did","example":"She regretted not bringing an umbrella when it started raining.","imageKeyword":"sorry rain"},
{"word":"regular","level":2,"definition":"happening at the same time or in the same way","example":"We have regular meetings every Monday morning.","imageKeyword":"calendar routine"},
{"word":"reinforce","level":2,"definition":"to make something stronger","example":"They reinforced the sandcastle walls with wet sand.","imageKeyword":"strong walls"},
{"word":"reject","level":2,"definition":"to say no to something offered","example":"She rejected the broken toy and asked for a new one.","imageKeyword":"saying no"},
{"word":"relate","level":2,"definition":"to see a connection between things","example":"I can relate to that story because something similar happened to me.","imageKeyword":"connecting dots"},
{"word":"release","level":2,"definition":"to let go or set free","example":"They released the healed bird back into the sky.","imageKeyword":"bird flying free"},
{"word":"relevant","level":2,"definition":"connected to what you are talking about","example":"Please share only facts that are relevant to the topic.","imageKeyword":"puzzle piece fitting"},
{"word":"relief","level":2,"definition":"the good feeling when something bad stops","example":"She felt relief when she found her lost homework in her bag.","imageKeyword":"relieved sigh"},
{"word":"rely","level":2,"definition":"to trust and depend on someone or something","example":"We rely on the sun to give plants the light they need.","imageKeyword":"depending sun"},
{"word":"remain","level":2,"definition":"to stay in the same place or condition","example":"Please remain in your seat until the bus stops completely.","imageKeyword":"staying seated"},
{"word":"remarkable","level":2,"definition":"so good that people notice","example":"It is remarkable that a computer can now write essays and draw pictures.","imageKeyword":"amazing flip"},
{"word":"remedy","level":2,"definition":"something that fixes a problem or sickness","example":"Honey and lemon tea is a good remedy for a sore throat.","imageKeyword":"honey tea"},
{"word":"remote","level":2,"definition":"far away from towns and people","example":"The cabin was in a remote area with no neighbors for miles.","imageKeyword":"isolated cabin"},
{"word":"remove","level":2,"definition":"to take something away","example":"Please remove your shoes before stepping on the clean floor.","imageKeyword":"taking off shoes"},
{"word":"renew","level":2,"definition":"to make something new or fresh again","example":"He renewed his library card, so he could keep borrowing books.","imageKeyword":"fresh start"},
{"word":"replace","level":2,"definition":"to put something new in place of the old one","example":"We need to replace the old batteries in the remote.","imageKeyword":"new batteries"},
{"word":"reputation","level":2,"definition":"opinions about you based on what you have done","example":"She has a reputation for always being honest and kind.","imageKeyword":"good name"},
{"word":"resemble","level":2,"definition":"to look like someone or something else","example":"The cloud resembled a fluffy white rabbit in the sky.","imageKeyword":"cloud shape"},
{"word":"reserve","level":2,"definition":"to save something for later or for a special use","example":"We reserved a table at the restaurant for Mom's birthday.","imageKeyword":"reserved sign"},
{"word":"reside","level":2,"definition":"to live in a particular place","example":"Many animals reside in the forest near our school.","imageKeyword":"forest home"},
{"word":"resist","level":2,"definition":"to fight against or not give in to something","example":"She had to resist eating the cookie until after dinner.","imageKeyword":"willpower cookie"},
{"word":"resolve","level":2,"definition":"to find a solution to a problem","example":"The friends resolved their argument by talking calmly.","imageKeyword":"solving problem"},
{"word":"restore","level":2,"definition":"to bring something back to how it was before","example":"Volunteers restored the old playground with fresh paint.","imageKeyword":"painting new"},
{"word":"restrict","level":2,"definition":"to limit or keep within certain rules","example":"The pool restricts diving to the deep end only.","imageKeyword":"deep end only"},
{"word":"retain","level":2,"definition":"to keep or hold on to something","example":"Sponges retain water even after you squeeze them.","imageKeyword":"sponge holding water"},
{"word":"retire","level":2,"definition":"to stop working because of age","example":"Grandpa retired from his job, and now spends time gardening.","imageKeyword":"retired gardening"},
{"word":"retreat","level":2,"definition":"to go back or move away from danger","example":"The hikers retreated when the storm got worse.","imageKeyword":"stepping back"},
{"word":"revenue","level":2,"definition":"money that comes in from selling things","example":"The bake sale brought in enough revenue to buy new books.","imageKeyword":"money earned"},
{"word":"reverse","level":2,"definition":"to go backward or make something opposite","example":"He reversed the car slowly out of the parking spot.","imageKeyword":"car backing up"},
{"word":"revise","level":2,"definition":"to change and improve something you wrote","example":"She revised her essay to fix spelling errors.","imageKeyword":"editing paper"},
{"word":"revolt","level":2,"definition":"to rise up and fight against authority","example":"The people revolted because the taxes were not fair.","imageKeyword":"protest uprising"},
{"word":"reward","level":2,"definition":"something good given for doing something well","example":"The reward for finding the lost dog was twenty dollars.","imageKeyword":"reward poster"},
{"word":"rigid","level":2,"definition":"stiff and hard to bend","example":"The frozen stick was rigid and snapped when she tried to bend it.","imageKeyword":"stiff stick"},
{"word":"rival","level":2,"definition":"someone you compete against","example":"The two soccer teams have been rivals for many years.","imageKeyword":"competing teams"},
{"word":"routine","level":2,"definition":"things you do the same way every day","example":"Her morning routine includes brushing teeth and eating breakfast.","imageKeyword":"morning routine"},
{"word":"ruin","level":2,"definition":"to damage something so badly it cannot be used","example":"The flood ruined all the books in the basement.","imageKeyword":"ruined books"},
{"word":"sacred","level":2,"definition":"holy or very special and important","example":"The ancient temple was a sacred place for the villagers.","imageKeyword":"sacred temple"},
{"word":"sacrifice","level":2,"definition":"to give up something important for a good reason","example":"He sacrificed his free time to help his friend study.","imageKeyword":"giving up"},
{"word":"satisfactory","level":2,"definition":"good enough but not the best","example":"His work was satisfactory, but the teacher knew he could do better.","imageKeyword":"okay grade"},
{"word":"schedule","level":2,"definition":"a plan that tells when things will happen","example":"The class schedule shows math at nine and reading at ten.","imageKeyword":"daily schedule"},
{"word":"scheme","level":2,"definition":"a plan to do something, sometimes sneaky","example":"The squirrel had a scheme to steal nuts from the bird feeder.","imageKeyword":"sneaky plan"},
{"word":"scope","level":2,"definition":"how much a topic covers or includes","example":"The scope of the project includes both plants and animals.","imageKeyword":"wide view"},
{"word":"secure","level":2,"definition":"safe and protected from danger","example":"Make sure the gate is secure, so the puppy cannot run out.","imageKeyword":"locked gate"},
{"word":"segment","level":2,"definition":"one piece or section of something","example":"She peeled the orange and shared each segment with friends.","imageKeyword":"orange segment"},
{"word":"seize","level":2,"definition":"to grab something quickly and firmly","example":"The eagle seized the fish from the water with its talons.","imageKeyword":"eagle grabbing"},
{"word":"sensation","level":2,"definition":"a feeling in your body or something that excites everyone","example":"The cold water gave a tingling sensation on her feet.","imageKeyword":"tingling feeling"},
{"word":"sequence","level":2,"definition":"things arranged in a specific order","example":"The computer runs each command in sequence, one line after another from top to bottom.","imageKeyword":"ordering steps"},
{"word":"series","level":2,"definition":"a number of things that come one after another","example":"She read the whole series of books about the magical school.","imageKeyword":"book series"},
{"word":"shift","level":2,"definition":"to move or change from one thing to another","example":"The wind shifted direction and blew the kite the other way.","imageKeyword":"wind changing"},
{"word":"significant","level":2,"definition":"important and worth paying attention to","example":"Getting into the spelling bee finals was a significant achievement.","imageKeyword":"important event"},
{"word":"similar","level":2,"definition":"almost the same but not exactly","example":"The twins wear similar clothes but different colored shoes.","imageKeyword":"look-alike twins"},
{"word":"simplify","level":2,"definition":"to make something less complicated","example":"The teacher simplified the math problem by breaking it into steps.","imageKeyword":"easy steps"},
{"word":"simulate","level":2,"definition":"to pretend or copy how something works","example":"The computer can simulate a real basketball game to test different strategies.","imageKeyword":"flight simulator"},
{"word":"site","level":2,"definition":"a place where something is or happens","example":"The construction site was busy with trucks and workers.","imageKeyword":"building site"},
{"word":"sketch","level":2,"definition":"a quick rough drawing","example":"He made a sketch of his cat before painting it.","imageKeyword":"pencil sketch"},
{"word":"slight","level":2,"definition":"very small in amount","example":"There was a slight breeze that barely moved the leaves.","imageKeyword":"gentle breeze"},
{"word":"sole","level":2,"definition":"the only one","example":"She was the sole person who finished the puzzle.","imageKeyword":"only one"},
{"word":"specific","level":2,"definition":"clear and exact, not general","example":"Give me specific directions, so I don't get lost.","imageKeyword":"exact directions"},
{"word":"spite","level":2,"definition":"doing something mean on purpose to upset someone","example":"He hid her pencil out of spite because she wouldn't share.","imageKeyword":"mean hiding"},
{"word":"standard","level":2,"definition":"the normal level of how good expected","example":"The standard for passing the test is seventy percent correct.","imageKeyword":"quality bar"},
{"word":"status","level":2,"definition":"the current state or position of something","example":"The status of the project is almost finished.","imageKeyword":"progress check"},
{"word":"steady","level":2,"definition":"firm and not shaking or changing","example":"Hold the camera steady, so the picture won't be blurry.","imageKeyword":"steady hands"},
{"word":"stock","level":2,"definition":"a supply of things kept for future use","example":"The store keeps a large stock of pencils for back-to-school season.","imageKeyword":"supply shelf"},
{"word":"strategy","level":2,"definition":"a careful plan to reach a goal","example":"Coach drew up a strategy on the whiteboard to beat their zone defense.","imageKeyword":"game plan"},
{"word":"stress","level":2,"definition":"worry or pressure that makes you feel tense","example":"Too much homework can cause stress if you don't take breaks.","imageKeyword":"stressed feeling"},
{"word":"strict","level":2,"definition":"having rules that must be followed exactly","example":"The strict teacher never allows late homework.","imageKeyword":"firm rules"},
{"word":"submit","level":2,"definition":"to give or hand in something for review","example":"Please submit your homework by Friday morning.","imageKeyword":"handing in paper"},
{"word":"substitute","level":2,"definition":"someone or something used in place of another","example":"When our teacher was sick, a substitute taught the class.","imageKeyword":"substitute teacher"},
{"word":"summit","level":2,"definition":"the very top of a mountain","example":"After hours of hiking, they reached the summit and saw the view.","imageKeyword":"mountain top"},
{"word":"superior","level":2,"definition":"better than others in quality or rank","example":"This paint is superior because it lasts longer in the rain.","imageKeyword":"best quality"},
{"word":"supplement","level":2,"definition":"something extra added to make something better","example":"She takes a vitamin supplement to stay healthy in winter.","imageKeyword":"vitamin extra"},
{"word":"suspect","level":2,"definition":"to believe someone might have done something wrong","example":"I suspect the cat knocked the cup off the table.","imageKeyword":"suspicious looking"},
{"word":"suspend","level":2,"definition":"to hang something from above or stop for now","example":"The spider suspended its web between two branches.","imageKeyword":"hanging web"},
{"word":"sustain","level":2,"definition":"to keep going or support for a long time","example":"Plants need water and sun to sustain their growth.","imageKeyword":"sustained growth"},
{"word":"sympathy","level":2,"definition":"feeling sorry for someone who is sad or hurt","example":"She showed sympathy by writing a kind note to her sick friend.","imageKeyword":"caring note"},
{"word":"tactic","level":2,"definition":"a clever action to help win or succeed","example":"His tactic in the game was to save his strongest card for last.","imageKeyword":"clever move"},
{"word":"target","level":2,"definition":"something you aim at or try to reach","example":"The archer aimed carefully and hit the center of the target.","imageKeyword":"bullseye hit"},
{"word":"task","level":2,"definition":"a job or piece of work that needs to be done","example":"His first task of the morning is to feed the classroom fish.","imageKeyword":"checklist task"},
{"word":"technique","level":2,"definition":"a special way of doing something skillfully","example":"The artist taught us a technique for drawing faces.","imageKeyword":"art technique"},
{"word":"tense","level":2,"definition":"tight and nervous, not relaxed","example":"His muscles felt tense before the big race started.","imageKeyword":"tense muscles"},
{"word":"theory","level":2,"definition":"an idea that explains how something works","example":"Her theory is that plants grow better with classical music.","imageKeyword":"idea theory"},
{"word":"thorough","level":2,"definition":"done with care and completely","example":"She did a thorough job cleaning her room—even under the bed.","imageKeyword":"spotless clean"},
{"word":"threaten","level":2,"definition":"to say you will hurt or harm someone","example":"Dark clouds threatened to bring a storm to the picnic.","imageKeyword":"dark clouds"},
{"word":"thrive","level":2,"definition":"to grow strong and do really well","example":"Cactus plants thrive in hot dry places with lots of sun.","imageKeyword":"thriving cactus"},
{"word":"tolerate","level":2,"definition":"to put up with something you do not like","example":"She tolerated the loud music until the song was over.","imageKeyword":"patience endure"},
{"word":"tone","level":2,"definition":"the feeling or attitude in someone's voice","example":"His friendly tone made the new student feel welcome.","imageKeyword":"friendly voice"},
{"word":"transfer","level":2,"definition":"to move something from one place to another","example":"He transferred the goldfish from the bag to the tank.","imageKeyword":"moving fish"},
{"word":"transparent","level":2,"definition":"clear enough to see through","example":"The transparent glass let sunlight fill the whole room.","imageKeyword":"clear glass"},
{"word":"trend","level":2,"definition":"a way things are moving or a well liked style","example":"The trend at school this year is wearing colorful socks.","imageKeyword":"popular style"},
{"word":"trial","level":2,"definition":"a test to see if something works","example":"The first trial of the paper airplane went crooked, so she adjusted the wings.","imageKeyword":"testing airplane"},
{"word":"tropical","level":2,"definition":"from hot wet places near the middle of the Earth","example":"Tropical birds have bright feathers of red, blue, and green.","imageKeyword":"colorful parrot"},
{"word":"trustworthy","level":2,"definition":"can be trusted to do the right thing","example":"A trustworthy friend keeps your secrets safe.","imageKeyword":"loyal friend"},
{"word":"undergo","level":2,"definition":"to experience or go through something","example":"The old building will undergo repairs to fix the roof.","imageKeyword":"building repairs"},
{"word":"unique","level":2,"definition":"one of a kind, unlike anything else","example":"Every person's fingerprint is unique—no two are alike.","imageKeyword":"fingerprint unique"},
{"word":"unite","level":2,"definition":"to join together as one group","example":"The whole school united to raise money for the food bank.","imageKeyword":"hands together"},
{"word":"universe","level":2,"definition":"everything that exists with all space","example":"The universe contains billions of stars and galaxies.","imageKeyword":"starry universe"},
{"word":"urge","level":2,"definition":"a strong feeling that you want to do something","example":"She had an urge to sneeze during the quiet test.","imageKeyword":"about to sneeze"},
{"word":"utilize","level":2,"definition":"to use something for a purpose","example":"We can utilize old jars as flower vases.","imageKeyword":"reusing jar"},
{"word":"valid","level":2,"definition":"right and true","example":"Your ticket is still valid for another hour.","imageKeyword":"valid ticket"},
{"word":"value","level":2,"definition":"how much something is worth or how important it is","example":"The value of honesty is something she learned from her grandmother.","imageKeyword":"treasure chest"},
{"word":"vehicle","level":2,"definition":"something used to carry people or things","example":"A bus is a vehicle that takes many students to school.","imageKeyword":"school bus"},
{"word":"venture","level":2,"definition":"a risky trip or new project","example":"Starting a lemonade stand was their first business venture.","imageKeyword":"lemonade business"},
{"word":"version","level":2,"definition":"one form of something that is slightly different from others","example":"The movie is a newer version of the old fairy tale.","imageKeyword":"different versions"},
{"word":"vibrant","level":2,"definition":"bright and full of energy or color","example":"The vibrant painting used every color of the rainbow.","imageKeyword":"colorful painting"},
{"word":"violate","level":2,"definition":"to break a rule or law","example":"Running in the hallway violates the school safety rules.","imageKeyword":"broken rule"},
{"word":"virtual","level":2,"definition":"made by computer and not real","example":"The virtual assistant answered every question without needing a real person.","imageKeyword":"computer tour"},
{"word":"vision","level":2,"definition":"an idea or picture of the future","example":"His vision was a garden full of roses along every fence.","imageKeyword":"garden plan"},
{"word":"vital","level":2,"definition":"fully needed for life or success","example":"Oxygen is vital for humans to breathe and stay alive.","imageKeyword":"breathing oxygen"},
{"word":"volume","level":2,"definition":"how loud a sound is or how much space something fills","example":"Please turn down the volume on the TV—it is too loud.","imageKeyword":"volume knob"},
{"word":"voluntary","level":2,"definition":"done by choice, not because you have to","example":"Helping at the animal shelter is voluntary—you do it because you want to.","imageKeyword":"choosing to help"},
{"word":"vulnerable","level":2,"definition":"easy to hurt or in danger of being harmed","example":"Baby turtles are vulnerable to birds when they walk to the sea.","imageKeyword":"baby turtle"},
{"word":"warrant","level":2,"definition":"to be a good enough reason for something","example":"The strange noise was enough to warrant a closer look by the teacher.","imageKeyword":"looking closer"},
{"word":"welfare","level":2,"definition":"the health and happiness of a person or group","example":"The vet cares about the welfare of all the animals in the clinic.","imageKeyword":"caring vet"},
{"word":"widespread","level":2,"definition":"found in many places or with many people","example":"Widespread rain made puddles on every street in town.","imageKeyword":"rain everywhere"},
{"word":"withdraw","level":2,"definition":"to take back or move away from something","example":"She withdrew her hand from the hot stove quickly.","imageKeyword":"pulling back"},
{"word":"worthy","level":2,"definition":"deserving of respect or focus","example":"Helping others is a worthy way to spend your time.","imageKeyword":"deserving respect"},
{"word":"yield","level":2,"definition":"to give way or produce something","example":"The apple tree yielded a hundred apples this fall.","imageKeyword":"apple harvest"},
{"word":"zone","level":2,"definition":"an area set apart for a special purpose","example":"The quiet zone in the library is for reading only.","imageKeyword":"quiet zone"},
{"word":"abolish","level":2,"definition":"to officially end or get rid of a rule or practice","example":"The school abolished the old dress code and let students wear what they want.","imageKeyword":"removing rule"},
{"word":"accelerate","level":2,"definition":"to go faster or speed up","example":"The car accelerated when the light turned green.","imageKeyword":"speeding up"},
{"word":"ambition","level":2,"definition":"a strong desire to achieve something great","example":"Her ambition is to become the first person to walk on Mars.","imageKeyword":"reaching stars"},
{"word":"ample","level":2,"definition":"plenty, more than what you need","example":"There was ample room in the car for all five friends.","imageKeyword":"plenty space"},
{"word":"anticipate","level":2,"definition":"to expect something and get ready for it","example":"A great point guard can anticipate where the pass is going before it's thrown.","imageKeyword":"preparing umbrella"},
{"word":"apparatus","level":2,"definition":"a tool or machine used for a specific job","example":"The science apparatus included beakers and test tubes.","imageKeyword":"lab equipment"},
{"word":"appliance","level":2,"definition":"a machine in your home that does a job","example":"The refrigerator is an appliance that keeps food cold.","imageKeyword":"kitchen appliance"},
{"word":"appoint","level":2,"definition":"to choose someone for a job or role","example":"The principal appointed her as the new hall monitor.","imageKeyword":"choosing person"},
{"word":"asset","level":2,"definition":"something valuable or useful","example":"His speed is a great asset on the track team.","imageKeyword":"valuable skill"},
{"word":"bankrupt","level":2,"definition":"having no money left to pay what you owe","example":"The shop went bankrupt because no one bought anything.","imageKeyword":"empty wallet"},
{"word":"behalf","level":2,"definition":"in the interest of or representing someone","example":"She accepted the award on behalf of the whole team.","imageKeyword":"representing team"},
{"word":"betray","level":2,"definition":"to break someone's trust","example":"He felt betrayed when his friend told his secret.","imageKeyword":"broken trust"},
{"word":"biased","level":2,"definition":"not fair to both sides","example":"The judge must not be biased toward either team.","imageKeyword":"tilted scale"},
{"word":"bilateral","level":2,"definition":"involving two sides or groups","example":"The two countries signed a bilateral agreement to share resources.","imageKeyword":"two sides agree"},
{"word":"boast","level":2,"definition":"to talk proudly about yourself in an annoying way","example":"He boasted about his trophy until his friends got tired of hearing it.","imageKeyword":"bragging"},
{"word":"bonus","level":2,"definition":"something extra and good that you did not expect","example":"Finding money in her old coat was a nice bonus.","imageKeyword":"extra surprise"},
{"word":"brisk","level":2,"definition":"quick and energetic","example":"They took a brisk walk around the park before breakfast.","imageKeyword":"fast walk"},
{"word":"bulk","level":2,"definition":"a large amount or the biggest part","example":"The bulk of the work was finished before lunch.","imageKeyword":"large portion"},
{"word":"campaign","level":2,"definition":"an organized effort to achieve a goal","example":"The class ran a campaign to get recycling bins in every room.","imageKeyword":"campaign poster"},
{"word":"cease","level":2,"definition":"to stop completely","example":"The rain ceased, and the sun came out again.","imageKeyword":"rain stopping"},
{"word":"certify","level":2,"definition":"to officially say something is true or meets a standard","example":"The doctor certified that the food was safe to eat.","imageKeyword":"official stamp"},
{"word":"chronic","level":2,"definition":"lasting a long time or happening again and again","example":"His chronic cough lasted for three weeks before he saw a doctor.","imageKeyword":"lasting cough"},
{"word":"cite","level":2,"definition":"to mention as an example or proof","example":"She cited three reasons why free time should be longer.","imageKeyword":"listing reasons"},
{"word":"commence","level":2,"definition":"to begin or start","example":"The show will commence at noon sharp.","imageKeyword":"starting bell"},
{"word":"commission","level":2,"definition":"to officially ask someone to do a piece of work","example":"The town commissioned an artist to paint a mural on the library wall.","imageKeyword":"mural painting"},
{"word":"compact","level":2,"definition":"small and tightly packed together","example":"The compact car fits easily into the small parking space.","imageKeyword":"small car"},
{"word":"compel","level":2,"definition":"to force someone to do something","example":"The heavy rain compelled everyone to stay indoors.","imageKeyword":"forced inside"},
{"word":"component","level":2,"definition":"a part of something that works with other parts","example":"The wheels are an important component of a bicycle.","imageKeyword":"bike parts"},
{"word":"compound","level":2,"definition":"made of two or more parts mixed together","example":"Water is a compound made of hydrogen and oxygen.","imageKeyword":"mixing elements"},
{"word":"comprehensive","level":2,"definition":"covering everything, leaving nothing out","example":"The teacher gave a comprehensive review before the big test.","imageKeyword":"complete review"},
{"word":"compromise","level":2,"definition":"each side gives up something to reach an agreement","example":"They reached a compromise: pizza on Monday and tacos on Wednesday.","imageKeyword":"meeting middle"},
{"word":"compulsory","level":2,"definition":"required and must be done","example":"Wearing a seatbelt is compulsory for all in the car.","imageKeyword":"must do"},
{"word":"condemn","level":2,"definition":"to say strongly that something is wrong","example":"The mayor condemned the vandalism at the park.","imageKeyword":"strong disapproval"},
{"word":"conduct","level":2,"definition":"to lead or carry out something","example":"The scientist conducted a test with magnets.","imageKeyword":"leading experiment"},
{"word":"confront","level":2,"definition":"to face a problem or person directly","example":"He confronted his fear by holding the harmless spider.","imageKeyword":"facing fear"},
{"word":"considerable","level":2,"definition":"large enough to be important or noticed","example":"A considerable amount of snow fell overnight.","imageKeyword":"lots of snow"},
{"word":"consistent","level":2,"definition":"staying the same and not changing","example":"Her consistent practice made her the best speller in class.","imageKeyword":"same every day"},
{"word":"conspicuous","level":2,"definition":"easy to notice because it stands out","example":"The bright red hat was conspicuous in the crowd of gray coats.","imageKeyword":"standing out"},
{"word":"constitute","level":2,"definition":"to make up or form something","example":"Twelve months constitute one full year.","imageKeyword":"parts forming whole"},
{"word":"constrain","level":2,"definition":"to limit or hold back","example":"The small budget constrained how much they could spend on decorations.","imageKeyword":"limited budget"},
{"word":"contempt","level":2,"definition":"a feeling that something is worthless or below you","example":"He showed contempt for the easy puzzle by finishing it in seconds.","imageKeyword":"looking down"},
{"word":"contend","level":2,"definition":"to compete or deal with something difficult","example":"The team contended with strong winds during the sailing race.","imageKeyword":"fighting wind"},
{"word":"controversial","level":2,"definition":"causing disagreement among people","example":"The new homework rule was controversial—some liked it, some didn't.","imageKeyword":"split opinions"},
{"word":"convention","level":2,"definition":"a large meeting or the usual way of doing things","example":"The comic book convention brought fans from all over the country.","imageKeyword":"big gathering"},
{"word":"convert","level":2,"definition":"to change from one thing into another","example":"The garage was converted into a playroom.","imageKeyword":"changing room"},
{"word":"convey","level":2,"definition":"to communicate or carry a message","example":"Her smile conveyed that she was pleased with the gift.","imageKeyword":"sending message"},
{"word":"coordinate","level":2,"definition":"to organize people or things so they work together","example":"The teacher coordinated the school show with all the classes.","imageKeyword":"organizing together"},
{"word":"cope","level":2,"definition":"to deal with something difficult","example":"She learned to cope with her shyness by taking deep breaths.","imageKeyword":"deep breath calm"},
{"word":"corporate","level":2,"definition":"related to a large business firm","example":"The corporate office sent new computers to every school.","imageKeyword":"office building"},
{"word":"corrupt","level":2,"definition":"dishonest and willing to break rules for gain","example":"The corrupt official took money that belonged to the town.","imageKeyword":"dishonest person"},
{"word":"counsel","level":2,"definition":"advice or the person who gives advice","example":"The school counselor offered counsel on dealing with bullies.","imageKeyword":"giving advice"},
{"word":"counterpart","level":2,"definition":"a person or thing that has the same role in another place","example":"The class president met his counterpart from the other school.","imageKeyword":"matching role"},
{"word":"criterion","level":2,"definition":"a standard used to judge or decide something","example":"Neatness is one criterion for grading the art project.","imageKeyword":"judging standard"},
{"word":"crucial","level":2,"definition":"extremely important and needed","example":"Wearing sunscreen is crucial on a sunny beach day.","imageKeyword":"very important"},
{"word":"cultivate","level":2,"definition":"to grow plants or develop a skill over time","example":"The farmer cultivates tomatoes in the greenhouse.","imageKeyword":"growing tomatoes"},
{"word":"cumulative","level":2,"definition":"growing by adding more and more over time","example":"The cumulative effect of saving a dollar a day is a lot by year's end.","imageKeyword":"growing savings"},
{"word":"curriculum","level":2,"definition":"all the subjects taught at a school","example":"Art and music are part of our school's curriculum.","imageKeyword":"school subjects"},
{"word":"custody","level":2,"definition":"the right and duty to take care of someone","example":"The zookeeper has custody of all the baby animals.","imageKeyword":"caring for animals"},
{"word":"debris","level":2,"definition":"broken pieces scattered around after something is destroyed","example":"Debris from the fallen tree covered the sidewalk.","imageKeyword":"scattered pieces"},
{"word":"deficit","level":2,"definition":"not having enough, a shortage","example":"The team had a three-point deficit going into the last quarter.","imageKeyword":"behind score"},
{"word":"delegate","level":2,"definition":"to give a task to someone else","example":"The captain delegated the cleanup jobs to different team members.","imageKeyword":"assigning jobs"},
{"word":"depict","level":2,"definition":"to show something in a picture or words","example":"The mural depicts children playing in a garden.","imageKeyword":"painted scene"},
{"word":"deplete","level":2,"definition":"to use up until almost nothing is left","example":"If we use too much water, we will deplete the supply.","imageKeyword":"empty battery"},
{"word":"designate","level":2,"definition":"to officially choose for a purpose","example":"The teacher designated one shelf for finished work.","imageKeyword":"labeled shelf"},
{"word":"deteriorate","level":2,"definition":"to become worse over time","example":"The old fence deteriorated and began to fall apart.","imageKeyword":"crumbling fence"},
{"word":"dictate","level":2,"definition":"to say words for someone to write or to give orders","example":"She dictated the letter while her friend typed it.","imageKeyword":"speaking words"}];
